'use client';

import { FileText, Plus, Save, X } from 'lucide-react';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { EmptyState } from '@/components/empty-state';
import { LoadingPanel } from '@/components/loading';
import { StatusBadge } from '@/components/badge';
import { apiFetch, ApiError } from '@/lib/api';
import { BRL, formatDate } from '@/lib/format';
import type { Building, Contract, Supplier } from '@/lib/types';

const EMPTY = { code: '', supplierId: '', object: '', type: 'INTEGRATED_MAINTENANCE', status: 'ACTIVE', startDate: '', endDate: '', originalValue: '', administrativeProcess: '', buildingIds: [] as string[], notes: '' };

export default function ContractsPage() {
  const [items, setItems] = useState<Contract[]>([]); const [suppliers, setSuppliers] = useState<Supplier[]>([]);
  const [buildings, setBuildings] = useState<Building[]>([]); const [detail, setDetail] = useState<Contract | null>(null);
  const [form, setForm] = useState(EMPTY); const [showForm, setShowForm] = useState(false); const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false); const [error, setError] = useState(''); const [referenceTime] = useState(Date.now);
  const load = useCallback(async () => { try { const [contracts, supplierItems, buildingItems] = await Promise.all([
    apiFetch<Contract[]>('/contracts'), apiFetch<Supplier[]>('/suppliers'), apiFetch<Building[]>('/buildings')]);
    setItems(contracts); setSuppliers(supplierItems); setBuildings(buildingItems);
    setForm((current) => ({ ...current, supplierId: current.supplierId || supplierItems[0]?.id || '' }));
  } catch (cause) { setError(cause instanceof Error ? cause.message : 'Falha ao carregar contratos.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function openContract(id: string) { try { setDetail(await apiFetch<Contract>(`/contracts/${id}`)); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Falha ao abrir contrato.'); } }
  function toggleBuilding(id: string) { setForm((current) => ({ ...current, buildingIds: current.buildingIds.includes(id) ? current.buildingIds.filter((item) => item !== id) : [...current.buildingIds, id] })); }
  async function submit(event: FormEvent) { event.preventDefault(); setSubmitting(true); setError(''); try {
    await apiFetch('/contracts', { method: 'POST', body: JSON.stringify({ ...form, originalValue: Number(form.originalValue),
      administrativeProcess: form.administrativeProcess || undefined, buildingIds: form.buildingIds.length ? form.buildingIds : undefined,
      notes: form.notes || undefined }) }); setForm({ ...EMPTY, supplierId: suppliers[0]?.id || '' }); setShowForm(false); setLoading(true); await load();
  } catch (cause) { setError(cause instanceof ApiError ? cause.message : 'Não foi possível cadastrar o contrato.'); } finally { setSubmitting(false); } }
  return <div className="page-container"><header className="page-header"><div className="page-title"><h1>Contratos</h1><p>Dossiê central de vigência, valores, fornecedores, OS, empenhos e eventos contratuais.</p></div><button className="btn btn-primary" type="button" onClick={() => setShowForm((value) => !value)}>{showForm ? <X size={16} /> : <Plus size={16} />}{showForm ? 'Fechar cadastro' : 'Novo contrato'}</button></header>
  {error ? <div className="notice error" style={{ marginBottom: 18 }}>{error}</div> : null}
  {showForm ? <form className="card form-card" onSubmit={submit} style={{ marginBottom: 18 }}><section className="form-section"><div className="form-section-header"><h2>Dados gerais do contrato</h2><p>O valor atual é calculado pelo sistema a partir do valor original, aditivos e reajustes/repactuações.</p></div><div className="form-grid">
    <F c="col-3" l="Número/código *"><input className="input" required value={form.code} onChange={(event) => setForm({ ...form, code: event.target.value })} /></F>
    <F c="col-5" l="Fornecedor *"><select className="select" required value={form.supplierId} onChange={(event) => setForm({ ...form, supplierId: event.target.value })}><option value="">Selecione</option>{suppliers.map((item) => <option value={item.id} key={item.id}>{item.tradeName || item.legalName}</option>)}</select></F>
    <F c="col-4" l="Processo licitatório/contratação de origem"><input className="input" value={form.administrativeProcess} onChange={(event) => setForm({ ...form, administrativeProcess: event.target.value })} /></F>
    <F c="col-12" l="Objeto *"><textarea className="textarea" required value={form.object} onChange={(event) => setForm({ ...form, object: event.target.value })} /></F>
    <F c="col-4" l="Tipo *"><select className="select" value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })}><option value="PREVENTIVE_MAINTENANCE">Manutenção preventiva</option><option value="CORRECTIVE_MAINTENANCE">Manutenção corretiva</option><option value="INTEGRATED_MAINTENANCE">Manutenção integrada</option><option value="OUTSOURCED_LABOR">Mão de obra terceirizada</option><option value="SUPPLY">Fornecimento</option><option value="OTHER">Outro</option></select></F>
    <F c="col-2" l="Status"><select className="select" value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })}><option value="DRAFT">Rascunho</option><option value="ACTIVE">Ativo</option><option value="SUSPENDED">Suspenso</option><option value="EXPIRING">A vencer</option></select></F>
    <F c="col-3" l="Início da vigência *"><input className="input" required type="date" value={form.startDate} onChange={(event) => setForm({ ...form, startDate: event.target.value })} /></F>
    <F c="col-3" l="Fim da vigência *"><input className="input" required type="date" value={form.endDate} onChange={(event) => setForm({ ...form, endDate: event.target.value })} /></F>
    <F c="col-4" l="Valor original (R$) *"><input className="input" required type="number" min="0.01" step="0.01" value={form.originalValue} onChange={(event) => setForm({ ...form, originalValue: event.target.value })} /></F>
    <F c="col-8" l="Valor atual (calculado)"><input className="input" disabled value={form.originalValue ? BRL.format(Number(form.originalValue)) : 'Calculado automaticamente'} /></F>
    <F c="col-12" l="Edificações abrangidas"><div className="actions">{buildings.map((item) => <label className={`btn ${form.buildingIds.includes(item.id) ? 'btn-primary' : 'btn-secondary'}`} key={item.id}><input type="checkbox" checked={form.buildingIds.includes(item.id)} onChange={() => toggleBuilding(item.id)} style={{ display: 'none' }} />{item.code} — {item.name}</label>)}</div></F>
    <F c="col-12" l="Observações"><textarea className="textarea" value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} /></F>
  </div></section><div className="form-footer"><button className="btn btn-secondary" type="button" onClick={() => setShowForm(false)}>Cancelar</button><button className="btn btn-primary" disabled={submitting || !form.supplierId}><Save size={16} /> {submitting ? 'Salvando…' : 'Salvar contrato'}</button></div></form> : null}
  {loading ? <LoadingPanel /> : <section className="card table-card">{items.length ? <div className="table-wrapper"><table className="data-table"><thead><tr><th>Contrato / objeto</th><th>Fornecedor</th><th>Vigência</th><th>Status</th><th>Valor atual calculado</th><th>Medido</th><th>Saldo</th></tr></thead><tbody>{items.map((item) => { const balance = Number(item.currentValue) - Number(item.measuredValue); const days = Math.ceil((new Date(item.endDate).getTime() - referenceTime) / 86_400_000); return <tr key={item.id} onClick={() => void openContract(item.id)} style={{ cursor: 'pointer' }}><td><span className="table-primary">{item.code}</span><span className="table-secondary">{item.object}</span></td><td>{item.supplier.tradeName || item.supplier.legalName}</td><td><span className="table-primary">{formatDate(item.startDate)} a {formatDate(item.endDate)}</span><span className="table-secondary">{days >= 0 ? `${days} dia(s) restantes` : `vencido há ${Math.abs(days)} dia(s)`}</span></td><td><StatusBadge value={item.status} /></td><td>{BRL.format(Number(item.currentValue))}</td><td>{BRL.format(Number(item.measuredValue))}</td><td><span className={`badge ${balance < 0 ? 'danger' : 'success'}`}>{BRL.format(balance)}</span></td></tr>; })}</tbody></table></div> : <EmptyState icon={FileText} title="Nenhum contrato cadastrado" description="Cadastre o primeiro contrato para vincular fornecedores, edificações e ordens de serviço." />}</section>}
  {detail ? <ContractWorkspace contract={detail} suppliers={suppliers} onRefresh={async () => { await load(); await openContract(detail.id); }} onError={setError} /> : null}
  </div>;
}

const EVENT_EMPTY = { number: '', type: 'TERM_EXTENSION', description: '', signedAt: '', endDateAfter: '', valueChange: '', referencePeriod: '', approvalDate: '', percentage: '', amount: '', indexName: '', supplierId: '', subcontractorName: '', subcontractorTaxId: '', scope: '', approvedAt: '', authorizationCase: '', appliedAt: '', administrativeCase: '' };
function ContractWorkspace({ contract, suppliers, onRefresh, onError }: { contract: Contract; suppliers: Supplier[]; onRefresh(): Promise<void>; onError(value: string): void }) {
  const [tab, setTab] = useState('summary'); const [form, setForm] = useState(EVENT_EMPTY); const [saving, setSaving] = useState(false);
  const tabs = [['summary', 'Resumo'], ['amendments', 'Prazo e aditivos'], ['subcontracts', 'Subcontratações'], ['penalties', 'Sanções'], ['work-orders', 'Ordens de serviço'], ['adjustments', 'Reajustes e repactuações'], ['commitments', 'Empenhos']];
  async function submitEvent(event: FormEvent) { event.preventDefault(); setSaving(true); onError(''); try {
    let endpoint = ''; let payload: Record<string, unknown> = {};
    if (tab === 'amendments') { endpoint = 'amendments'; payload = { number: form.number, type: form.type, description: form.description, signedAt: form.signedAt || undefined, endDateAfter: form.endDateAfter || undefined, valueChange: form.valueChange ? Number(form.valueChange) : undefined }; }
    if (tab === 'adjustments') { endpoint = 'adjustments'; payload = { type: form.type, referencePeriod: form.referencePeriod, approvalDate: form.approvalDate, percentage: form.percentage ? Number(form.percentage) : undefined, amount: Number(form.amount), indexName: form.indexName || undefined }; }
    if (tab === 'subcontracts') { endpoint = 'subcontracts'; const selected = suppliers.find((item) => item.id === form.supplierId); payload = { supplierId: form.supplierId || undefined, subcontractorName: selected?.legalName || form.subcontractorName, subcontractorTaxId: selected?.taxId || form.subcontractorTaxId || undefined, scope: form.scope, approvedAt: form.approvedAt, authorizationCase: form.authorizationCase, amount: form.amount ? Number(form.amount) : undefined }; }
    if (tab === 'penalties') { endpoint = 'penalties'; payload = { type: form.type, administrativeCase: form.administrativeCase || undefined, description: form.description, appliedAt: form.appliedAt, amount: form.amount ? Number(form.amount) : undefined }; }
    await apiFetch(`/contracts/${contract.id}/${endpoint}`, { method: 'POST', body: JSON.stringify(payload) }); setForm(EVENT_EMPTY); await onRefresh();
  } catch (cause) { onError(cause instanceof Error ? cause.message : 'Falha ao registrar evento contratual.'); } finally { setSaving(false); } }
  return <section className="card form-card" style={{ marginTop: 18 }}><section className="form-section"><div className="form-section-header"><h2>Dossiê {contract.code}</h2><p>Processo de origem: {contract.administrativeProcess || 'não informado'} · fornecedor: {contract.supplier.tradeName || contract.supplier.legalName}</p></div><div className="actions" style={{ marginBottom: 18 }}>{tabs.map(([value, label]) => <button type="button" key={value} className={`btn ${tab === value ? 'btn-primary' : 'btn-secondary'}`} onClick={() => { setTab(value); setForm(EVENT_EMPTY); }}>{label}</button>)}</div>
  {tab === 'summary' ? <div className="kpi-grid"><Metric label="Valor original" value={BRL.format(Number(contract.originalValue))} /><Metric label="Aditivos e ajustes" value={BRL.format(Number(contract.currentValue) - Number(contract.originalValue))} /><Metric label="Valor atual calculado" value={BRL.format(Number(contract.currentValue))} /><Metric label="Fim da vigência" value={formatDate(contract.endDate)} /></div> : null}
  {tab === 'amendments' ? <><EventTable rows={contract.amendments ?? []} columns={['number', 'type', 'description', 'endDateAfter', 'valueChange']} /><form className="form-grid" onSubmit={submitEvent}><F c="col-2" l="Número *"><input className="input" required value={form.number} onChange={(e) => setForm({ ...form, number: e.target.value })} /></F><F c="col-3" l="Tipo"><select className="select" value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })}><option value="TERM_EXTENSION">Prorrogação de prazo</option><option value="VALUE_INCREASE">Acréscimo</option><option value="VALUE_DECREASE">Supressão</option><option value="SCOPE_CHANGE">Alteração de escopo</option><option value="OTHER">Outro</option></select></F><F c="col-3" l="Assinatura"><input className="input" type="date" value={form.signedAt} onChange={(e) => setForm({ ...form, signedAt: e.target.value })} /></F><F c="col-2" l="Nova vigência final"><input className="input" type="date" value={form.endDateAfter} onChange={(e) => setForm({ ...form, endDateAfter: e.target.value })} /></F><F c="col-2" l="Impacto (R$)"><input className="input" type="number" step="0.01" value={form.valueChange} onChange={(e) => setForm({ ...form, valueChange: e.target.value })} /></F><F c="col-10" l="Descrição *"><input className="input" required value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></F><Submit saving={saving} /></form></> : null}
  {tab === 'adjustments' ? <><EventTable rows={contract.adjustments ?? []} columns={['type', 'referencePeriod', 'approvalDate', 'percentage', 'amount']} /><form className="form-grid" onSubmit={submitEvent}><F c="col-3" l="Tipo"><select className="select" value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })}><option value="PRICE_ADJUSTMENT">Reajuste</option><option value="REPACTUATION">Repactuação</option><option value="ECONOMIC_REBALANCING">Reequilíbrio econômico</option></select></F><F c="col-2" l="Período de referência *"><input className="input" required value={form.referencePeriod} onChange={(e) => setForm({ ...form, referencePeriod: e.target.value })} /></F><F c="col-2" l="Aprovação *"><input className="input" required type="date" value={form.approvalDate} onChange={(e) => setForm({ ...form, approvalDate: e.target.value })} /></F><F c="col-2" l="Percentual"><input className="input" type="number" step="0.000001" value={form.percentage} onChange={(e) => setForm({ ...form, percentage: e.target.value })} /></F><F c="col-3" l="Impacto (R$) *"><input className="input" required type="number" step="0.01" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} /></F><F c="col-10" l="Índice"><input className="input" value={form.indexName} onChange={(e) => setForm({ ...form, indexName: e.target.value })} /></F><Submit saving={saving} /></form></> : null}
  {tab === 'subcontracts' ? <><EventTable rows={contract.subcontractors ?? []} columns={['subcontractorName', 'subcontractorTaxId', 'scope', 'authorizationCase', 'amount']} /><form className="form-grid" onSubmit={submitEvent}><F c="col-4" l="Empresa cadastrada"><select className="select" value={form.supplierId} onChange={(e) => setForm({ ...form, supplierId: e.target.value })}><option value="">Outra empresa</option>{suppliers.map((item) => <option key={item.id} value={item.id}>{item.tradeName || item.legalName}</option>)}</select></F><F c="col-4" l="Nome da subcontratada *"><input className="input" required={!form.supplierId} disabled={Boolean(form.supplierId)} value={form.subcontractorName} onChange={(e) => setForm({ ...form, subcontractorName: e.target.value })} /></F><F c="col-4" l="CNPJ"><input className="input" disabled={Boolean(form.supplierId)} value={form.subcontractorTaxId} onChange={(e) => setForm({ ...form, subcontractorTaxId: e.target.value })} /></F><F c="col-3" l="Autorização/processo *"><input className="input" required value={form.authorizationCase} onChange={(e) => setForm({ ...form, authorizationCase: e.target.value })} /></F><F c="col-3" l="Data da autorização *"><input className="input" required type="date" value={form.approvedAt} onChange={(e) => setForm({ ...form, approvedAt: e.target.value })} /></F><F c="col-2" l="Valor"><input className="input" type="number" step="0.01" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} /></F><F c="col-4" l="Escopo *"><input className="input" required value={form.scope} onChange={(e) => setForm({ ...form, scope: e.target.value })} /></F><Submit saving={saving} /></form></> : null}
  {tab === 'penalties' ? <><EventTable rows={contract.penalties ?? []} columns={['appliedAt', 'type', 'administrativeCase', 'description', 'amount']} /><form className="form-grid" onSubmit={submitEvent}><F c="col-3" l="Tipo"><select className="select" value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })}><option value="WARNING">Advertência</option><option value="FINE">Multa</option><option value="TEMPORARY_SUSPENSION">Suspensão</option><option value="DEBARMENT">Impedimento</option><option value="OTHER">Outra</option></select></F><F c="col-3" l="Data *"><input className="input" required type="date" value={form.appliedAt} onChange={(e) => setForm({ ...form, appliedAt: e.target.value })} /></F><F c="col-3" l="Processo"><input className="input" value={form.administrativeCase} onChange={(e) => setForm({ ...form, administrativeCase: e.target.value })} /></F><F c="col-3" l="Valor"><input className="input" type="number" step="0.01" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} /></F><F c="col-10" l="Descrição *"><input className="input" required value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></F><Submit saving={saving} /></form></> : null}
  {tab === 'work-orders' ? <EventTable rows={(contract.workOrders ?? []).map((item) => item.workOrder)} columns={['number', 'title', 'status']} /> : null}
  {tab === 'commitments' ? <><EventTable rows={contract.commitments ?? []} columns={['number', 'issueDate', 'originalAmount', 'currentAmount', 'committedBalance']} /><p className="muted">Novos empenhos e movimentos são registrados no menu Empenhos e permanecem vinculados a este contrato.</p></> : null}
  </section></section>;
}

function EventTable({ rows, columns }: { rows: Array<Record<string, unknown>>; columns: string[] }) { return rows.length ? <div className="table-wrapper" style={{ marginBottom: 18 }}><table className="data-table"><thead><tr>{columns.map((column) => <th key={column}>{column}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={String(row.id ?? index)}>{columns.map((column) => <td key={column}>{formatCell(row[column])}</td>)}</tr>)}</tbody></table></div> : <p className="muted" style={{ marginBottom: 18 }}>Nenhum registro nesta seção.</p>; }
function formatCell(value: unknown) { if (value === null || value === undefined || value === '') return '—'; if (typeof value === 'object') return '—'; const text = String(value); if (/^\d{4}-\d{2}-\d{2}T/.test(text)) return formatDate(text); return text; }
function Metric({ label, value }: { label: string; value: string }) { return <article className="kpi-card"><span className="kpi-label">{label}</span><strong className="kpi-value" style={{ fontSize: '1.2rem' }}>{value}</strong></article>; }
function Submit({ saving }: { saving: boolean }) { return <div className="field col-2" style={{ justifyContent: 'end' }}><button className="btn btn-primary" disabled={saving}><Save size={16} /> Registrar</button></div>; }
function F({ c, l, children }: { c: string; l: string; children: React.ReactNode }) { return <div className={`field ${c}`}><label>{l}</label>{children}</div>; }
