'use client';

import { HandCoins, Pencil, Plus, RefreshCw, Trash2, X } from 'lucide-react';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { EmptyState } from '@/components/empty-state';
import { LoadingPanel } from '@/components/loading';
import { apiFetch, ApiError } from '@/lib/api';
import { BRL, formatDate } from '@/lib/format';
import type { Contract } from '@/lib/types';

type Movement = { id: string; type: string; amount: string; occurredAt: string };
type Commitment = { id: string; number: string; fiscalYear: number; issueDate: string; originalValue: string;
  notes?: string | null; contract: { id: string; code: string; object: string }; movements: Movement[] };
const EMPTY = { contractId: '', number: '', fiscalYear: String(new Date().getFullYear()), issueDate: new Date().toISOString().slice(0,10), originalValue: '', notes: '' };

export default function CommitmentsPage() {
  const [items, setItems] = useState<Commitment[]>([]); const [contracts, setContracts] = useState<Contract[]>([]);
  const [form, setForm] = useState(EMPTY); const [movement, setMovement] = useState({ commitmentId: '', type: 'REINFORCEMENT', amount: '', occurredAt: new Date().toISOString().slice(0,10), documentRef: '' });
  const [editingId, setEditingId] = useState<string | null>(null);
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const load = useCallback(() => Promise.all([apiFetch<Commitment[]>('/finance/commitments'), apiFetch<Contract[]>('/contracts')])
    .then(([rows, contracts]) => { setItems(rows); setContracts(contracts); setForm((v) => ({ ...v, contractId: v.contractId || contracts[0]?.id || '' })); })
    .catch((e: Error) => setError(e.message)).finally(() => setLoading(false)), []);
  useEffect(() => { void load(); }, [load]);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { await apiFetch(editingId ? `/finance/commitments/${editingId}` : '/finance/commitments', { method: editingId ? 'PATCH' : 'POST', body: JSON.stringify({ ...form, fiscalYear: Number(form.fiscalYear), originalValue: Number(form.originalValue), issueDate: `${form.issueDate}T12:00:00.000Z`, notes: form.notes || undefined }) }); setForm({ ...EMPTY, contractId: form.contractId }); setEditingId(null); setLoading(true); await load(); } catch (e) { setError(e instanceof ApiError ? e.message : 'Falha ao salvar empenho.'); } finally { setBusy(false); } }
  async function addMovement(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { await apiFetch(`/finance/commitments/${movement.commitmentId}/movements`, { method: 'POST', body: JSON.stringify({ type: movement.type, amount: Number(movement.amount), occurredAt: `${movement.occurredAt}T12:00:00.000Z`, documentRef: movement.documentRef || undefined }) }); setMovement({ ...movement, amount: '', documentRef: '' }); setLoading(true); await load(); } catch (e) { setError(e instanceof ApiError ? e.message : 'Falha ao movimentar empenho.'); } finally { setBusy(false); } }
  function edit(item: Commitment) { setEditingId(item.id); setForm({ contractId: item.contract.id, number: item.number,
    fiscalYear: String(item.fiscalYear), issueDate: item.issueDate.slice(0,10), originalValue: String(item.originalValue), notes: item.notes ?? '' }); window.scrollTo({top:0,behavior:'smooth'}); }
  async function archive(item: Commitment) { if(!window.confirm(`Excluir o empenho ${item.number}/${item.fiscalYear}? O saldo disponível será anulado e o razão ficará preservado.`))return; setBusy(true);setError('');try{await apiFetch(`/finance/commitments/${item.id}`,{method:'DELETE'});await load();}catch(e){setError(e instanceof ApiError?e.message:'Falha ao excluir empenho.')}finally{setBusy(false)} }
  return <div className="page-container"><header className="page-header"><div className="page-title"><h1>Empenhos</h1><p>Reserva, reforço, anulação, liquidação e pagamento conciliados por contrato.</p></div><button className="btn btn-secondary" onClick={() => { setLoading(true); void load(); }}><RefreshCw size={16}/>Atualizar</button></header>
    {error ? <div className="notice error" style={{marginBottom:18}}>{error}</div> : null}
    <div className="grid grid-2" style={{marginBottom:18}}><form className="card form-card" onSubmit={submit}><div className="card-header"><div><h2>{editingId?'Editar empenho':'Novo empenho'}</h2><p>A emissão inicial é registrada automaticamente no razão.</p></div>{editingId?<button className="btn btn-ghost" type="button" onClick={()=>{setEditingId(null);setForm({...EMPTY,contractId:contracts[0]?.id||''})}}><X size={17}/>Cancelar edição</button>:<Plus size={19}/>}</div><div className="card-body"><div className="form-grid"><F c="col-7" l="Contrato"><select className="select" required value={form.contractId} onChange={e=>setForm({...form,contractId:e.target.value})}>{contracts.map(c=><option key={c.id} value={c.id}>{c.code} — {c.object}</option>)}</select></F><F c="col-5" l="Número"><input className="input" required value={form.number} onChange={e=>setForm({...form,number:e.target.value})}/></F><F c="col-4" l="Exercício"><input className="input" type="number" min="2000" required value={form.fiscalYear} onChange={e=>setForm({...form,fiscalYear:e.target.value})}/></F><F c="col-4" l="Emissão"><input className="input" type="date" required value={form.issueDate} onChange={e=>setForm({...form,issueDate:e.target.value})}/></F><F c="col-4" l="Valor"><input className="input" type="number" min="0.01" step="0.01" required value={form.originalValue} onChange={e=>setForm({...form,originalValue:e.target.value})}/></F><F c="col-12" l="Observações"><input className="input" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></F></div><div className="actions" style={{marginTop:16}}><button className="btn btn-primary" disabled={busy}>{editingId?'Salvar alterações':'Emitir empenho'}</button></div></div></form>
    <form className="card form-card" onSubmit={addMovement}><div className="card-header"><div><h2>Movimentar razão</h2><p>Os limites de saldo são conferidos pela API.</p></div><HandCoins size={19}/></div><div className="card-body"><div className="form-grid"><F c="col-12" l="Empenho"><select className="select" required value={movement.commitmentId} onChange={e=>setMovement({...movement,commitmentId:e.target.value})}><option value="">Selecione</option>{items.map(i=><option key={i.id} value={i.id}>{i.number}/{i.fiscalYear}</option>)}</select></F><F c="col-5" l="Movimento"><select className="select" value={movement.type} onChange={e=>setMovement({...movement,type:e.target.value})}><option value="REINFORCEMENT">Reforço</option><option value="CANCELLATION">Anulação</option></select></F><F c="col-3" l="Valor"><input className="input" type="number" min="0.01" step="0.01" required value={movement.amount} onChange={e=>setMovement({...movement,amount:e.target.value})}/></F><F c="col-4" l="Data"><input className="input" type="date" required value={movement.occurredAt} onChange={e=>setMovement({...movement,occurredAt:e.target.value})}/></F></div><div className="actions" style={{marginTop:16}}><button className="btn btn-primary" disabled={busy || !movement.commitmentId}>Registrar movimento</button></div></div></form></div>
    {loading ? <LoadingPanel/> : <section className="card table-card">{items.length ? <div className="table-wrapper"><table className="data-table"><thead><tr><th>Empenho</th><th>Contrato</th><th>Emissão</th><th>Empenhado</th><th>Liquidado</th><th>Pago</th><th>Disponível</th><th>Ações</th></tr></thead><tbody>{items.map(item=>{const sum=(types:string[])=>item.movements.filter(m=>types.includes(m.type)).reduce((a,m)=>a+Number(m.amount),0); const issued=sum(['ISSUE','REINFORCEMENT']); const canceled=sum(['CANCELLATION']); const liquidated=sum(['LIQUIDATION']); const paid=sum(['PAYMENT']); return <tr key={item.id}><td><span className="table-primary">{item.number}/{item.fiscalYear}</span><span className="table-secondary">{item.movements.length} movimento(s)</span></td><td>{item.contract.code}</td><td>{formatDate(item.issueDate)}</td><td>{BRL.format(issued-canceled)}</td><td>{BRL.format(liquidated)}</td><td>{BRL.format(paid)}</td><td><span className="badge success">{BRL.format(issued-canceled-liquidated)}</span></td><td><div className="table-actions"><button className="btn btn-ghost" type="button" disabled={item.movements.length!==1} title={item.movements.length!==1?'Empenhos movimentados são alterados por reforço/anulação.':''} onClick={()=>edit(item)}><Pencil size={14}/>Editar</button><button className="btn btn-ghost danger-text" type="button" onClick={()=>void archive(item)}><Trash2 size={14}/>Excluir</button></div></td></tr>})}</tbody></table></div> : <EmptyState icon={HandCoins} title="Nenhum empenho" description="Emita o primeiro empenho para iniciar o controle financeiro."/>}</section>}
  </div>;
}
function F({c,l,children}:{c:string;l:string;children:React.ReactNode}){return <div className={`field ${c}`}><label>{l}</label>{children}</div>}
