import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const apiAssets=path.resolve(root,'../api/src/modules/infraestrutura/assets');
const manifest=JSON.parse(await fs.readFile(path.join(root,'extraction-manifest.json'),'utf8'));
const sources=[];
for(const item of manifest.modules)sources.push({name:item.file,code:await fs.readFile(path.join(root,'src/modules',item.file),'utf8')});
const alSeed=JSON.parse(await fs.readFile(path.join(root,'public/data/administracao-local-seed.json'),'utf8'));
const mobilizationSeed=JSON.parse(await fs.readFile(path.join(root,'public/data/mobilizacao-seed.json'),'utf8'));
const template=await fs.readFile(path.join(root,'scripts/runtime-template.cjs'),'utf8');
await fs.mkdir(apiAssets,{recursive:true});
const header=`/* Generated from the approved OrçaPro Infraestrutura modules; do not edit formulas here. */\nconst SOURCE_SHA256=${JSON.stringify(manifest.sourceSha256)};\nconst MODULES=${JSON.stringify(sources)};\nconst DATA=${JSON.stringify({alSeed,mobilizationSeed})};\n`;
await fs.writeFile(path.join(apiAssets,'legacy-runtime.cjs'),header+template);
console.log('Infraestrutura legacy-runtime.cjs generated.');
