'use client';

import Link from 'next/link';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { KeyRound, ShieldCheck, Users, CreditCard, ClipboardList, Calculator, Plus, Search, UserPlus, X } from 'lucide-react';
import { apiFetch, apiFileUrl, ApiError } from '@/lib/api';
import { endSession } from '@/lib/end-session';
import { ORCAPRO_ONLY } from '@/lib/product-config';
import styles from '../workspace.module.css';
import css from './saas.module.css';

type Plan = { id: string; code: string; name: string; billingInterval: 'MONTH' | 'YEAR'; priceBrl: string; stripePriceId: string | null; active: boolean; version: number };
type Subscription = { id: string; planId: string | null; status: string; billingSource: string; currentPeriodEnd: string | null; stripeSubscriptionId: string | null; stripeStatus: string | null; stripePeriodEnd: string | null; cancelAtPeriodEnd: boolean; version: number; plan: Plan | null };
type User = { id: string; name: string; email: string; protected: boolean; accessAllowed: boolean; status: string; orcaproAccess: { enabled: boolean; managed: boolean; deletedAt: string | null } | null; orcaproSubscription: Subscription | null; memberships: { status: string; maintenanceAccess: boolean; tenant: { name: string; slug: string } }[] };
type Log = { id: string; action: string; entityId: string | null; actorUserId: string; createdAt: string; metadata?: { reason?: string; status?: string } };
type Integration = { keyConfigured: boolean; webhookConfigured: boolean; webhookPath: string };
const labels: Record<string, string> = { ACTIVE: 'Ativa', TRIALING: 'Em teste', MANUAL_CONTRACT: 'Contrato manual', PAST_DUE: 'Inadimplente', UNPAID: 'Não paga', CANCELED: 'Cancelada' };
const actions: Record<string, string> = { 'saas.user.create': 'Cadastro de usuário', 'saas.user.password': 'Alteração de senha', 'saas.user.status': 'Alteração de acesso', 'saas.user.revoke': 'Revogação de sessões', 'saas.plan.save': 'Cadastro de plano', 'saas.subscription.manual': 'Controle manual de assinatura', 'saas.subscription.stripe': 'Gestão de assinatura Stripe', 'saas.subscription.webhook': 'Atualização automática Stripe' };
const text = (cause: unknown) => cause instanceof Error ? cause.message : 'Não foi possível concluir a operação.';
const date = (value: string | null) => value ? new Date(value).toLocaleDateString('pt-BR', { timeZone: 'America/Sao_Paulo' }) : 'Sem vencimento';
const dateInput = (value: string) => new Date(value).toLocaleDateString('en-CA', { timeZone: 'America/Sao_Paulo', year: 'numeric', month: '2-digit', day: '2-digit' });
const amount = (value: string) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(Number(value));
const emptyPlan = { code: '', name: '', billingInterval: 'MONTH' as 'MONTH' | 'YEAR', priceBrl: '0.00', stripePriceId: '', active: true };

export default function SaasAdministrationPage() {
  const [tab, setTab] = useState<'users' | 'plans' | 'audit'>('users');
  const [users, setUsers] = useState<User[]>([]); const [total, setTotal] = useState(0);
  const [plans, setPlans] = useState<Plan[]>([]); const [logs, setLogs] = useState<{ items: Log[]; total: number }>({ items: [], total: 0 });
  const [integration, setIntegration] = useState<Integration | null>(null);
  const [access, setAccess] = useState(false); const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const [search, setSearch] = useState(''); const [filter, setFilter] = useState(''); const [deleted, setDeleted] = useState(false); const [page, setPage] = useState(1); const [logPage, setLogPage] = useState(1);
  const [createOpen, setCreateOpen] = useState(false); const [newUser, setNewUser] = useState({ name: '', email: '', password: '', organizationName: '', organizationSlug: '' });
  const [passwordUser, setPasswordUser] = useState<User | null>(null); const [password, setPassword] = useState('');
  const [confirm, setConfirm] = useState<{ user: User; status: 'ACTIVE' | 'SUSPENDED' | 'DELETED' } | null>(null);
  const [subscriptionUser, setSubscriptionUser] = useState<User | null>(null); const [subscription, setSubscription] = useState({ planId: '', status: 'ACTIVE', currentPeriodEnd: '', reason: '' });
  const [editPlan, setEditPlan] = useState<Plan | null>(null); const [planOpen, setPlanOpen] = useState(false); const [planForm, setPlanForm] = useState(emptyPlan);
  const [stripeConfirm, setStripeConfirm] = useState<{ user: User; action: 'SYNC' | 'CANCEL_AT_PERIOD_END' | 'RESUME' } | null>(null);

  const load = useCallback(async () => {
    const query = new URLSearchParams({ search: filter, deleted: String(deleted), page: String(page), pageSize: '20' });
    const [people, catalog, stripe, history] = await Promise.all([
      apiFetch<{ items: User[]; total: number }>(`/orcapro/admin/saas/users?${query}`), apiFetch<Plan[]>('/orcapro/admin/saas/plans'),
      apiFetch<Integration>('/orcapro/admin/saas/stripe'), apiFetch<{ items: Log[]; total: number }>(`/orcapro/admin/logs?page=${logPage}&pageSize=20`),
    ]);
    setUsers(people.items); setTotal(people.total); setPlans(catalog); setIntegration(stripe); setLogs(history); setAccess(true);
  }, [filter, deleted, page, logPage]);
  useEffect(() => { let active = true;
    Promise.resolve().then(() => { if (active) return load(); }).catch(cause => { if (!active) return; if (cause instanceof ApiError && cause.status === 401) { window.location.replace('/login?next=/orcapro'); return; } setError(text(cause)); }).finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [load]);
  async function mutate(operation: () => Promise<unknown>, message: string, close?: () => void) {
    if (busy) return; setBusy(true); setError(''); setNotice('');
    try { await operation(); close?.(); setNotice(message); await load(); } catch (cause) { setError(text(cause)); } finally { setBusy(false); }
  }
  function openSubscription(user: User) {
    const s = user.orcaproSubscription;
    setSubscriptionUser(user); setSubscription({ planId: s?.planId ?? '', status: s?.status ?? 'ACTIVE', currentPeriodEnd: s?.currentPeriodEnd ? dateInput(s.currentPeriodEnd) : '', reason: '' });
  }
  async function create(event: FormEvent) { event.preventDefault(); await mutate(() => apiFetch('/orcapro/admin/saas/users', { method: 'POST', body: JSON.stringify({ name: newUser.name, email: newUser.email, password: newUser.password, organizationName: newUser.organizationName || undefined, organizationSlug: newUser.organizationSlug || undefined }) }), 'Usuário cadastrado com teste de 30 dias e acesso somente ao OrçaPro.', () => { setCreateOpen(false); setNewUser({ name: '', email: '', password: '', organizationName: '', organizationSlug: '' }); }); }
  async function savePassword(event: FormEvent) { event.preventDefault(); if (!passwordUser) return;
    await mutate(() => apiFetch(`/orcapro/admin/saas/users/${passwordUser.id}/password`, { method: 'POST', body: JSON.stringify({ newPassword: password }) }), 'Senha compartilhada alterada e sessões anteriores encerradas.', () => { setPasswordUser(null); setPassword(''); }); }
  async function saveSubscription(event: FormEvent) { event.preventDefault(); if (!subscriptionUser) return;
    await mutate(() => apiFetch(`/orcapro/admin/saas/users/${subscriptionUser.id}/subscription`, { method: 'PUT', body: JSON.stringify({ ...subscription, planId: subscription.planId || undefined, currentPeriodEnd: subscription.currentPeriodEnd ? `${subscription.currentPeriodEnd}T23:59:59-03:00` : undefined, expectedVersion: subscriptionUser.orcaproSubscription?.version }) }), 'Controle manual de acesso atualizado.', () => setSubscriptionUser(null)); }
  async function savePlan(event: FormEvent) { event.preventDefault(); await mutate(() => apiFetch(`/orcapro/admin/saas/plans${editPlan ? `/${editPlan.id}` : ''}`, { method: editPlan ? 'PUT' : 'POST', body: JSON.stringify({ ...planForm, priceBrl: planForm.priceBrl.replace(',', '.'), stripePriceId: planForm.stripePriceId || undefined, expectedVersion: editPlan?.version }) }), 'Plano salvo.', () => { setPlanOpen(false); setEditPlan(null); setPlanForm(emptyPlan); }); }
  async function logout() { if (busy) return; setBusy(true); setError(''); try { await endSession('/login?next=/orcapro'); } catch { setError('Não foi possível encerrar a sessão. Tente novamente.'); setBusy(false); } }

  if (loading) return <main className={styles.loading} aria-busy="true">Carregando gestão do SaaS…</main>;
  if (!access) return <main className={styles.loading}><h1>Gestão do SaaS</h1><p role="alert">{error}</p><Link href="/orcapro">Voltar ao OrçaPro</Link></main>;
  return <div className={styles.workspace}>
    <aside className={styles.sidebar}><Link href="/orcapro" className={styles.brand}><span><Calculator size={24} /></span><strong>OrçaPro<small>Administração do SaaS</small></strong></Link>
      <nav aria-label="Gestão do SaaS"><button className={tab === 'users' ? styles.active : ''} onClick={() => setTab('users')}><Users size={18} /> Usuários e assinaturas</button><button className={tab === 'plans' ? styles.active : ''} onClick={() => setTab('plans')}><CreditCard size={18} /> Planos e Stripe</button><button className={tab === 'audit' ? styles.active : ''} onClick={() => setTab('audit')}><ClipboardList size={18} /> Auditoria</button></nav>
      <footer><span className={styles.badge}>Administrador global</span><Link href="/orcapro">Voltar ao editor</Link><Link href="/orcapro/gerenciar">Meus orçamentos e SINAPI</Link>{!ORCAPRO_ONLY ? <Link href="/programas">Trocar programa</Link> : null}<button disabled={busy} onClick={() => void logout()}>Sair</button></footer>
    </aside>
    <main className={styles.main}><header className={styles.topbar}><h1>Gestão do SaaS</h1><ShieldCheck size={22} /></header><div className={`${styles.content} ${css.content}`}>
      {error ? <p className={styles.error} role="alert">{error}</p> : null}{notice ? <p className={styles.notice} role="status">{notice}</p> : null}
      <section className={css.summary}><article><small>Contas nesta consulta</small><strong>{total}</strong></article><article><small>Planos ativos</small><strong>{plans.filter(p => p.active).length}</strong></article><article><small>Cobrança</small><strong>Por usuário</strong></article><article><small>Integração Stripe</small><strong>{integration?.keyConfigured && integration?.webhookConfigured ? 'Configurada' : 'Configuração pendente'}</strong></article></section>
      {tab === 'users' ? <>
        <section className={styles.panel}><div className={css.sectionHeader}><div><h2>Usuários e assinaturas</h2><p className={styles.muted}>Assinaturas individuais do OrçaPro. A contratação do Gestão de Prédios é independente.</p></div><button disabled={busy} onClick={() => setCreateOpen(!createOpen)}><UserPlus size={16} /> Cadastrar usuário</button></div>
          <form className={css.filters} onSubmit={e => { e.preventDefault(); setPage(1); setFilter(search); }}><label htmlFor="saas-search">Buscar nome ou e-mail<input id="saas-search" value={search} onChange={e => setSearch(e.target.value)} /></label><button><Search size={15} /> Buscar</button><label><input type="checkbox" checked={deleted} onChange={e => { setDeleted(e.target.checked); setPage(1); }} /> Mostrar excluídos</label></form>
        </section>
        {createOpen ? <form className={styles.panel} onSubmit={create}><h2>Cadastrar usuário</h2><p className={styles.muted}>A nova conta recebe 30 dias de teste. Preencha uma nova organização ou deixe ambos os campos em branco para usar sua organização atual.</p><div className={css.grid}>
          <label>Nome<input required minLength={2} maxLength={160} value={newUser.name} onChange={e => setNewUser({ ...newUser, name: e.target.value })} /></label><label>E-mail<input required type="email" value={newUser.email} onChange={e => setNewUser({ ...newUser, email: e.target.value })} /></label><label>Senha inicial<input required type="password" autoComplete="new-password" minLength={10} maxLength={72} value={newUser.password} onChange={e => setNewUser({ ...newUser, password: e.target.value })} /><small>De 10 a 72 caracteres.</small></label><label>Nome da nova organização<input value={newUser.organizationName} onChange={e => setNewUser({ ...newUser, organizationName: e.target.value })} /></label><label>Identificador da nova organização<input pattern="[a-z0-9][a-z0-9-]{2,99}" value={newUser.organizationSlug} onChange={e => setNewUser({ ...newUser, organizationSlug: e.target.value })} /><small>Usado no login. Letras minúsculas, números e hífen.</small></label></div><div className={styles.actions}><button disabled={busy}><UserPlus size={16} /> Criar usuário</button><button type="button" disabled={busy} onClick={() => { setCreateOpen(false); setNewUser({ name: '', email: '', password: '', organizationName: '', organizationSlug: '' }); }}>Cancelar</button></div></form> : null}
        <section className={styles.panel}><div className={styles.tablewrap}><table><thead><tr><th>Usuário</th><th>Organização / login</th><th>Acesso OrçaPro</th><th>Assinatura</th><th>Validade</th><th>Ações</th></tr></thead><tbody>{users.map(user => <tr key={user.id}><td><strong>{user.name}</strong><small className={css.secondary}>{user.email}</small></td><td>{user.memberships.map(m => <span key={m.tenant.slug} className={css.secondary}>{m.tenant.name} · {m.tenant.slug}</span>)}</td><td><span className={user.accessAllowed ? css.activeBadge : css.inactiveBadge}>{user.protected ? 'Administrador' : user.orcaproAccess?.deletedAt ? 'Excluído' : user.accessAllowed ? 'Ativo' : 'Bloqueado'}</span></td><td>{user.orcaproSubscription ? <>{user.orcaproSubscription.plan?.name ?? 'Plano não definido'}<small className={css.secondary}>{labels[user.orcaproSubscription.status]} · {user.orcaproSubscription.billingSource === 'STRIPE' ? 'Stripe' : 'Manual'}</small></> : 'Acesso existente'}</td><td>{date(user.orcaproSubscription?.currentPeriodEnd ?? null)}</td><td><div className={css.rowActions}>
          {!user.protected ? <><button disabled={busy} onClick={() => openSubscription(user)}>Assinatura</button><button disabled={busy} onClick={() => { setPasswordUser(user); setPassword(''); }}><KeyRound size={14} /> Senha</button><button disabled={busy} onClick={() => setConfirm({ user, status: user.orcaproAccess?.enabled === false || user.orcaproAccess?.deletedAt ? 'ACTIVE' : 'SUSPENDED' })}>{user.orcaproAccess?.deletedAt ? 'Restaurar' : user.orcaproAccess?.enabled === false ? 'Reativar' : 'Suspender'}</button><button disabled={busy || !!user.orcaproAccess?.deletedAt} onClick={() => setConfirm({ user, status: 'DELETED' })}>Excluir</button><button disabled={busy} onClick={() => mutate(() => apiFetch(`/orcapro/admin/saas/users/${user.id}/revoke-sessions`, { method: 'POST' }), 'Sessões encerradas.')}>Encerrar sessões</button></> : <span className={styles.muted}>Conta protegida</span>}
          {user.orcaproSubscription?.stripeSubscriptionId && !user.protected ? <><button disabled={busy} onClick={() => setStripeConfirm({ user, action: 'SYNC' })}>Usar Stripe</button><button disabled={busy} onClick={() => setStripeConfirm({ user, action: user.orcaproSubscription!.cancelAtPeriodEnd ? 'RESUME' : 'CANCEL_AT_PERIOD_END' })}>{user.orcaproSubscription.cancelAtPeriodEnd ? 'Manter renovação' : 'Cancelar renovação'}</button></> : null}
        </div></td></tr>)}</tbody></table></div>{!users.length ? <p>Nenhum usuário encontrado.</p> : null}<div className={styles.pager}><button disabled={page === 1 || busy} onClick={() => setPage(p => p - 1)}>Anterior</button><span>Página {page} · {total} contas</span><button disabled={page * 20 >= total || busy} onClick={() => setPage(p => p + 1)}>Próxima</button></div></section>
      </> : null}
      {tab === 'plans' ? <>
        <section className={styles.panel}><div className={css.sectionHeader}><div><h2>Planos do OrçaPro</h2><p className={styles.muted}>Valores e periodicidade por usuário. Desativar um plano impede novas contratações.</p></div><button onClick={() => { setEditPlan(null); setPlanForm(emptyPlan); setPlanOpen(true); }}><Plus size={16} /> Novo plano</button></div><div className={styles.tablewrap}><table><thead><tr><th>Plano</th><th>Preço por usuário</th><th>Stripe</th><th>Situação</th><th /></tr></thead><tbody>{plans.map(plan => <tr key={plan.id}><td>{plan.name}<small className={css.secondary}>{plan.code}</small></td><td>{amount(plan.priceBrl)} / {plan.billingInterval === 'MONTH' ? 'mês' : 'ano'}</td><td>{plan.stripePriceId ? 'Preço vinculado' : 'Manual'}</td><td>{plan.active ? 'Ativo' : 'Inativo'}</td><td><button onClick={() => { setEditPlan(plan); setPlanForm({ code: plan.code, name: plan.name, billingInterval: plan.billingInterval, priceBrl: plan.priceBrl, stripePriceId: plan.stripePriceId ?? '', active: plan.active }); setPlanOpen(true); }}>Editar</button></td></tr>)}</tbody></table></div>{!plans.length ? <p>Cadastre o primeiro plano. Nenhum valor de cobrança foi definido automaticamente.</p> : null}</section>
        {planOpen ? <form className={styles.panel} onSubmit={savePlan}><h2>{editPlan ? 'Editar plano' : 'Novo plano'}</h2><div className={css.grid}><label>Código<input required pattern="[A-Z0-9][A-Z0-9_-]{1,49}" value={planForm.code} onChange={e => setPlanForm({ ...planForm, code: e.target.value.toUpperCase() })} /></label><label>Nome<input required minLength={2} value={planForm.name} onChange={e => setPlanForm({ ...planForm, name: e.target.value })} /></label><label>Valor em R$<input required inputMode="decimal" value={planForm.priceBrl} onChange={e => setPlanForm({ ...planForm, priceBrl: e.target.value })} /></label><label>Periodicidade<select value={planForm.billingInterval} onChange={e => setPlanForm({ ...planForm, billingInterval: e.target.value as 'MONTH' | 'YEAR' })}><option value="MONTH">Mensal</option><option value="YEAR">Anual</option></select></label><label>Identificador do preço Stripe<input placeholder="price_… (opcional)" value={planForm.stripePriceId} onChange={e => setPlanForm({ ...planForm, stripePriceId: e.target.value })} /></label><label><input type="checkbox" checked={planForm.active} onChange={e => setPlanForm({ ...planForm, active: e.target.checked })} /> Plano ativo</label></div><div className={styles.actions}><button disabled={busy}>Salvar plano</button><button type="button" disabled={busy} onClick={() => setPlanOpen(false)}>Cancelar</button></div></form> : null}
        <section className={styles.panel}><h2>Integração Stripe</h2><p>Chave da API: {integration?.keyConfigured ? 'configurada' : 'pendente'}. Webhook: {integration?.webhookConfigured ? 'configurado' : 'pendente'}.</p><p>As credenciais são configuradas no ambiente seguro da hospedagem. Cadastre os preços dos planos no Stripe e vincule seus identificadores acima.</p><p>Endereço do webhook: <code>{new URL(apiFileUrl('/')).origin}{integration?.webhookPath}</code></p><p className={styles.muted}>O controle manual altera o acesso ao OrçaPro. Para interromper uma cobrança Stripe, use “Cancelar renovação” na assinatura.</p></section>
      </> : null}
      {tab === 'audit' ? <section className={styles.panel}><h2>Auditoria do OrçaPro</h2><div className={styles.tablewrap}><table><thead><tr><th>Quando</th><th>Ação</th><th>Registro</th><th>Responsável</th></tr></thead><tbody>{logs.items.map(log => <tr key={log.id}><td>{new Date(log.createdAt).toLocaleString('pt-BR', { timeZone: 'America/Sao_Paulo' })}</td><td>{actions[log.action] ?? log.action}{log.metadata?.reason ? <small className={css.secondary}>{log.metadata.reason}</small> : null}{log.metadata?.status ? <small className={css.secondary}>{labels[log.metadata.status] ?? log.metadata.status}</small> : null}</td><td>{log.entityId ?? '—'}</td><td>{users.find(u => u.id === log.actorUserId)?.name ?? log.actorUserId}</td></tr>)}</tbody></table></div><div className={styles.pager}><button disabled={logPage === 1} onClick={() => setLogPage(p => p - 1)}>Anterior</button><span>Página {logPage}</span><button disabled={logPage * 20 >= logs.total} onClick={() => setLogPage(p => p + 1)}>Próxima</button></div></section> : null}
    </div></main>
    {passwordUser ? <div className={styles.overlay}><form className={styles.drawer} role="dialog" aria-modal="true" aria-label="Alterar senha" onSubmit={savePassword}><header><h2>Senha de {passwordUser.name}</h2><button type="button" disabled={busy} onClick={() => { setPasswordUser(null); setPassword(''); }} aria-label="Fechar alteração de senha"><X size={18} /></button></header><p>O login é compartilhado: esta senha vale para OrçaPro e Gestão de Prédios. Todas as sessões anteriores serão encerradas.</p><label className={css.field}>Nova senha<input autoFocus required type="password" autoComplete="new-password" minLength={10} maxLength={72} value={password} onChange={e => setPassword(e.target.value)} /></label><button disabled={busy}>Alterar senha e encerrar sessões</button>{error ? <p role="alert" className={styles.error}>{error}</p> : null}</form></div> : null}
    {subscriptionUser ? <div className={styles.overlay}><form className={styles.drawer} role="dialog" aria-modal="true" aria-label="Controle de assinatura" onSubmit={saveSubscription}><header><h2>Assinatura de {subscriptionUser.name}</h2><button type="button" disabled={busy} onClick={() => setSubscriptionUser(null)}>Fechar</button></header><p>Controle manual do acesso individual ao OrçaPro. Cobranças existentes no Stripe continuam até serem canceladas no Stripe.</p><div className={css.grid}><label>Plano<select value={subscription.planId} onChange={e => setSubscription({ ...subscription, planId: e.target.value })}><option value="">Sem plano definido</option>{plans.filter(p => p.active).map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Situação<select value={subscription.status} onChange={e => setSubscription({ ...subscription, status: e.target.value })}>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Válida até<input type="date" required={subscription.status === 'TRIALING'} value={subscription.currentPeriodEnd} onChange={e => setSubscription({ ...subscription, currentPeriodEnd: e.target.value })} /><small>Em branco: acesso sem vencimento, exceto teste.</small></label><label>Motivo da alteração<textarea required minLength={5} maxLength={500} value={subscription.reason} onChange={e => setSubscription({ ...subscription, reason: e.target.value })} /></label></div><button disabled={busy}>Salvar controle manual</button>{error ? <p role="alert" className={styles.error}>{error}</p> : null}</form></div> : null}
    {confirm ? <div className={styles.overlay}><section className={styles.drawer} role="dialog" aria-modal="true" aria-label="Confirmar alteração de acesso"><h2>{confirm.status === 'DELETED' ? 'Excluir usuário do OrçaPro' : confirm.status === 'ACTIVE' ? 'Reativar acesso' : 'Suspender acesso'}</h2><p>{confirm.user.name} · {confirm.user.email}</p><p>{confirm.status === 'DELETED' ? 'O acesso será removido da lista ativa. Orçamentos e histórico serão preservados, e você poderá restaurá-lo em “Mostrar excluídos”. A conta de manutenção será preservada.' : 'Esta ação altera apenas o acesso ao OrçaPro. A situação da assinatura também precisa permitir o acesso.'}</p><p className={styles.muted}>Esta ação não cancela cobranças no Stripe. Use “Cancelar renovação” para interromper a renovação da assinatura.</p><div className={styles.actions}><button disabled={busy} onClick={() => mutate(() => apiFetch(`/orcapro/admin/saas/users/${confirm.user.id}/status`, { method: 'PATCH', body: JSON.stringify({ status: confirm.status }) }), 'Acesso atualizado e sessões anteriores encerradas.', () => setConfirm(null))}>Confirmar</button><button disabled={busy} onClick={() => setConfirm(null)}>Cancelar</button></div>{error ? <p role="alert" className={styles.error}>{error}</p> : null}</section></div> : null}
    {stripeConfirm ? <div className={styles.overlay}><section className={styles.drawer} role="dialog" aria-modal="true" aria-label="Confirmar gestão Stripe"><h2>{stripeConfirm.action === 'SYNC' ? 'Usar a assinatura Stripe para controlar o acesso' : stripeConfirm.action === 'RESUME' ? 'Manter renovação automática' : 'Cancelar renovação automática'}</h2><p>{stripeConfirm.user.name}. {stripeConfirm.action === 'SYNC' ? 'A situação e validade do Stripe substituirão o controle manual.' : stripeConfirm.action === 'RESUME' ? 'A assinatura continuará renovando no Stripe.' : 'A assinatura Stripe será cancelada ao final do período pago.'}</p><div className={styles.actions}><button disabled={busy} onClick={() => mutate(() => apiFetch(`/orcapro/admin/saas/subscriptions/${stripeConfirm.user.orcaproSubscription!.id}/stripe`, { method: 'POST', body: JSON.stringify({ action: stripeConfirm.action, expectedVersion: stripeConfirm.user.orcaproSubscription!.version }) }), 'Assinatura Stripe atualizada.', () => setStripeConfirm(null))}>Confirmar</button><button disabled={busy} onClick={() => setStripeConfirm(null)}>Cancelar</button></div>{error ? <p role="alert" className={styles.error}>{error}</p> : null}</section></div> : null}
  </div>;
}
