'use client';

import { Plus, Save, UsersRound, X } from 'lucide-react';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { EmptyState } from '@/components/empty-state';
import { LoadingPanel } from '@/components/loading';
import { apiFetch, ApiError } from '@/lib/api';
import type { Supplier } from '@/lib/types';

const EMPTY = { legalName: '', tradeName: '', taxId: '', email: '', phone: '', contactName: '', serviceAreas: '', notes: '' };

export default function SuppliersPage() {
  const [items, setItems] = useState<Supplier[]>([]); const [form, setForm] = useState(EMPTY);
  const [loading, setLoading] = useState(true); const [showForm, setShowForm] = useState(false); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState('');
  const load = useCallback(() => { apiFetch<Supplier[]>('/suppliers').then(setItems).catch((e: Error) => setError(e.message)).finally(() => setLoading(false)); }, []);
  useEffect(load, [load]);
  async function submit(event: FormEvent) { event.preventDefault(); setSubmitting(true); setError(''); try { await apiFetch('/suppliers', { method: 'POST', body: JSON.stringify({ ...form, tradeName: form.tradeName || undefined, email: form.email || undefined, phone: form.phone || undefined, contactName: form.contactName || undefined, notes: form.notes || undefined, serviceAreas: form.serviceAreas.split(',').map((v) => v.trim()).filter(Boolean) }) }); setForm(EMPTY); setShowForm(false); setLoading(true); load(); } catch (cause) { setError(cause instanceof ApiError ? cause.message : 'Falha ao cadastrar fornecedor.'); } finally { setSubmitting(false); } }
  return <div className="page-container"><header className="page-header"><div className="page-title"><h1>Fornecedores</h1><p>Empresas contratadas, áreas de atuação, histórico de contratos, ordens e penalidades.</p></div><button className="btn btn-primary" type="button" onClick={() => setShowForm((v) => !v)}>{showForm ? <X size={16} /> : <Plus size={16} />}{showForm ? 'Fechar cadastro' : 'Novo fornecedor'}</button></header>{error ? <div className="notice error" style={{ marginBottom: 18 }}>{error}</div> : null}
  {showForm ? <form className="card form-card" onSubmit={submit} style={{ marginBottom: 18 }}><section className="form-section"><div className="form-section-header"><h2>Dados cadastrais</h2><p>O CNPJ/CPF é único dentro da organização.</p></div><div className="form-grid"><F c="col-8" l="Razão social *"><input className="input" required value={form.legalName} onChange={(e) => setForm({ ...form, legalName: e.target.value })} /></F><F c="col-4" l="Nome fantasia"><input className="input" value={form.tradeName} onChange={(e) => setForm({ ...form, tradeName: e.target.value })} /></F><F c="col-3" l="CNPJ/CPF *"><input className="input" required minLength={8} value={form.taxId} onChange={(e) => setForm({ ...form, taxId: e.target.value })} /></F><F c="col-3" l="Contato"><input className="input" value={form.contactName} onChange={(e) => setForm({ ...form, contactName: e.target.value })} /></F><F c="col-3" l="E-mail"><input className="input" type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></F><F c="col-3" l="Telefone"><input className="input" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /></F><F c="col-12" l="Áreas de atuação"><input className="input" placeholder="elétrica, hidráulica, civil, climatização" value={form.serviceAreas} onChange={(e) => setForm({ ...form, serviceAreas: e.target.value })} /></F><F c="col-12" l="Observações"><textarea className="textarea" value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></F></div></section><div className="form-footer"><button className="btn btn-secondary" type="button" onClick={() => setShowForm(false)}>Cancelar</button><button className="btn btn-primary" disabled={submitting}><Save size={16} /> {submitting ? 'Salvando…' : 'Salvar fornecedor'}</button></div></form> : null}
  {loading ? <LoadingPanel /> : <section className="card table-card">{items.length ? <div className="table-wrapper"><table className="data-table"><thead><tr><th>Fornecedor</th><th>CNPJ/CPF</th><th>Contato</th><th>Status</th><th>Contratos</th><th>OS</th><th>Penalidades</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><span className="table-primary">{item.tradeName || item.legalName}</span>{item.tradeName ? <span className="table-secondary">{item.legalName}</span> : null}</td><td>{item.taxId}</td><td><span className="table-primary">{item.contactName || '—'}</span><span className="table-secondary">{item.email || item.phone || 'Sem contato'}</span></td><td><span className={`badge status-${item.status}`}>{item.status.toLowerCase()}</span></td><td>{item._count?.contracts ?? 0}</td><td>{item._count?.directWorkOrders ?? 0}</td><td>{item._count?.penalties ?? 0}</td></tr>)}</tbody></table></div> : <EmptyState icon={UsersRound} title="Nenhum fornecedor cadastrado" description="Cadastre empresas para vinculá-las a contratos e ordens de serviço." />}</section>}</div>;
}
function F({ c, l, children }: { c: string; l: string; children: React.ReactNode }) { return <div className={`field ${c}`}><label>{l}</label>{children}</div>; }
