/* ==== 40_sicro_ui.js — Base de dados SICRO (importação de relatórios) e Manual ==== */
(function (G) {
  'use strict';
  const OP = G.OP, U = OP.util, UI = OP.ui, A = OP.app, S = OP.sicro, esc = U.esc;
  const pick = () => new Promise((res) => { const i = document.createElement('input'); i.type = 'file'; i.multiple = true; i.accept = '.xlsx'; i.onchange = () => res([...i.files]); i.click(); });
  function basesHTML() {
    const list = [{ id: 'embedded', ref: A.embeddedRef || '07/2026', uf: 'SP' }, ...(A.basesMeta || [])];
    return `<div class="tblw"><table class="tbl sm"><thead><tr><th>Base</th><th>Origem</th><th class="r">Conferência com o oficial</th><th></th></tr></thead><tbody>${list.map((x) => `<tr><td><b>SICRO ${esc(x.uf || '')} ${esc(x.ref)}</b>${x.id === A.base.id ? ' <span class="tag">ativa</span>' : ''}</td><td>${x.id === 'embedded' ? 'embutida no arquivo' : 'importada em ' + new Date(x.at).toLocaleDateString('pt-BR')}</td><td class="r">${x.valid && x.valid.total ? U.pct(x.valid.ok / x.valid.total, 3) : ''}</td>
      <td class="r">${x.id !== A.base.id ? `<button class="btn sm" data-act="useBase" data-id="${esc(x.id)}">Usar</button>` : ''}${x.id !== 'embedded' ? `<button class="ib sm danger" data-act="delBase" data-id="${esc(x.id)}" title="Excluir">${UI.icon('trash', 15)}</button>` : ''}</td></tr>`).join('')}</tbody></table></div>`;
  }
  UI.views.base = { render: () => {
    const b = A.base, raw = b.raw, v = raw.valid || {}, pj = A.pj, nEq = Object.keys(raw.eq || {}).length;
    const cnt = { mat: 0, eq: 0, mo: 0 }; raw.ins.k.forEach((k, i) => { if (i < b.nOfficialIns) cnt[['mat', 'mo', 'eq'][k] || 'mat']++; });
    const prz = raw.ins.v.filter((x, i) => x == null && raw.ins.k[i] === 0).length;
    const enc = (rg) => raw.encargos && raw.encargos[rg] ? `${U.num(raw.encargos[rg].h[0], 2)}% horista · ${U.num(raw.encargos[rg].m[0], 2)}% mensalista` : '—';
    const grp = (rg, kind) => { const g = raw.encGrp && raw.encGrp[rg] && raw.encGrp[rg][kind]; return g ? ['A', 'B', 'C', 'D'].map((k) => `<td class="r">${U.num(g[k], 2)}%</td>`).join('') : '<td colspan="4" class="muted">—</td>'; };
    const legend = Object.entries(raw.origLeg || {}).map(([k, t]) => `<tr><td><b>${esc(k)}</b></td><td>${esc(t)}</td><td class="r">${U.int(raw.ins.o.filter((o) => raw.orig[o] === k).length)}</td></tr>`).join('');
    return `<div class="vh"><div><h1>Base de dados</h1><p class="muted">Relatórios do SICRO/DNIT lidos neste navegador. Custos recalculados pela regra do SICRO (linhas em 4 casas, meio para cima; total em 2 casas) e conferidos com o relatório analítico publicado.</p></div></div>
      <div class="cards"><div class="card hl"><small>Referência ativa</small><b>SICRO ${esc(b.ufs[0])} ${esc(raw.ref)}</b><span class="muted">${esc(raw.ufName || '')} · ${b.id === 'embedded' ? 'embutida no arquivo' : 'importada neste navegador'}</span></div>
      <div class="card"><small>Composições</small><b>${U.int(b.nComp)}</b><span class="muted">${raw.grupos.length} grupos do SICRO</span></div>
      <div class="card"><small>Insumos</small><b>${U.int(b.nOfficialIns || b.nIns)}</b><span class="muted">${U.int(cnt.mat)} materiais · ${U.int(cnt.eq)} equipamentos · ${U.int(cnt.mo)} mão de obra</span></div>
      <div class="card"><small>Custos conferidos com o oficial</small><b>${U.int(v.ok)} / ${U.int(v.total)}</b><span class="muted">${v.total ? U.pct(v.ok / v.total, 3) : ''} · sem desoneração, sem transporte</span></div></div>
      <div class="panel"><h3>Importar outro relatório do SICRO (UF e mês)</h3><p>Extraia o pacote do DNIT (.7z ou .zip) e selecione, de uma vez, as planilhas <b>.xlsx</b>. O <b>Relatório Analítico de Composições de Custos</b> é obrigatório; recomenda-se incluir os sintéticos de <b>Materiais</b>, <b>Equipamentos</b> e <b>Mão de Obra</b> (com e sem desoneração), a <b>Origem de Preços</b> e os <b>Encargos Sociais</b>. Nada é enviado pela internet.</p>
      <button class="btn pri" data-act="importBase">${UI.icon('dl')} Selecionar planilhas…</button><div id="impProg" class="prog" hidden><i></i><span></span></div></div>
      <div class="panel"><h3>Bases disponíveis</h3>${basesHTML()}</div>
      <div class="panel"><h3>Regimes e encargos sociais</h3><div class="tblw"><table class="tbl sm"><thead><tr><th>Regime</th><th>Total</th><th class="r">Grupo A</th><th class="r">Grupo B</th><th class="r">Grupo C</th><th class="r">Grupo D</th></tr></thead><tbody>
        ${['SD', 'CD'].filter((rg) => raw.regimes.includes(rg)).map((rg) => `<tr><td><b>${S.REGIMES[rg]}</b> · horista</td><td>${enc(rg)}</td>${grp(rg, 'h')}</tr><tr><td><b>${S.REGIMES[rg]}</b> · mensalista</td><td></td>${grp(rg, 'm')}</tr>`).join('')}</tbody></table></div>
        <p class="note">${raw.regimes.includes('CD') ? 'Com desoneração: mão de obra e custos horários de equipamentos dos relatórios “com desoneração”; o custo das composições é recalculado pela mesma regra.' : 'Relatórios com desoneração não importados: somente o regime sem desoneração está disponível.'} ${nEq} equipamentos com parcelas de custo horário (depreciação, oportunidade de capital, seguros e impostos, manutenção, operação e mão de obra de operação).</p></div>
      <div class="panel"><h3>Origem dos preços dos insumos (${esc(b.ufs[0])})</h3>${legend ? `<div class="tblw" style="max-height:300px"><table class="tbl sm"><thead><tr><th>Sigla</th><th>Significado</th><th class="r">Insumos</th></tr></thead><tbody>${legend}</tbody></table></div>` : '<p class="muted">Relatório de origem de preços não importado.</p>'}
        <p class="note"><span class="tag sm warn">PRZ</span> ${prz} materiais com preço referencial zerado (ex.: CAP 50/70, asfalto diluído, emulsões, concreto e massa asfáltica comerciais). Nas composições entram com custo zero, como no relatório: inclua o fornecimento em item próprio (com BDI diferenciado, se for o caso) ou informe cotação do projeto.</p></div>
      <div class="panel"><h3>Composições próprias</h3>${A.customs.length ? `<div class="tblw"><table class="tbl sm"><thead><tr><th>Código</th><th>Descrição</th><th>Und</th><th class="r">Custo ${esc(pj.uf)}</th></tr></thead><tbody>${A.customs.map((c) => `<tr><td><button class="lnk code" data-act="openComp" data-code="${esc(c.code)}">${esc(c.code)}</button></td><td>${esc(c.desc)}</td><td>${esc(c.unit)}</td><td class="r">${UI.money(b.compCost(c.code, pj.uf, pj.rg))}</td></tr>`).join('')}</tbody></table></div>` : '<p class="muted">Nenhuma ainda. Abra uma composição SICRO e use “Criar própria”.</p>'}</div>`;
  } };
  UI.act.importBase = async () => {
    const files = await pick(); if (!files || !files.length) return;
    const pr = UI.$('#impProg'); pr.hidden = false; const bar = pr.querySelector('i'), txt = pr.querySelector('span');
    try {
      const raw = await S.importFiles(files, (msg, fr) => { bar.style.width = (fr * 100).toFixed(0) + '%'; txt.textContent = `${msg} ${(fr * 100).toFixed(0)}%`; });
      const id = 'SICRO-' + raw.ufs[0] + '-' + String(raw.ref).replace(/\W+/g, '-') + '-' + Date.now().toString(36);
      await OP.store.put('bases', { id, raw });
      A.basesMeta = (A.basesMeta || []).concat([{ id, ref: raw.ref, uf: raw.ufs[0], at: Date.now(), valid: { ok: raw.valid.ok, total: raw.valid.total } }]);
      await OP.store.setSetting('basesMeta', A.basesMeta); await OP.store.setSetting('activeBase', id);
      OP.main.useBase(raw, id); UI.render(); UI.toast(`SICRO ${raw.ufs[0]} ${raw.ref} importado: ${U.int(raw.valid.ok)} de ${U.int(raw.valid.total)} composições conferidas com o relatório.`);
    } catch (e) { console.error(e); UI.toast('Erro na importação: ' + e.message, 'warn'); pr.hidden = true; }
  };
  /* ---------------- Manual ---------------- */
  UI.views.manual = { render: () => {
    const b = A.base, J = +A.pj.calendar.hpd || 8.8, code = '4011209', has = b.compIdx.has(code);
    const ex = has ? OP.prod.calc(b, { code, qty: 84000, teams: 1 }, J) : null, an = has ? b.analytic(code, A.pj.uf, 'SD') : null, v = b.raw.valid || {};
    const sec = (t, body, open) => `<details${open ? ' open' : ''}><summary>${t}</summary><div class="mc">${body}</div></details>`;
    return `<div class="man"><div class="vh"><div><h1>Manual</h1><p class="muted">Fluxo de trabalho, regras de cálculo do SICRO, transporte, equipes, cronograma, BDI, eventograma e reforma tributária.</p></div></div>`
      + sec('1. O que o sistema faz', `<p>O OrçaPro Infraestrutura monta orçamentos e cronogramas de obras de infraestrutura com as composições do <b>SICRO</b> (DNIT). A base de ${esc(b.ufs[0])} ${esc(b.raw.ref)} vem embutida no arquivo e funciona sem internet; outras UFs e meses são importados a partir das planilhas publicadas. O fluxo é: <b>Catálogo</b> (encontrar a composição) → <b>Orçamento</b> (EAP e quantidades) → <b>Transportes (DMT)</b> → <b>BDI</b> → <b>Equipes e produtividade</b> → <b>Cronograma</b> → <b>Recursos e Curva S</b> → <b>Eventograma</b> e <b>Reforma Tributária</b>. Toda alteração recalcula custos, durações e datas.</p>`, true)
      + sec('2. Regra de cálculo do SICRO', `<p>Cada composição tem uma <b>equipe</b> e uma <b>produção horária</b>. O custo segue as seções do relatório analítico:</p><div class="formula">A) equipamentos: Σ r4( quantidade × (UO × CHP + UI × CHI) )<br>B) mão de obra: Σ r4( quantidade × custo horário )<br>custo unitário de execução = r4( (A + B) ÷ produção da equipe )<br>FIC = r4( FIC × r4( (Σ quantidade × CHI + B) ÷ produção ) )<br>C) material = Σ r4(q × preço) · D) auxiliares = Σ r4(q × custo da auxiliar)<br>E) tempo fixo = Σ r4(q × custo da carga/descarga) · F) transporte = Σ r4(q × Σ DMT × custo por tkm)<br>custo unitário direto total = r2(execução + FIC + C + D + E + F)</div><p>r4 e r2 são arredondamentos “meio para cima” em 4 e 2 casas, feitos em aritmética decimal exata. O <b>FIC</b> (fator de influência de chuvas) incide apenas sobre o custo improdutivo: equipamentos parados (CHI) e mão de obra. Na base ativa, <b>${U.int(v.ok)} de ${U.int(v.total)}</b> composições reproduzem o relatório publicado centavo a centavo.</p>${an ? `<p>Exemplo — ${esc(code)} (${esc(an.desc)}): execução ${U.num(Number(an.cuEx) / 1e4, 4)} + FIC ${U.num(Number(an.ficV) / 1e4, 4)} + material ${U.num(Number(an.matV) / 1e4, 4)} + auxiliares ${U.num(Number(an.auxV) / 1e4, 4)} = <b>${U.brl(Number(an.totalC) / 100)}</b> por ${esc(an.unit)}.</p>` : ''}`)
      + sec('3. Transporte (DMT), tempo fixo e materiais sem preço', `<p>O relatório publicado deixa a seção F (momento de transporte) em branco porque a distância depende da obra. Em <b>Transportes (DMT)</b> informe, por item transportado, a distância média em leito natural (LN), revestimento primário (RP), pavimentado (P) e ferrovia (FE). O custo entra em todas as composições que usam o item, inclusive nas atividades auxiliares (por exemplo, brita comercial até a usina e concreto asfáltico da usina até a pista). Sem DMT, os custos coincidem com o relatório.</p><p>O <b>tempo fixo</b> (seção E — carga, manobra e descarga) já vem quantificado nas composições. Materiais com origem <b>PRZ</b> (preço referencial zerado), como CAP, asfalto diluído e emulsões, entram com custo zero: inclua o fornecimento em item próprio, com BDI diferenciado, e o transporte por composição de transporte de material betuminoso.</p>`)
      + sec('4. Desoneração e FIT', `<p>“Sem desoneração” usa os relatórios oficiais; “com desoneração” recalcula as composições com a mão de obra e os custos horários de equipamentos dos relatórios desonerados. O <b>FIC</b> (Volume 04) pode ser recalculado no menu FIC para a UF, o solo, a declividade e o nd do projeto: FIC = fa × {1 + [(1 − C) × fr]} × nd, por etapa de execução, aplicado ao custo improdutivo. O <b>FIT</b> (fator de interferência de tráfego, Volume 05) é calculado no menu FIT para cada item transportado: atraso do sistema PARE e SIGA (A1) e das vias urbanas (A2) sobre a DMT pavimentada, que entra no momento de transporte como DMT fictícia (DMTF = FIT × DMTp).</p>`)
      + sec('5. Equipes, produtividade e duração', `<p>A equipe base é a equipe publicada na composição: mão de obra pela quantidade e equipamentos arredondados para cima. Horas por unidade = quantidade ÷ produção; para equipamentos separam-se horas produtivas (utilização operativa) e improdutivas. Duração (dias úteis) = quantidade × T ÷ (equipes × ${U.num(J, 1)} h/dia), em que T = 1 ÷ produção da equipe.</p>${ex ? `<p>Exemplo: ${U.num(84000, 0)} m² de regularização do subleito (${esc(code)}), produção de ${U.num(1 / ex.T, 2)} m²/h, 1 equipe → <b>${ex.days} dias úteis</b>.</p>` : ''}<p>Composições que só agregam atividades auxiliares (corpos e bocas de bueiro, caixas, fôrmas e armação) não têm equipe própria: o sistema estima a equipe a partir das auxiliares, e a duração pode ser ajustada manualmente.</p>`)
      + sec('6. Cronograma e Curva S', `<p>O cronograma usa o método do caminho crítico (CPM) com vínculos TI, II, TT e IT e defasagens. Em obras lineares, use vínculos II com defasagem (a camada seguinte começa depois de liberada uma extensão) e TT (termina depois da anterior). Gantt, rede PERT, tabela CPM, histogramas de mão de obra e equipamentos e Curva S são atualizados a cada alteração.</p>`)
      + sec('7. BDI e eventograma', `<p>O menu BDI calcula e aplica o BDI ao orçamento; o exemplo usa 20,97% (valor médio do Acórdão 2.622/2013-TCU para construção de rodovias e ferrovias) e BDI diferenciado de 14,02% para fornecimento de materiais betuminosos. O eventograma distribui o preço por marcos físicos, com prazos, multas e recebimentos provisório e definitivo.</p>`)
      + sec('8. Reforma tributária', `<p>A simulação de créditos de IBS e CBS (2026–2033) explode cada composição até os insumos. No SICRO, o custo horário dos equipamentos é decomposto em depreciação, oportunidade de capital, seguros e impostos, manutenção, operação (combustível ou energia) e operador, cada parcela com o seu perfil tributário. É uma estimativa econômica, não apuração fiscal.</p>`)
      + sec('9a. Mobilização e desmobilização (Volume 08)', `<p>O menu <b>Mobilização</b> aplica o Volume 08: a frota é o máximo simultâneo de cada equipamento das equipes SICRO no cronograma; cada equipamento é classificado (pequeno, misto ou grande), segue rodando se for autopropelido ou em transportador (FU pela área e pela massa úteis), com tempo de viagem pelas velocidades de referência de cada tipo de via, descanso, pedágios e k = 2 (mobilização e desmobilização). O efetivo transportado vem da Administração Local. A aba Conferência reproduz o caso do caderno de aplicação (R$ 22.119,65 de mão de obra e R$ 327.410,30 de equipamentos).</p>`)
      + sec('9b. Canteiro de obras', `<p>O menu <b>Canteiro de Obras</b> dimensiona as áreas pelas equações do manual em função do efetivo (que vem da Administração Local), aplica os fatores K1 a K3 e RCT, o CMCC e as instalações industriais identificadas no orçamento (central de concreto, britagem e usinas). As áreas coberta e descoberta alimentam a manutenção do canteiro na Administração Local. A aba Conferência executa os 39 testes oficiais do caderno.</p>`)
      + sec('9. Administração local (Volume 07)', `<p>O menu <b>Administração Local</b> aplica a metodologia do Manual de Custos de Infraestrutura de Transportes, Volume 07: parcela fixa pelo porte (extensão × 12 ÷ prazo), parcelas vinculadas às fases de terraplenagem, pavimentação, OAE e topografia, parcela variável pelas frentes de serviço, laboratórios de solos, asfaltos e concreto e manejo florestal (equações 4 a 16), segurança do trabalho pelo pico de profissionais (Tabela 22), manutenção do canteiro (CAC e CAD) e custos diversos. Os serviços vêm do orçamento, os prazos e o efetivo médio do cronograma, e os preços das equipes da base SICRO ativa. O motor reproduz o caderno de aplicação do DNIT (R$ 13.046.028,31) nos autotestes da aba Conferência. “Aplicar ao orçamento” grava o resultado como composição própria no item de administração local.</p>`)
      + sec('10. Exemplo: rodovia em SP', `<p>Construção de 6,0 km de pista simples (2 × 3,60 m) com acostamentos de 2,50 m: terraplenagem, drenagem e bueiros, pavimentação com base de BGS e concreto asfáltico, ponte de 40 m em vigas pré-moldadas protendidas, gabiões e solo grampeado, sinalização, defensas e proteção ambiental. As DMT seguem as fontes (pedreira, areal, jazida, usina e central no canteiro). A administração local é calculada no menu próprio (Volume 07). Mobilização, canteiro e preços dos materiais betuminosos são <b>valores ilustrativos</b>, identificados nos itens próprios, e devem ser substituídos por memórias e cotações do projeto real.</p><button class="btn" data-act="demo">${UI.icon('flag')} Recarregar o exemplo</button>`)
      + sec('11. Importação, exportação e limites', `<p>Base de dados: importe as planilhas .xlsx do SICRO de qualquer UF e mês. Arquivo: exportação do projeto (JSON), Excel, CSV e PDF. Os dados ficam no navegador (IndexedDB). Limites: uma UF por base; DMT, FIT, produtividade adotada e preços de itens próprios são responsabilidade do orçamentista; o simulador tributário não substitui a apuração fiscal.</p>`)
      + '</div>';
  } };
})(typeof window !== 'undefined' ? window : globalThis);

