/* ==== 43_mob_core.js — Mobilização e desmobilização (SICRO, Manual de Custos — Volume 08) ==== */
/* Motor da calculadora "MobilizaSICRO" do usuário, integrado ao OrçaPro: rotas, classes de
 * equipamentos, fator de utilização do transportador, tempos de viagem e de descanso, pedágios e
 * CHP/CHI dos transportadores; os custos horários passam a vir da base SICRO ativa. */
(function (G) {
'use strict';
const OP=G.OP; const MB=(OP.mob={version:'1.2.1-orçaplan'});
const DB=G.OP_DATA.mobilizationSeed;
const TECH_PROFILE=DB['technical-profile'],CADERNO_T8=DB['caderno-table8'],TRANSPORTER_TECH=DB['transporter-tech'],CADERNO_WORKFORCE=DB['caderno-workforce'],SOURCE_META=DB['source-meta'];
const TECH_BY_CODE=new Map(TECH_PROFILE.map(x=>[x.code,x]));const T8_BY_CODE=new Map(CADERNO_T8.map(x=>[x.code,x]));
const baseLabel=()=>{const b=OP.app&&OP.app.base;return b?('SICRO '+b.ufs[0]+' '+b.raw.ref):'base SICRO';};
/* custos horários dos equipamentos: base SICRO ativa (regime do orçamento) */
const EQUIP_DB={get(code){const b=OP.app&&OP.app.base;if(!b)return null;const i=b.insIdx.get(code);if(i==null||b.insCat[i]!=='eq')return null;const e=b.eqParts(code,(OP.app.pj&&OP.app.pj.rg)||'SD');return e?{code,description:b.raw.ins.d[i],chp:e[7],chi:e[8]}:null;},has(code){return !!this.get(code);}};
let state=null;
const BRL=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});const NUM2=new Intl.NumberFormat('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});const NUM4=new Intl.NumberFormat('pt-BR',{minimumFractionDigits:4,maximumFractionDigits:4});
let calc_unused;let calculations={};let validationItems=[];let equipmentPage=1,databasePage=1,databaseMode='equipment',dbSearch='',equipmentFilter='',equipmentClassFilter='all';let editingEquipmentId=null,editingTransporterId=null;let activePage='dashboard';
function id(prefix='id'){return prefix+'_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7)}
function n(v,d=0){const x=Number(v);return Number.isFinite(x)?x:d}function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function getPath(o,path){return path.split('.').reduce((a,k)=>a?.[k],o)}function setPath(o,path,value){const p=path.split('.');let cur=o;while(p.length>1){const k=p.shift();cur[k]??={};cur=cur[k]}cur[p[0]]=value}
function clone(v){return JSON.parse(JSON.stringify(v))}function fmtMoney(v){return BRL.format(n(v))}function fmt2(v){return NUM2.format(n(v))}function fmt4(v){return NUM4.format(n(v))}
function defaultTransporters(){return TRANSPORTER_TECH.map(t=>{const p=EQUIP_DB.get(t.code)||{};return{...clone(t),id:id('tr'),description:p.description||t.code,chp:p.chp??0,chi:p.chi??0,customPrice:false}})}
function blankState(){return{schema:1,id:id('project'),meta:{name:'Novo empreendimento',agency:'',responsible:'',municipality:'',workState:'SP',latitude:'',longitude:'',workType:'Construção rodoviária',workSubtype:'',size:'Não classificado',fronts:1,lengthKm:0,contractMonths:0,executionMonths:0,projectDirectCost:0,bdi:0,priceMode:'sicro2026',profile:'custom',notes:'',physicalSizeNote:'',financialSizeNote:'',temporalSizeNote:'',logisticSizeNote:'',priceState:'SP',priceReference:''},settings:{applyDailyRest:true,dailyWorkHours:8,dailyRestHours:11},routes:[{id:id('route'),name:'Rota principal',segments:[{id:id('seg'),type:'road_paved',distance:100,customSpeed:0,description:'Trecho principal'}]}],workforce:{nmoPeak:0,npfv:0,npvPeak:0,variablePct:50,ordinaryPct:50,localCount:0,rule:'standard',manualTotal:0,groups:[]},equipment:[],transporters:defaultTransporters(),complements:[],services:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}}
function normalizeState(s){const b=blankState();const x={...b,...s,meta:{...b.meta,...(s.meta||{})},settings:{...b.settings,...(s.settings||{})},workforce:{...b.workforce,...(s.workforce||{})}};x.routes=Array.isArray(s.routes)&&s.routes.length?s.routes:b.routes;x.equipment=Array.isArray(s.equipment)?s.equipment:[];x.transporters=Array.isArray(s.transporters)&&s.transporters.length?s.transporters:b.transporters;x.complements=Array.isArray(s.complements)?s.complements:[];x.services=Array.isArray(s.services)?s.services:[];x.workforce.groups=Array.isArray(s.workforce?.groups)?s.workforce.groups:[];return x}
function priceFor(code,ctx={}){if(ctx.customChp!=null&&ctx.customChp!=='')return{chp:n(ctx.customChp),chi:n(ctx.customChi),source:'manual no recurso'};if(state.meta.priceMode==='caderno2023'&&ctx.historicalChp!=null)return{chp:n(ctx.historicalChp),chi:n(ctx.historicalChi),source:'Caderno jul/2023'};const st=state?.transporters?.find(t=>t.code===code);if(st&&(st.customPrice||!EQUIP_DB.has(code)))return{chp:n(st.chp),chi:n(st.chi),source:'catálogo editável'};const p=EQUIP_DB.get(code);return{chp:n(p?.chp??st?.chp),chi:n(p?.chi??st?.chi),source:p?baseLabel():st?'catálogo técnico':'ausente'}}
function transporter(code){return state.transporters.find(t=>t.code===code)}
const SPEED={road_paved:{truck:60,tractor:30},road_primary:{truck:50,tractor:25},road_natural:{truck:40,tractor:20},rail:{truck:24,tractor:24,rail:24},water_tow:{truck:10.29,tractor:10.29,water:10.29},water_self:{truck:12.69,tractor:12.69,water:12.69},hopper750:{truck:15.48,tractor:15.48,water:15.48},hopper1000:{truck:18.49,tractor:18.49,water:18.49},hopper2000:{truck:20.95,tractor:20.95,water:20.95},hopper3000:{truck:22.49,tractor:22.49,water:22.49},hopper4000:{truck:23.49,tractor:23.49,water:23.49},hopper5000:{truck:24.96,tractor:24.96,water:24.96},hopper10000:{truck:28.97,tractor:28.97,water:28.97},custom:{truck:0,tractor:0}};
const SEG_LABEL={road_paved:'Rodovia pavimentada',road_primary:'Rodovia com revestimento primário',road_natural:'Rodovia em leito natural',rail:'Ferrovia',water_tow:'Hidrovia — combinação rebocada/empurrada',water_self:'Hidrovia — embarcação autopropelida',hopper750:'Draga hopper 750 m³',hopper1000:'Draga hopper 1.000 m³',hopper2000:'Draga hopper 2.000 m³',hopper3000:'Draga hopper 3.000 m³',hopper4000:'Draga hopper 4.000 m³',hopper5000:'Draga hopper 5.000 m³',hopper10000:'Draga hopper ≥ 10.000 m³',custom:'Velocidade personalizada'};
function routeMetrics(routeId,transportClass='truck'){const r=state.routes.find(x=>x.id===routeId)||state.routes[0];let distance=0,time=0,missing=false;for(const s of r?.segments||[]){const d=n(s.distance);let v=s.type==='custom'?n(s.customSpeed):n(SPEED[s.type]?.[transportClass]??SPEED[s.type]?.truck);distance+=d;if(v>0)time+=d/v;else if(d>0)missing=true}return{route:r,distance,time,missing}}
function restTime(tv,kind,drivers,override){if(override!==null&&override!==undefined&&override!=='')return Math.max(0,n(override));if(n(drivers,1)>=2)return 0;const interval=kind==='people'?4:6;let rest=Math.floor((tv+1e-9)/interval)*.5;if(state.settings.applyDailyRest&&tv>n(state.settings.dailyWorkHours,8)){rest+=Math.floor((tv-1e-9)/n(state.settings.dailyWorkHours,8))*n(state.settings.dailyRestHours,11)}return rest}
function workforceSuggested(){const w=state.workforce;if(w.rule==='manual')return Math.max(0,n(w.manualTotal));if(w.rule==='full')return Math.max(0,n(w.nmoPeak)+n(w.npfv)+n(w.npvPeak)-n(w.localCount));const nadm=n(w.npfv)+n(w.variablePct)/100*n(w.npvPeak);return Math.max(0,nadm+n(w.ordinaryPct)/100*n(w.nmoPeak)-n(w.localCount))}
function calcWorkforce(g){const t=transporter(g.transporterCode);const cap=n(g.capacity)||n(t?.passengerCapacity);const fu=n(g.manualFu)||((cap>0)?1/cap:0);const eq=n(g.people)*fu;const cls=t?.transportClass||'truck';const rawRoute=routeMetrics(g.routeId,cls);const rm={...rawRoute,time:(g.travelTimeOverride!==null&&g.travelTimeOverride!==undefined&&g.travelTimeOverride!=='')?n(g.travelTimeOverride):rawRoute.time};const td=restTime(rm.time,'people',g.drivers,g.restOverride);const pr=priceFor(g.transporterCode,{customChp:g.customChp,customChi:g.customChi,historicalChp:g.historicalChp,historicalChi:g.historicalChi});const k=n(g.k,2);const cc=n(g.tollOneWay)*k+n(g.otherPerEq);const cost=eq*((rm.time*pr.chp+td*pr.chi)*k+cc)+n(g.fixedCost);return{kind:'people',id:g.id,description:g.description||'Grupo de mão de obra',code:'PESSOAS',quantity:n(g.people),transporterCode:g.transporterCode,fu,eq,route:rm,td,k,cc,chp:pr.chp,chi:pr.chi,cost,priceSource:pr.source,published:n(g.cmdPublished),capacity:cap,operationalVehicles:cap?Math.ceil(n(g.people)/cap):0}}
function equipmentClass(item){if(item.sizeOverride&&item.sizeOverride!=='auto')return item.sizeOverride;if(item.referenceSizeClass)return item.referenceSizeClass;const mass=n(item.mass);const maxDim=Math.max(n(item.length),n(item.width));if(mass>0&&maxDim>0){if(mass<300&&maxDim<2.5)return'small';if(mass>=300&&maxDim>=2.5)return'large';return'mixed'}return'mixed'}
function calcFu(item,t){if(item.manualFu!==null&&item.manualFu!==undefined&&item.manualFu!=='')return n(item.manualFu);if(item.autoLong)return 1;if(!t)return 0;const a=t.areaUseful>0?n(item.area)/n(t.areaUseful):0;const c=t.loadUseful>0?n(item.mass)/n(t.loadUseful):0;return Math.max(a,c)}
function calcEquipment(item){const cls=equipmentClass(item);if(!item.include||cls==='small')return{kind:'equipment',id:item.id,description:item.description,code:item.code,quantity:n(item.quantity),transporterCode:item.autoLong?item.code:(item.transporterCode||''),fu:0,eq:0,route:routeMetrics(item.routeId,'truck'),td:0,k:n(item.k,2),cc:0,chp:0,chi:0,cost:0,priceSource:'não remunerado',sizeClass:cls,published:n(item.cmdPublished)};const t=item.autoLong?null:transporter(item.transporterCode);const trCode=item.autoLong?item.code:item.transporterCode;const trClass=item.autoLong?'truck':(t?.transportClass||'truck');const fu=calcFu(item,t);const eq=n(item.quantity)*fu;const rawRoute=routeMetrics(item.routeId,trClass);const rm={...rawRoute,time:(item.travelTimeOverride!==null&&item.travelTimeOverride!==undefined&&item.travelTimeOverride!=='')?n(item.travelTimeOverride):rawRoute.time};const td=restTime(rm.time,'cargo',item.drivers,item.restOverride);const pr=priceFor(trCode,{customChp:item.customChp,customChi:item.customChi,historicalChp:item.historicalChp,historicalChi:item.historicalChi});const k=n(item.k,2);const cc=n(item.tollOneWay)*k+n(item.otherPerEq);const cost=eq*((rm.time*pr.chp+td*pr.chi)*k+cc)+n(item.fixedCost);return{kind:'equipment',id:item.id,description:item.description,code:item.code,quantity:n(item.quantity),transporterCode:trCode,fu,eq,route:rm,td,k,cc,chp:pr.chp,chi:pr.chi,cost,priceSource:pr.source,sizeClass:cls,published:n(item.cmdPublished),transport:t}}
function calculate(){const labor=state.workforce.groups.map(calcWorkforce);const equipment=state.equipment.map(calcEquipment);const complementTotal=state.complements.reduce((s,x)=>s+n(x.amount),0);const laborTotal=labor.reduce((s,x)=>s+x.cost,0);const equipmentTotal=equipment.reduce((s,x)=>s+x.cost,0);const direct=laborTotal+equipmentTotal+complementTotal;const bdiValue=direct*n(state.meta.bdi)/100;const selling=direct+bdiValue;return{labor,equipment,complementTotal,laborTotal,equipmentTotal,direct,bdiValue,selling,resourceCount:state.workforce.groups.length+state.equipment.length}}
function validations(){const out=[];const add=(severity,title,message,ref='')=>out.push({severity,title,message,ref});if(state.meta.workState!==state.meta.priceState)add('warning','UF da obra difere da base de preços',`A obra está em ${state.meta.workState}, mas CHP, CHI e composições são de ${state.meta.priceState} — ${state.meta.priceReference}.`,'project');for(const r of state.routes){const m=routeMetrics(r.id,'truck');if(m.distance>0&&m.distance<50)add('warning','Distância inferior a 50 km',`A rota “${r.name}” tem ${fmt2(m.distance)} km e exige justificativa técnica.`,'routes');if(m.missing)add('error','Velocidade ausente',`A rota “${r.name}” contém segmento sem velocidade válida.`,'routes')}if(!state.routes.length)add('error','Nenhuma rota cadastrada','Cadastre ao menos uma rota de mobilização.','routes');for(const g of state.workforce.groups){const c=calcWorkforce(g);if(!g.transporterCode)add('error','Grupo de pessoas sem transportador',g.description||'Grupo sem descrição','workforce');if(c.capacity<=0)add('error','Capacidade de passageiros inválida',`${g.transporterCode||'Transportador'} não possui capacidade informada.`,'workforce');if(c.chp<=0)add('error','CHP ausente na mão de obra',`Não há CHP válido para ${g.transporterCode||'o transportador'}.`,'workforce');const autoRest=restTime(c.route.time,'people',g.drivers,null);if(autoRest>0&&g.restOverride!==null&&n(g.restOverride)===0)add('warning','Descanso zerado manualmente',`${g.description}: o trajeto sugere ${fmt2(autoRest)} h de descanso.`,'workforce')}
for(const item of state.equipment){const c=calcEquipment(item);const cl=c.sizeClass;if(cl==='mixed'&&item.include)add('warning','Porte inconclusivo',`${item.code} — ${item.description}: informe dimensões ou classifique com justificativa.`,'equipment');if(cl==='small'&&item.transporterCode)add('info','Pequeno porte com transportador específico',`${item.code} é de pequeno porte e, em regra, deve viajar na frota já mobilizada.`,'equipment');if(cl==='large'&&!item.autoLong&&!item.transporterCode&&item.include)add('error','Equipamento sem transportador',`${item.code} — ${item.description}`,'equipment');if(item.include&&cl!=='small'&&c.chp<=0)add('error','CHP ausente',`Não foi localizado CHP para o transportador de ${item.code}.`,'equipment');if(c.fu>1&&!item.fragmentable)add('error','FU superior a 1 sem fragmentação',`${item.code}: FU = ${fmt4(c.fu)}. Confirme mais de uma carga ou plano de desmontagem.`,'equipment');if(!item.autoLong&&item.transporterCode){const t=transporter(item.transporterCode);if(t&&!item.fragmentable&&(n(item.area)>n(t.areaUseful)||n(item.mass)>n(t.loadUseful)))add('error','Capacidade do transportador insuficiente',`${item.code} excede área ou carga útil de ${t.code}.`,'equipment')}const autoRest=restTime(c.route.time,'cargo',item.drivers,null);if(autoRest>0&&item.restOverride!==null&&n(item.restOverride)===0)add('warning','Descanso de carga zerado',`${item.code}: o trajeto sugere ${fmt2(autoRest)} h de descanso.`,'equipment')}
if(n(state.meta.bdi)===0)add('warning','BDI não informado','O resultado apresenta apenas custo direto.','project');if(!state.equipment.length&&!state.workforce.groups.length)add('info','Nenhum recurso cadastrado','Adicione mão de obra e equipamentos para formar a composição.','dashboard');if(!state.settings.applyDailyRest)add('info','Repouso diário automático desativado','Revise manualmente viagens que ultrapassem a jornada diária.','routes');if(state.meta.profile==='caderno'&&state.meta.priceMode==='sicro2026')add('info','Exemplo atualizado para abril/2026','Os valores não coincidirão com julho/2023; a comparação publicada permanece disponível.','results');return out}
MB.calculate=s=>{state=s;return calculate();};MB.validations=s=>{state=s;return validations();};MB.blankState=()=>blankState();MB.normalize=s=>normalizeState(s);
MB.defaultTransporters=()=>defaultTransporters();MB.equipmentClass=i=>equipmentClass(i);MB.SEG_LABEL=SEG_LABEL;MB.SPEED=SPEED;MB.TECH_BY_CODE=TECH_BY_CODE;MB.T8_BY_CODE=T8_BY_CODE;MB.TRANSPORTER_TECH=TRANSPORTER_TECH;MB.CADERNO_WORKFORCE=CADERNO_WORKFORCE;MB.TECH_PROFILE=TECH_PROFILE;MB.SOURCE_META=SOURCE_META;MB.id=id;MB.n=n;MB.routeMetrics=(s,r,c)=>{state=s;return routeMetrics(r,c);};
/* caso do caderno (Volume 08, Caderno de Aplicação — Tabelas 4, 6, 7 e 8) */
MB.cadernoState=()=>{const s=blankState();s.meta={...s.meta,name:'Exemplo SICRO — Construção rodoviária com OAE',priceMode:'caderno2023',bdi:0};s.settings.applyDailyRest=false;s.routes=[{id:id('route'),name:'Capital/origem → canteiro',segments:[{id:id('seg'),type:'road_paved',distance:323,customSpeed:0,description:'Rodovia pavimentada'}]}];const routeId=s.routes[0].id;
 s.workforce={nmoPeak:252,npfv:47,npvPeak:36,variablePct:50,ordinaryPct:50,localCount:0,rule:'standard',manualTotal:191,groups:CADERNO_WORKFORCE.map(w=>({id:id('wg'),description:w.description,people:w.people,transporterCode:w.transporter,capacity:w.capacity,routeId,k:w.k,drivers:1,travelTimeOverride:w.travelTime,restOverride:w.restTime,tollOneWay:w.tollOneWay,otherPerEq:0,fixedCost:0,manualFu:w.fu,historicalChp:w.chpHistorical,historicalChi:w.chiHistorical,cmdPublished:w.cmdPublished}))};
 s.equipment=TECH_PROFILE.map(p=>{const r=T8_BY_CODE.get(p.code);return {id:id('eq'),code:p.code,description:p.description,quantity:p.quantity,area:p.area,mass:p.mass,length:0,width:0,sizeOverride:p.sizeClass,referenceSizeClass:p.sizeClass,autoLong:p.autoLong,fragmentable:p.fragmentable,include:true,manualFu:r?.fuPublished??null,transporterCode:p.autoLong?p.code:(r?.transporter||''),routeId,k:2,drivers:1,travelTimeOverride:r?.travelTimePublished??null,restOverride:r?.restTimePublished??null,tollOneWay:r?.tollOneWay??0,otherPerEq:0,fixedCost:0,customChp:null,customChi:null,historicalChp:r?.chpHistorical??null,historicalChi:r?.chiHistorical??null,cmdPublished:r?.cmdPublished??0};});s.transporters=defaultTransporters();return s;};
MB.selfTests=()=>{const out=[],check=(name,fn)=>{try{const v=fn();out.push({name,pass:v!==false,detail:v===false?'Resultado divergente':''});}catch(e){out.push({name,pass:false,detail:e.message});}};
 check('Equação de referência do caderno: 3 × 0,09 × ((323/60 × 285,7414) × 2 + 43 × 2) = R$ 853,87',()=>Math.abs(3*.09*(((323/60)*285.7414)*2+43*2)-853.87)<=.03);
 const s=MB.cadernoState(),r=MB.calculate(s),pub=r.labor.concat(r.equipment).reduce((t,x)=>t+(x.published||0),0);
 check('Mão de obra do caderno: R$ 22.119,65',()=>Math.abs(r.laborTotal-22119.65)<=.05);
 check('Equipamentos do caderno: R$ 327.410,30 (tolerância de 0,1% pelo arredondamento de TV e FU publicados)',()=>Math.abs(r.equipmentTotal-327410.30)<=327410.30*.001);
 check('Benchmark das tabelas do caderno: R$ 349.529,95',()=>Math.abs(pub-349529.95)<.1);
 check('63 equipamentos e 3 grupos de pessoas do caso de referência',()=>r.equipment.length===63&&r.labor.length===3);
 check('Base SICRO ativa: custo horário dos transportadores disponível',()=>MB.defaultTransporters().every(t=>t.chp>0));return out;};
})(typeof window!=='undefined'?window:globalThis);

