/* ==== 50_manual.js — Manual interativo do OrçaPro Infraestrutura ==== */
(function (G) {
  'use strict';
  const OP = G.OP, U = OP.util, UI = OP.ui, A = OP.app, esc = U.esc;
  const KEY = 'orcaplan-infra-manual-v1';
  const st = () => (A.man = A.man || { cap: 'mapa', q: '', lab: { code: '4011209', qty: 84000, teams: 1, uf: 'SP', et: '4', nd: 'p', dr: 52, du: 8, vmdf: 0, ps: 0, ac: 4.01, s: 0.4, r: 0.56, g: 0.4, df: 1.11, l: 7.3, t: 5.65 } });
  const read = () => { try { return new Set(JSON.parse(localStorage.getItem(KEY) || '[]')); } catch (e) { return new Set(); } };
  const save = (s) => { try { localStorage.setItem(KEY, JSON.stringify([...s])); } catch (e) {} };
  const go = (v, t) => `<button class="btn sm" data-act="nav" data-v="${v}">${UI.icon('right', 14)} ${t}</button>`;
  const box = (t, body, cls = '') => `<div class="mbox ${cls}"><b>${t}</b><div>${body}</div></div>`;
  const flow = (steps) => `<div class="mflow">${steps.map(([t, d, v], i) => `${i ? '<span class="marr">→</span>' : ''}<div class="mstep"${v ? ` data-act="nav" data-v="${v}" title="Abrir o menu"` : ''}><b>${t}</b><small>${d}</small></div>`).join('')}</div>`;
  const steps = (list) => `<ol class="msteps">${list.map((x) => `<li>${x}</li>`).join('')}</ol>`;
  const fx = (s) => `<div class="formula">${s}</div>`;
  const n = (v, d = 2) => U.num(v, d);
  const inp = (k, v, w = 90, step = '') => `<input class="qty sm" style="width:${w}px" data-ch="manLab" data-k="${k}" value="${esc(String(v))}" ${step}>`;

  /* ---------------- laboratórios (motores do próprio sistema) ---------------- */
  function labSicro() {
    const L = st().lab, b = A.base, an = b.analytic(L.code, A.pj.uf, A.pj.rg);
    if (!an) return `<div class="mlab"><b>Laboratório — custo de uma composição</b><p>Código ${inp('code', L.code)} não encontrado.</p></div>`;
    const v = (x) => n(Number(x) / 1e4, 4);
    return `<div class="mlab"><b>Laboratório — anatomia de uma composição SICRO</b><p>Código ${inp('code', L.code)} · ${esc(an.desc)} (${esc(an.unit)})</p>
      ${fx(`custo horário de execução = A ${v(an.eqH)} + B ${v(an.moH)} = ${v(an.exH)} R$/h<br>custo unitário de execução = ${v(an.exH)} ÷ ${n(an.P, 5)} ${esc(an.unit)}/h = <b>${v(an.cuEx)}</b><br>FIC (${n(an.fic || 0, 5)}) sobre o custo improdutivo = <b>${v(an.ficV)}</b><br>material ${v(an.matV)} + auxiliares ${v(an.auxV)} + tempo fixo ${v(an.tfV)} + transporte ${v(an.mtV)}<br>custo unitário direto total = <b>${U.brl(Number(an.totalC) / 100)}</b>`)}
      <p class="note">Altere o código para ver outra composição. Os valores são os da base ativa, com as DMT, o FIT e o FIC deste projeto.</p></div>`;
  }
  function labDur() {
    const L = st().lab, J = +A.pj.calendar.hpd || 8.8; let r = null;
    try { r = OP.prod.calc(A.base, { code: L.code, qty: +L.qty || 0, teams: +L.teams || 1 }, J); } catch (e) {}
    return `<div class="mlab"><b>Laboratório — do orçamento ao prazo</b><p>Quantidade ${inp('qty', L.qty, 110)} de ${esc(L.code)} com ${inp('teams', L.teams, 60)} equipe(s), ${n(J, 1)} h/dia.</p>
      ${r && r.T ? fx(`produção da equipe = 1 ÷ T = ${n(1 / r.T, 3)} un/h · ${n(J / r.T, 2)} un/dia<br>duração = quantidade × T ÷ (equipes × horas/dia) = ${n(+L.qty, 2)} × ${n(r.T, 6)} ÷ (${+L.teams || 1} × ${n(J, 1)}) = <b>${r.days} dias úteis</b>`) : '<p class="muted">Composição sem equipe produtiva própria: informe a duração manualmente.</p>'}
      <p class="note">É exatamente o cálculo da tela Equipes e Produtividade; o resultado entra no CPM do Cronograma.</p></div>`;
  }
  function labFic() {
    const L = st().lab; if (!OP.fic) return '';
    const ref = OP.fic.reference(L.uf), e = +L.et, nd = ref.nd[L.nd === 'g' ? 1 : 0], fac = 1 + (1 - ref.C[e]) * ref.fr[e], v = OP.fic.rnd(fac * nd, 5);
    return `<div class="mlab"><b>Laboratório — FIC (Volume 04)</b><p>UF <select data-ch="manLab" data-k="uf">${Object.keys(OP.fic.ND).sort().map((u) => `<option${u === L.uf ? ' selected' : ''}>${u}</option>`).join('')}</select> · etapa <select data-ch="manLab" data-k="et">${[1, 2, 3, 4, 5].map((x) => `<option value="${x}"${String(x) === String(L.et) ? ' selected' : ''}>${x}</option>`).join('')}</select> · nd <select data-ch="manLab" data-k="nd"><option value="p"${L.nd !== 'g' ? ' selected' : ''}>padrão</option><option value="g"${L.nd === 'g' ? ' selected' : ''}>geotécnico</option></select></p>
      ${fx(`FIC = fa × {1 + [(1 − C) × fr]} × nd = 1 × {1 + [(1 − ${n(ref.C[e])}) × ${n(ref.fr[e])}]} × ${n(nd, 5)} = <b>${n(v, 5)}</b>`)}</div>`;
  }
  function labFit() {
    const L = st().lab; if (!OP.fit) return '';
    const r = OP.fit.calcRota({ ln: 0, rp: 0, dmtr: +L.dr || 0, dmtu: +L.du || 0, vmdf: +L.vmdf || 0, passa: true, fit: true }, { pareSiga: +L.ps === 1, Vu: 30, Vp: 60, lim: 100 });
    return `<div class="mlab"><b>Laboratório — FIT (Volume 05)</b><p>DMT rural ${inp('dr', L.dr, 70)} km · urbana ${inp('du', L.du, 70)} km · VMDf ${inp('vmdf', L.vmdf, 80)} · PARE e SIGA <select data-ch="manLab" data-k="ps"><option value="0"${+L.ps !== 1 ? ' selected' : ''}>não</option><option value="1"${+L.ps === 1 ? ' selected' : ''}>sim</option></select></p>
      ${fx(`A1 = ${n(r.A1)} s · A2 = Fc × DMTu = ${n(r.A2)} s<br>FIT = 1 + (A1 + A2) ÷ (DMTp × Fp) = <b>${n(r.FIT, 4)}</b> · DMT fictícia = ${n(r.DMTF)} km`)}</div>`;
  }
  function labBdi() {
    const L = st().lab, p = (k) => (+L[k] || 0) / 100, K = (1 + p('ac') + p('s') + p('r') + p('g')) * (1 + p('df')) * (1 + p('l')), bdi = K / (1 - p('t')) - 1;
    return `<div class="mlab"><b>Laboratório — fórmula do BDI (Acórdão 2.622/2013-TCU)</b><p>AC ${inp('ac', L.ac, 60)}% · S ${inp('s', L.s, 60)}% · R ${inp('r', L.r, 60)}% · G ${inp('g', L.g, 60)}% · DF ${inp('df', L.df, 60)}% · L ${inp('l', L.l, 60)}% · tributos T ${inp('t', L.t, 60)}%</p>
      ${fx(`BDI = [(1 + AC + S + R + G) × (1 + DF) × (1 + L)] ÷ (1 − T) − 1 = <b>${U.pct(bdi, 2)}</b>`)}
      <p class="note">Referência do TCU para construção de rodovias e ferrovias: 1º quartil 19,60%, médio 20,97%, 3º quartil 24,23%. O menu BDI faz este cálculo com a tributação detalhada (ISS, CPRB, PIS/COFINS e equivalência do IVA) e aplica o resultado ao orçamento.</p></div>`;
  }
  function labAbc() {
    const m = UI.model(), rows = m.items.filter((r) => r.total > 0).sort((a, b) => b.total - a.total), tot = U.sum(rows, (r) => r.total); let acc = 0;
    const top = rows.slice(0, 8).map((r) => { const prev = acc / tot; acc += r.total; return `<tr><td>${esc(r.num)}</td><td>${esc(String(r.desc).slice(0, 60))}</td><td class="r">${U.pct(r.total / tot, 2)}</td><td class="r">${U.pct(acc / tot, 1)}</td><td><b>${prev < 0.8 ? 'A' : prev < 0.95 ? 'B' : 'C'}</b></td></tr>`; }).join('');
    return `<div class="mlab"><b>Laboratório — curva ABC do orçamento aberto</b><div class="tblw"><table class="tbl sm"><thead><tr><th>Item</th><th>Serviço</th><th class="r">Peso</th><th class="r">Acumulado</th><th>Classe</th></tr></thead><tbody>${top}</tbody></table></div><p class="note">${U.int(rows.length)} itens com preço; classe A até 80% do preço acumulado, B de 80% a 95%, C o restante.</p></div>`;
  }

  /* ---------------- capítulos ---------------- */
  const CAPS = [
    ['mapa', 'Mapa do sistema', () => `<p>O OrçaPro Infraestrutura transforma a base do <b>SICRO/DNIT</b> em um orçamento completo e em um planejamento coerente. Cada menu alimenta o seguinte — e toda alteração se propaga automaticamente.</p>
      ${flow([['Base SICRO', '6.619 composições conferidas', 'base'], ['Catálogo', 'encontrar o serviço', 'catalog'], ['Orçamento', 'EAP e quantidades', 'budget'], ['Transporte · FIT · FIC', 'DMT e fatores', 'transport'], ['Produções', 'demonstrativos', 'pem'], ['BDI', 'preço de venda', 'bdi']])}
      ${flow([['Equipes', 'duração de cada serviço', 'crews'], ['Cronograma', 'CPM, Gantt e PERT', 'schedule'], ['Recursos e Curva S', 'histogramas e desembolso', 'resources'], ['Eventograma', 'marcos e pagamentos', 'evento'], ['Mob. · Canteiro · AL', 'custos indiretos do Vol. 06–08', 'al'], ['Reforma Tributária', 'créditos de IBS e CBS', 'reforma']])}
      ${box('Regra de ouro', 'O catálogo do SICRO nunca é alterado. Ajustes (cópias, demonstrativos editados, cotações) geram <b>composições próprias</b> deste projeto e substituem as originais apenas no orçamento.', 'hl')}
      ${box('Integração automática', 'Mudou equipe, produção, vínculo ou calendário? O cronograma é recalculado e, se as calculadoras de Administração Local, Canteiro e Mobilização já estiverem aplicadas, elas são recalculadas e reaplicadas ao orçamento — na ordem AL → Canteiro (com retorno das áreas à AL) → Mobilização.')}
      <p>Use o índice ao lado, a busca ou os botões “Ir para o menu”. Marque os capítulos lidos: o progresso fica salvo neste navegador.</p>`],
    ['conceitos', 'Conceitos de engenharia de custos', () => `<p>Os termos abaixo aparecem em todas as telas. Entendê-los é o primeiro passo para ler e auditar um orçamento de obra pública.</p>
      <div class="mgrid">${[['Custo direto', 'Soma dos custos dos serviços executados (mão de obra, equipamentos, materiais, transportes). No sistema: quantidade × custo unitário de cada item.'], ['Composição de custo', 'Receita do serviço: quais insumos, em que quantidades e com que equipe se produz uma unidade. O SICRO publica a composição e o custo por UF e mês.'], ['Insumo', 'Material (M), equipamento (E) ou mão de obra (P). Equipamentos têm custo horário produtivo (CHP) e improdutivo (CHI).'], ['Produção da equipe', 'Quantas unidades a equipe faz por hora. Define o custo de execução e, no planejamento, a duração do serviço.'], ['BDI', 'Benefícios e Despesas Indiretas: administração central, seguros, garantias, riscos, despesas financeiras, lucro e tributos sobre o faturamento. Preço = custo × (1 + BDI).'], ['Custos indiretos da obra', 'Administração local, canteiro e mobilização/desmobilização — no SICRO entram como itens do orçamento (Volumes 06 a 08), não no BDI.'], ['Desoneração', 'Regime em que a contribuição previdenciária sai da folha (encargos menores) e passa a incidir sobre a receita (CPRB, no BDI).'], ['DMT e momento de transporte', 'Distância média de transporte por tipo de via; massa × DMT × custo por tkm compõe o transporte dos materiais.'], ['FIC e FIT', 'Fatores do SICRO para paralisação por chuva (sobre o custo improdutivo) e interferência de tráfego (sobre a DMT pavimentada).'], ['Caminho crítico', 'Sequência de serviços sem folga: qualquer atraso neles atrasa a obra.'], ['Curva S', 'Custo acumulado ao longo do tempo; base do cronograma físico-financeiro e do fluxo de caixa.'], ['Curva ABC', 'Ordenação de serviços ou insumos pelo peso no preço: poucos itens (classe A) concentram a maior parte do valor.']].map(([t, d]) => box(t, d)).join('')}</div>`],
    ['sicro', 'Como o SICRO funciona', () => `<p>O SICRO organiza cada composição em seis seções. O sistema reproduz o relatório analítico oficial <b>centavo a centavo</b> (${U.int((A.base.raw.valid || {}).ok || 0)} de ${U.int((A.base.raw.valid || {}).total || 0)} composições conferidas).</p>
      <div class="mgrid">${[['A — Equipamentos', 'Quantidade × (UO × CHP + UI × CHI): UO e UI são as utilizações operativa e improdutiva da equipe.'], ['B — Mão de obra', 'Quantidade × custo horário (salário + encargos).'], ['Execução e FIC', 'Custo de execução = (A + B) ÷ produção. O FIC incide sobre o custo improdutivo: (Σ q × CHI + B) ÷ produção.'], ['C — Material', 'Quantidade × preço. Materiais PRZ (preço zerado, como CAP e emulsões) entram com custo zero e são pagos em itens próprios.'], ['D — Atividades auxiliares', 'Outras composições usadas como insumo (concreto, usinagem, escavação de jazida).'], ['E e F — Tempo fixo e transporte', 'Carga, manobra e descarga; e momento de transporte com a DMT de cada tipo de via (definida no projeto).']].map(([t, d]) => box(t, d)).join('')}</div>
      ${fx('linhas arredondadas em 4 casas (meio para cima) · total = r2(execução + FIC + C + D + E + F)')}${labSicro()}
      <p>Os <b>demonstrativos de produção</b> (Produção de Equipe Mecânica) explicam de onde vem a produção da equipe: variáveis (capacidade, distâncias, tempos, eficiência), fórmula de cada equipamento, equipamento líder e utilizações. ${go('pem', 'Demonstrativo de Produções Horárias')} ${go('base', 'Base de dados')}</p>`],
    ['orcamento', 'Passo a passo: o orçamento', () => `${steps(['<b>Crie ou abra o orçamento</b> no menu Arquivo (ou recarregue o exemplo da rodovia). Ajuste UF, regime (com ou sem desoneração) e BDI na barra superior.', '<b>Monte a EAP</b>: botão “Etapa” para os grupos (terraplenagem, drenagem…); clique numa etapa para torná-la destino dos novos serviços.', '<b>Encontre o serviço</b> no Catálogo (árvore por grupo e fatores) ou na busca (Ctrl K) por código, descrição ou sinônimo (CBUQ, BSTC, gabião).', '<b>Informe a quantidade</b> e, se quiser, a memória de cálculo (ícone de lista ao lado do código).', '<b>Itens especiais</b>: “Item com custo” para valores informados; insumos diretamente no orçamento (ex.: fornecimento de CAP com BDI diferenciado); composições próprias e cópias em Composições.', '<b>Transporte, FIT e FIC</b>: defina as DMT por item transportado; ajuste o FIT (tráfego) e, se preciso, recalcule o FIC para a UF e as condições do projeto.', '<b>Confira</b> com “Verificar orçamento” e as curvas ABC; exporte em Excel, CSV ou PDF.'])}${go('budget', 'Orçamento')} ${go('catalog', 'Catálogo SICRO')} ${go('compositions', 'Composições')}`],
    ['cronograma', 'Do orçamento ao cronograma', () => `<p>Cada item do orçamento vira uma atividade. A duração nasce da equipe da composição — não é digitada.</p>
      ${flow([['Quantidade', 'do orçamento'], ['Produção da equipe', 'da composição / demonstrativo'], ['Equipes simultâneas', 'Equipes e Produtividade'], ['Duração', 'dias úteis'], ['Vínculos', 'TI, II, TT, IT + defasagens'], ['CPM', 'datas, folgas e caminho crítico']])}
      ${labDur()}
      ${steps(['Em <b>Equipes e Produtividade</b>, ajuste equipes simultâneas, prazo desejado (o sistema dimensiona as equipes) ou duração manual para serviços sem equipe própria.', 'No <b>Cronograma</b>, escolha o sequenciamento (manual, com vínculos editados) e o calendário: início, dias da semana, horas/dia, feriados nacionais e carnaval.', 'Em obras lineares, use vínculos <b>II com defasagem</b> (a camada seguinte começa depois de liberada uma extensão) e <b>TT</b> (termina depois da anterior). Ex.: regularização II+4 sub-base, TT+4.', 'Administração local e canteiro acompanham o prazo da obra automaticamente (duração = prazo dos demais serviços).', 'Analise Gantt, rede PERT e tabela CPM (início e término mais cedo/tarde, folga total). Itens em vermelho são críticos.', 'Em <b>Recursos e Curva S</b> veja os histogramas de mão de obra e equipamentos e o desembolso acumulado.'])}${go('crews', 'Equipes')} ${go('schedule', 'Cronograma')} ${go('resources', 'Recursos e Curva S')}`],
    ['fatores', 'Transporte, FIT, FIC e produções', () => `<div class="mgrid">${box('Transportes (DMT)', 'Para cada item transportado (material ou produto de outra composição) informe a DMT em leito natural, revestimento primário, pavimentado e ferrovia. O custo entra em todas as composições que o usam, inclusive auxiliares. Sem DMT, o custo coincide com o relatório.')}${box('FIT — Volume 05', 'Atrasos do PARE e SIGA (A1) e de trechos urbanos (A2) aumentam a DMT pavimentada: DMTF = FIT × DMTp. Configurado por item transportado no menu FIT.')}${box('FIC — Volume 04', 'Por padrão vale o FIC publicado. No modo “recalculado”, o FIC de cada composição segue a etapa, o tipo de nd, a UF, o solo e a declividade do projeto.')}${box('Produções horárias', 'Editar um demonstrativo cria a composição própria CP-código com a nova produção e utilizações; o prazo do serviço e todos os resultados são recalculados.')}</div>
      ${labFit()}${labFic()}${go('transport', 'Transportes')} ${go('fit', 'FIT')} ${go('fic', 'FIC')} ${go('pem', 'Produções horárias')}`],
    ['bdi', 'BDI, riscos e o orçamento', () => `<p>O BDI transforma custo em preço. No menu BDI você escolhe o modo de cálculo — paramétrico, exato (matriz de creditamento) ou Simples Nacional —, compara cenários e simula reequilíbrio na transição tributária.</p>
      ${fx('K = (1 + AC + R + S + G) × (1 + DF) × (1 + L) · T = ISS + CPRB + PIS/COFINS · BDI = K × (1 + IVAeq) ÷ (1 − T) − 1')}
      ${labBdi()}
      ${flow([['Menu BDI', 'componentes e tributos', 'bdi'], ['Aplicar', 'grava o BDI do projeto'], ['Orçamento', 'preço = custo × (1 + BDI)', 'budget'], ['BDI diferenciado', 'itens de fornecimento de materiais'], ['Eventograma e Curva S', 'valores com BDI']])}
      ${box('Riscos e contingências', 'Neste sistema os riscos entram no BDI pela parcela <b>R</b> (riscos), ao lado de S (seguros) e G (garantias). Calibre-as pelo perfil de risco do contrato e confira com as faixas do TCU: o BDI resultante segue para o orçamento ao ser aplicado. Incertezas de prazo e produtividade são tratadas no cronograma (equipes, folgas e caminho crítico). A versão atual não tem um módulo próprio de análise quantitativa de riscos (simulação de cenários de custo).', 'hl')}
      ${box('Custos que não vão para o BDI', 'Administração local, canteiro e mobilização são itens do orçamento calculados pelos Volumes 06 a 08 — não devem ser repetidos no BDI.')}${go('bdi', 'BDI')}`],
    ['indiretos', 'Mobilização, canteiro e administração local', () => `<p>As três calculadoras usam o orçamento e o cronograma como entrada e devolvem um item do orçamento (composição própria cotada).</p>
      ${flow([['Cronograma', 'prazos e efetivo médio'], ['Administração Local', 'Vol. 07: fixa, vinculada, variável', 'al'], ['Canteiro de Obras', 'efetivo da AL → áreas', 'can'], ['AL', 'manutenção do canteiro (áreas)'], ['Mobilização', 'Vol. 08: frota de pico + efetivo', 'mob'], ['Orçamento', 'CP-AL, CP-CAN, CP-MOB', 'budget']])}
      <div class="mgrid">${box('Administração Local', 'Parcela fixa pelo porte (extensão × 12 ÷ prazo), parcelas vinculadas às fases (terraplenagem, pavimentação, OAE), variável pelas frentes de serviço e laboratórios, segurança do trabalho, manutenção do canteiro e custos diversos. Prazos e efetivo vêm do cronograma.')}${box('Canteiro de Obras', 'Áreas pelas equações do manual em função do efetivo (vindo da AL), fatores K1–K3 e RCT, CMCC e instalações industriais identificadas no orçamento (usinas e centrais).')}${box('Mobilização', 'Frota = máximo simultâneo de cada equipamento no cronograma; transporte autopropelido ou em transportador (FU por área e massa), tempos de viagem e descanso, pedágios, k = 2 (ida e volta); efetivo transportado vindo da AL.')}${box('Sincronização', 'Depois de aplicadas, as três são recalculadas e reaplicadas sozinhas quando o cronograma muda. Para mantê-las fixas, não as aplique ao orçamento.')}</div>`],
    ['evento', 'Eventograma', () => `<p>O eventograma distribui o preço por marcos físicos (eventos) e define prazos, multas e recebimentos. Cada item do orçamento pertence a um evento (ou é “Diluído” ao longo da obra).</p>${steps(['Cadastre os eventos e subeventos com prazo (dias) e multa diária.', 'Associe itens ou etapas aos eventos; recebimentos provisório e definitivo entram como parcelas fixas.', 'A data prevista de cada evento vem do cronograma; se ultrapassar o prazo contratual, o evento aparece “após o prazo” e a simulação de atraso calcula a multa.', 'A curva de pagamentos mostra quando cada parcela do preço é recebida.'])}${go('evento', 'Eventograma')}`],
    ['tributos', 'Reforma tributária: IBS e CBS', () => `<p>O módulo estima o <b>crédito de IBS e CBS</b> que o construtor pode recuperar sobre os insumos do orçamento em cada ano da transição (2026–2033). É uma estimativa econômica, não apuração fiscal: não reduz o preço nem altera o BDI automaticamente.</p>
      <h4>Como o cálculo é feito</h4>${steps(['<b>Explosão até os insumos</b>: cada serviço é aberto até o último nível (auxiliares, tempo fixo, transporte). No SICRO, o custo horário de cada equipamento é decomposto em depreciação, oportunidade de capital, seguros e impostos, manutenção, operação (diesel ou energia, em litros ou kWh equivalentes) e operador.', '<b>Perfil tributário</b> de cada ocorrência: material, mão de obra (sem crédito), depreciação (crédito econômico do ativo, por rateio), manutenção, combustíveis (regime monofásico, base equivalente por litro), energia, locação, seguros etc.', '<b>Base creditável</b> = valor do insumo, com o ICMS/ISS remanescente do ano tratado conforme as premissas, e com redutores de alíquota dos anexos da LC 214/2025 quando o insumo se enquadra.', '<b>Crédito do ano</b> = base creditável × alíquotas de CBS e IBS daquele ano. Crédito fiscal (operações correntes) e crédito econômico (rateio do ativo) são mostrados separadamente.', '<b>Reconciliação</b>: o total explodido é ajustado ao custo direto de cada serviço; ocorrências sem preço ou sem perfil ficam como pendências e tornam o resultado “parcial”.'])}
      <h4>O que você pode editar</h4><div class="mgrid">${box('Ano do IVA', 'Barra superior ou topo do módulo: escolhe o ano de 2026 a 2033 mostrado nas colunas do orçamento.')}${box('Alíquotas IVA', 'CBS e IBS por ano e o percentual remanescente de ICMS/ISS na transição.')}${box('ICMS e ISS', 'Alíquotas por UF e município usadas para separar o tributo antigo embutido nos preços.')}${box('Premissas', 'Hipóteses do motor (tratamento do ativo, valoração, regras gerais) — salvas no projeto; exporte e importe cenários.')}${box('Créditos e regimes', 'Regime do fornecedor e enquadramento em anexos/redutores por insumo ou grupo.')}${box('Combustíveis', 'Alíquotas específicas por litro e equivalências do diesel, gasolina e GLP.')}${box('Consultar insumos e serviços', 'Perfil de cada insumo, memória do crédito por unidade e justificativa/fonte de alterações.')}${box('Dados e testes', 'Autotestes do motor e conferência das bases.')}</div>
      ${box('Relação com o BDI', 'O BDI considera a transição pela equivalência IVAeq e pela matriz de creditamento (modo exato). O crédito estimado no módulo tributário é informativo e serve para avaliar o efeito econômico e o reequilíbrio.')}${go('reforma', 'Reforma Tributária')} ${go('bdi', 'BDI')}`],
    ['abc', 'Curvas ABC de serviços e de insumos', () => `<p>Disponíveis no Orçamento. A <b>curva de serviços</b> ordena os itens pelo preço; a <b>curva de insumos</b> explode todas as composições e soma cada insumo (material, equipamento, mão de obra) no orçamento inteiro, com rastreabilidade de onde ele aparece.</p>${labAbc()}${box('Para que servem', 'Focar a análise de preços e quantidades nos itens A; negociar e cotar os insumos de maior peso; conferir a coerência de quantitativos; e, na curva de insumos, ver o crédito tributário por insumo (curva ABC tributária).')}${go('budget', 'Orçamento')}`],
    ['dados', 'Base, importação, exportação e limites', () => `${steps(['<b>Base embutida</b>: SICRO SP 07/2026, funciona sem internet. Outras UFs e meses: menu Base de dados, selecionando as planilhas .xlsx do DNIT (o analítico de composições é obrigatório).', '<b>Conferência</b>: toda importação recalcula as composições e compara com o relatório oficial.', '<b>Armazenamento</b>: projetos e bases ficam no navegador (IndexedDB). Use Arquivo → exportar projeto (JSON) para backup e troca.', '<b>Exportações</b>: orçamento em Excel, CSV e PDF; cronograma em SVG, PNG e PDF; administração local em CSV.', '<b>Limites</b>: uma UF por base; DMT, FIT, produtividades adotadas e preços próprios são responsabilidade do orçamentista; o módulo tributário é estimativa econômica.'])}${go('base', 'Base de dados')}`],
    ['glossario', 'Glossário rápido', () => `<div class="tblw"><table class="tbl sm"><tbody>${[['CHP / CHI', 'Custo horário produtivo / improdutivo do equipamento'], ['UO / UI', 'Utilização operativa / improdutiva na equipe'], ['FIC', 'Fator de influência de chuvas (Vol. 04)'], ['FIT', 'Fator de interferência de tráfego (Vol. 05)'], ['DMT / DMTF', 'Distância média de transporte / DMT fictícia com FIT'], ['PRZ', 'Preço referencial zerado no SICRO'], ['PEM', 'Produção de equipe mecânica (demonstrativo)'], ['CPM', 'Método do caminho crítico'], ['TI, II, TT, IT', 'Vínculos término-início, início-início, término-término, início-término'], ['AC, S, R, G, DF, L', 'Administração central, seguros, riscos, garantias, despesas financeiras, lucro'], ['CPRB', 'Contribuição previdenciária sobre a receita bruta (desoneração)'], ['IBS / CBS', 'Imposto e contribuição sobre bens e serviços (LC 214/2025)'], ['CMCC', 'Custo médio de construção civil (canteiro)'], ['NPF, NPV, NMO', 'Profissionais das parcelas fixa e variável e mão de obra ordinária']].map(([a, b]) => `<tr><td><b>${a}</b></td><td>${b}</td></tr>`).join('')}</tbody></table></div>`],
  ];
  UI.views.manual = { render: () => {
    const s = st(), rd = read(), q = U.norm(s.q || '');
    const list = q ? CAPS.filter(([id, t, f]) => U.norm(t + ' ' + f().replace(/<[^>]+>/g, ' ')).includes(q)) : CAPS;
    const cur = CAPS.find((c) => c[0] === s.cap) || CAPS[0], i = CAPS.indexOf(cur);
    return `<div class="vh"><div><h1>Manual</h1><p class="muted">Guia interativo do OrçaPro Infraestrutura · ${rd.size} de ${CAPS.length} capítulos lidos</p></div></div>
      <div class="mwrap"><nav class="mnav"><input data-ch="manQ" value="${esc(s.q || '')}" placeholder="Buscar no manual…">
        <div class="mprog"><i style="width:${(100 * rd.size / CAPS.length).toFixed(0)}%"></i></div>
        ${list.map(([id, t]) => `<button class="${id === cur[0] ? 'on' : ''}" data-act="manGo" data-id="${id}">${rd.has(id) ? '✓ ' : ''}${esc(t)}</button>`).join('') || '<p class="muted">Nada encontrado.</p>'}</nav>
        <article class="mart"><h2>${esc(cur[1])}</h2>${cur[2]()}
          <div class="row" style="justify-content:space-between;margin-top:18px">${i > 0 ? `<button class="btn" data-act="manGo" data-id="${CAPS[i - 1][0]}">← ${esc(CAPS[i - 1][1])}</button>` : '<span></span>'}
          <button class="btn ${rd.has(cur[0]) ? '' : 'pri'}" data-act="manRead" data-id="${cur[0]}">${rd.has(cur[0]) ? 'Lido ✓' : 'Marcar como lido'}</button>
          ${i < CAPS.length - 1 ? `<button class="btn" data-act="manGo" data-id="${CAPS[i + 1][0]}">${esc(CAPS[i + 1][1])} →</button>` : '<span></span>'}</div></article></div>`;
  } };
  UI.act.manGo = (el) => { st().cap = el.dataset.id; UI.render(); const a = document.querySelector('.mart'); if (a) a.scrollIntoView({ block: 'start' }); };
  UI.act.manRead = (el) => { const s = read(); if (s.has(el.dataset.id)) s.delete(el.dataset.id); else s.add(el.dataset.id); save(s); UI.render(); };
  UI.chg.manQ = (el) => { st().q = el.value; UI.render(); };
  UI.chg.manLab = (el) => { st().lab[el.dataset.k] = el.value; UI.render(); };
})(typeof window !== 'undefined' ? window : globalThis);

