window.installOrcaProRisks = function installOrcaProRisks() {
  'use strict';
  const O=window.OP,A=O.app,UI=O.ui,U=O.util,C=O.riskLocal,esc=U.esc;
  const S=O.risks={active:null,tab:'model',draft:null,dirty:false,busy:false,filter:'',page:1,error:'',bdiMethod:'param',applyMode:'replace',preview:null};
  window.addEventListener('beforeunload',event=>{if(S.dirty||S.busy){event.preventDefault();event.returnValue='';}});
  const clone=v=>JSON.parse(JSON.stringify(v)), money=c=>U.brl(Number(c)/100), pct=v=>U.num(Number(v)*100,2)+'%';
  const analyses=()=>A.pj.risks?.analyses?.filter(a=>!a.archivedAt)||[];
  const active=()=>analyses().find(a=>a.id===S.active)||analyses().at(-1);
  function select(a) { S.active=a?.id;S.draft=a?clone(a.config):null;S.dirty=false;S.preview=null;S.error='';S.page=1; }
  const field=(label,key,value,type='number',owner='',index='')=>`<label class="fld"><span>${esc(label)}</span><input class="inp" data-ch="riskField" data-in="riskField" data-owner="${owner}" data-index="${index}" data-key="${key}" type="${type}" ${type==='number'?'step="any"':''} value="${esc(value??'')}"></label>`;
  const choose=(label,key,value,list,owner='',index='')=>`<label class="fld"><span>${esc(label)}</span><select class="inp" data-ch="riskField" data-in="riskField" data-owner="${owner}" data-index="${index}" data-key="${key}">${list.map(([k,t])=>`<option value="${k}" ${value===k?'selected':''}>${esc(t)}</option>`).join('')}</select></label>`;
  const distributions=[['triangular','Triangular'],['pert','PERT beta'],['uniforme','Uniforme'],['normal_truncada','Normal truncada'],['lognormal','Lognormal'],['fixo','Fixo']];
  const responsibilities=[['contratado','Contratado'],['compartilhado','Compartilhado'],['administracao','Administração (excluído)']];
  function modeledRows(a) {
    const rows=a.snapshot.rows.filter(r=>U.norm(r.code+' '+r.description).includes(U.norm(S.filter)));
    const page=rows.slice((S.page-1)*40,S.page*40);
    return `<div class="risk-toolbar"><input class="inp" data-in="riskSearch" data-fk="riskSearch" placeholder="Filtrar código ou serviço…" value="${esc(S.filter)}" aria-label="Filtrar serviços"><button class="btn sm" data-act="riskSelectScope">Selecionar serviços do escopo</button><button class="btn sm" data-act="riskSelectNone">Desmarcar todos</button></div><p class="note">Variações em %. Eventos são modelados em reais. Configure todos os riscos selecionados; os valores iniciais são hipóteses editáveis.</p><div class="tblw"><table class="tbl sm"><thead><tr><th>Incluir</th><th>Serviço / ABC / custo direto</th><th>Probabilidade %</th><th>Mínimo %</th><th>Provável %</th><th>Máximo %</th><th>Distribuição</th><th>Responsável</th><th>Tipo</th><th>Detalhes</th></tr></thead><tbody>${page.map(row=>{
      const index=S.draft.variables.findIndex(v=>v.id===row.id),v=S.draft.variables[index];
      if(!v)return '';
      const number=(key)=>`<input class="inp risk-input" type="number" step="any" data-ch="riskField" data-in="riskField" data-owner="variables" data-index="${index}" data-key="${key}" aria-label="${esc(row.code+' '+key)}" value="${v[key]}">`;
      const dropdown=(key,list)=>`<select class="inp" data-ch="riskField" data-in="riskField" data-owner="variables" data-index="${index}" data-key="${key}" aria-label="${esc(row.code+' '+key)}">${list.map(([k,t])=>`<option value="${k}" ${v[key]===k?'selected':''}>${esc(t)}</option>`).join('')}</select>`;
      return `<tr><td><input type="checkbox" data-ch="riskField" data-in="riskField" data-owner="variables" data-index="${index}" data-key="selected" aria-label="Selecionar ${esc(row.code)}" ${v.selected?'checked':''}></td><td class="risk-description"><b class="code">${esc(row.code)}</b> · <span class="tag">${row.abc}</span><div>${esc(row.description)}</div><small>${money(row.directCents)} · ${esc(row.qty)} ${esc(row.unit)}</small></td><td>${number('probability')}</td><td>${number('min')}</td><td>${number('mode')}</td><td>${number('max')}</td><td>${dropdown('distribution',distributions)}</td><td>${dropdown('responsibility',responsibilities)}</td><td>${dropdown('type',[['variacao_custo_unitario','Custo unitário'],['variacao_quantitativo','Quantitativo']])}</td><td><button class="btn sm" data-act="riskVariableDetails" data-index="${index}">Média / desvio / justificativa</button></td></tr>`;
    }).join('')}</tbody></table></div><div class="risk-toolbar"><button class="btn sm" data-act="riskPage" data-d="-1" ${S.page<=1?'disabled':''}>Anterior</button><span>Página ${S.page} de ${Math.max(1,Math.ceil(rows.length/40))}</span><button class="btn sm" data-act="riskPage" data-d="1" ${S.page*40>=rows.length?'disabled':''}>Próxima</button></div>`;
  }
  function eventsView() {return `<div class="vh"><h2>Eventos de risco</h2><button class="btn pri" data-act="riskAddEvent">${UI.icon('plus')} Novo evento</button></div><p class="note">Eventos devem ser independentes das variações dos serviços, para evitar dupla contagem. Impactos em R$ sobre o custo direto.</p><div class="tblw"><table class="tbl"><thead><tr><th>Evento</th><th>Probabilidade</th><th>Mínimo / provável / máximo</th><th>Distribuição</th><th>Responsável</th><th></th></tr></thead><tbody>${S.draft.events.map((e,i)=>`<tr><td>${esc(e.description)}</td><td>${U.num(e.probability,2)}%</td><td>${money(e.min*100)} / ${money(e.mode*100)} / ${money(e.max*100)}</td><td>${esc(e.distribution)}</td><td>${esc(e.responsibility)}</td><td><button class="btn sm" data-act="riskEditEvent" data-index="${i}">Editar</button> <button class="btn sm" data-act="riskRemoveEvent" data-index="${i}">Remover do modelo</button></td></tr>`).join('')||'<tr><td colspan="6">Nenhum evento cadastrado.</td></tr>'}</tbody></table></div>`;}
  function chartHistogram(bins) {
    const max=Math.max(1,...bins.map(b=>b.quantidade));
    return `<svg class="risk-chart" viewBox="0 0 680 260" role="img" aria-label="Histograma dos custos simulados"><line x1="35" x2="660" y1="220" y2="220" stroke="currentColor"/>${bins.map((b,i)=>{const h=b.quantidade/max*180;return `<rect x="${35+i*620/bins.length}" y="${220-h}" width="${Math.max(1,620/bins.length-2)}" height="${h}" fill="#2473b5"><title>${money(b.inicio*100)} a ${money(b.fim*100)}: ${b.quantidade} simulações</title></rect>`;}).join('')}<text x="35" y="246" fill="currentColor">${esc(money((bins[0]?.inicio||0)*100))}</text><text x="650" y="246" text-anchor="end" fill="currentColor">${esc(money((bins.at(-1)?.fim||0)*100))}</text></svg>`;
  }
  function curve(points) {
    const lo=points[0]?.valor||0,hi=points.at(-1)?.valor||1;
    const line=points.map((p,i)=>`${i?'L':'M'}${35+(p.valor-lo)/(hi-lo||1)*610},${220-p.percentil*1.8}`).join(' ');
    return `<svg class="risk-chart" viewBox="0 0 680 260" role="img" aria-label="Curva acumulada dos custos"><path d="M35 30V220H650" fill="none" stroke="currentColor"/><path d="${line}" fill="none" stroke="#2473b5" stroke-width="3"/><text x="0" y="38" fill="currentColor">100%</text><text x="5" y="220" fill="currentColor">0%</text><text x="35" y="246" fill="currentColor">${esc(money(lo*100))}</text><text x="650" y="246" text-anchor="end" fill="currentColor">${esc(money(hi*100))}</text></svg>`;
  }
  function results(a) {
    const r=a.result;if(!r)return '<p class="note">Salve o modelo e execute a simulação para ver os resultados.</p>';
    const max=Math.max(1,...r.tornado.map(t=>t.amplitude));
    return `<div class="risk-kpis">${[['Custo direto da fotografia',money(r.baseCents)],['Contingência estimada',money(r.contingencyCents)],['Taxa de risco',pct(r.rate)],['Percentil-alvo P'+a.config.percentile,money(r.targetCents)]].map(([t,v])=>`<div class="card"><small>${t}</small><b>${v}</b></div>`).join('')}</div><p class="risk-legend">${esc(a.config.iterations)} iterações · semente ${esc(a.config.seed)} · ${esc(r.engineVersion)} · ${esc(new Date(r.computedAt).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}))}</p><div class="risk-grid"><div class="panel"><h3>Distribuição dos custos</h3>${chartHistogram(r.summary.histograma)}</div><div class="panel"><h3>Curva acumulada</h3>${curve(r.summary.curva_acumulada)}</div></div><div class="panel"><h3>Diagrama de tornado</h3><p class="note">Sensibilidade entre extremos; ordenação pelo maior impacto absoluto. Mesmos serviços e eventos incluídos no Monte Carlo. Exibindo os 20 maiores impactos.</p><div class="risk-tornado">${r.tornado.slice(0,20).map(t=>`<div class="risk-tornado-row"><span title="${esc(t.nome)}">${esc(t.nome.slice(0,75))}</span><div class="risk-bars"><span><i style="width:${Math.max(0,-t.impacto_minimo)/max*100}%"></i></span><span><i style="width:${Math.max(0,t.impacto_maximo)/max*100}%"></i></span></div><span>${money(t.amplitude*100)}</span></div>`).join('')}</div></div><div class="risk-grid"><div class="panel"><h3>Percentis</h3><table class="tbl sm">${['p50','p80','p90','p95'].map(k=>`<tr><td>${k.toUpperCase()}</td><td class="r">${money(r.summary[k]*100)}</td></tr>`).join('')}</table></div><div class="panel"><h3>Indicadores auxiliares</h3><p>VME: <b>${money(r.expected.contingencia_total*100)}</b></p><p>RMS dos VME: <b>${money(r.expected.contingencia_rms*100)}</b></p><p class="note">RMS é a raiz da média dos quadrados dos VME. Não representa contingência com nível de confiança.</p></div></div>${r.assumptions.map(t=>`<p class="risk-alert">${esc(t)}</p>`).join('')}`;
  }
  function bdiView(a) { return `<h2>Criar BDI com a taxa de risco</h2><p class="note">Aplica ao BDI principal. A configuração anterior ficará registrada na memória desta análise. O BDI diferenciado permanece separado.</p><div class="risk-grid">${choose('Método do BDI','bdiMethod',S.bdiMethod,O.bdiui.MODES,'ui')}${choose('Parcela de risco','applyMode',S.applyMode,[['replace','Substituir risco atual'],['add','Somar ao risco atual']],'ui')}</div><p class="note">Revise primeiro os demais parâmetros no menu BDI. A prévia usa esses parâmetros, inclusive ano e regime tributário.</p><button class="btn pri" data-act="riskBdiPreview" ${!a.result||S.dirty?'disabled':''}>Calcular prévia do BDI</button>${a.applications.length?`<h3>Memória das aplicações</h3><div class="tblw"><table class="tbl"><thead><tr><th>Data</th><th>BDI anterior</th><th>BDI personalizado</th><th>Taxa de risco</th><th>Justificativa</th></tr></thead><tbody>${a.applications.map(p=>`<tr><td>${esc(new Date(p.createdAt).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}))}</td><td>${pct(p.oldBdi)}</td><td>${pct(p.newBdi)}</td><td>${pct(p.rate)}</td><td>${esc(p.reason)}</td></tr>`).join('')}</tbody></table></div>`:''}`; }
  UI.views.risks={render:()=>{
    const a=active();if(a&&a.id!==S.active)select(a);
    const intro=`<div class="vh"><div><h1>Riscos e contingências</h1><p class="muted">Monte Carlo, sensibilidade e BDI · análise local deste orçamento.</p></div><button class="btn pri" data-act="riskNew">${UI.icon('plus')} Nova análise</button></div>`;
    if(!a)return `<div class="risk-page">${intro}<div class="panel"><h2>Crie uma fotografia do orçamento</h2><p>A análise usa custos diretos, quantidades e a referência SICRO da fotografia salva. Modele as variações dos serviços e os eventos, escolha o percentil e confira a contingência antes de criar o BDI personalizado.</p><p class="note">As variáveis são independentes. Riscos atribuídos à Administração ficam excluídos.</p></div>${S.error?`<p class="alertbox">${esc(S.error)}</p>`:''}</div>`;
    const c=S.draft;
    return `<div class="risk-page">${intro}${S.error?`<p class="alertbox" role="alert">${esc(S.error)}</p>`:''}<div class="panel risk-toolbar"><label class="fld"><span>Análise</span><select class="inp" data-ch="riskAnalysis">${analyses().map(x=>`<option value="${x.id}" ${a.id===x.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label><span class="note">Fotografia de ${esc(new Date(a.snapshot.capturedAt||a.createdAt).toLocaleString('pt-BR'))} · ${esc(a.snapshot.uf)} / ${esc(a.snapshot.regime)} · ${money(a.snapshot.baseCents)}</span><span class="tag ${S.dirty?'warn':''}">${S.dirty?'Modelo não salvo':'Modelo salvo'}</span><button class="btn" data-act="riskSave" ${!S.dirty?'disabled':''}>Salvar modelo</button><button class="btn pri" data-act="riskRun">Executar Monte Carlo</button><button class="btn" data-act="riskReport" ${!a.result||S.dirty?'disabled':''}>Relatório</button><button class="btn" data-act="riskCsv" ${!a.result||S.dirty?'disabled':''}>CSV</button></div><div class="risk-tabs">${[['model','Premissas e serviços'],['events','Eventos de risco'],['results','Resultados e tornado'],['bdi','BDI com risco']].map(([k,t])=>`<button class="btn ${S.tab===k?'on':''}" data-act="riskTab" data-tab="${k}">${t}</button>`).join('')}</div><section class="panel">${S.tab==='model'?`<div class="risk-grid">${choose('Escopo de serviços','scope',c.scope,[['A','Classe A'],['AB','Classes A + B'],['ALL','Orçamento completo']])}${field('Iterações (1.000 a 100.000)','iterations',c.iterations)}${field('Semente reproduzível','seed',c.seed)}${field('Percentil-alvo (P50 a P99)','percentile',c.percentile)}${choose('Regime de execução','contract',c.contract,[['global','Preço global'],['preco_unitario','Preço unitário']])}${field('Justificativa para risco de quantitativos','quantityJustification',c.quantityJustification,'text')}${field('Premissas e justificativa do percentil','notes',c.notes,'text')}</div><p class="risk-alert">Base: custo direto completo, sem BDI. Fora do escopo, os serviços ficam fixos. Riscos da Administração são excluídos; em preço unitário, risco de quantitativos exige justificativa.</p>${modeledRows(a)}`:S.tab==='events'?eventsView():S.tab==='results'?results(a):bdiView(a)}</section></div>`;
  }};
  async function operation(task) {
    if(S.busy)return;S.busy=true;S.error='';
    const app=document.getElementById('app');app.inert=true;
    const overlay=document.createElement('div');overlay.id='riskBusy';overlay.setAttribute('role','status');overlay.innerHTML='<div>Processando riscos e contingências…<br><small>Simulação reproduzível em segundo plano; salvando no navegador.</small><progress></progress></div>';document.body.append(overlay);
    try {await C.flush();await task();}
    catch(e){S.error=e.message;UI.toast(e.message,'warn');}
    finally {S.busy=false;app.inert=false;overlay.remove();UI.render();}
  }
  const route=a=>'/orcapro/projects/'+C.wrapper.id+'/risks'+(a?'/'+a.id:'');
  async function post(path,body={},method='POST') {return C.request(path,{method,body:JSON.stringify({...body,expectedVersion:C.wrapper.version})});}
  async function saveDraft() {if(!S.dirty)return;const a=active();const out=await post(route(a),{config:S.draft},'PUT');C.acceptProject(out.project);select(active());}
  function confirmRisk(message) {return new Promise(resolve=>{let answer=false;UI.modal('Confirmar alteração',`<p>${esc(message)}</p><button class="btn" data-act="riskConfirm" data-answer="no">Cancelar</button> <button class="btn pri" data-act="riskConfirm" data-answer="yes">Confirmar</button>`,{onClose:()=>{delete S.confirm;resolve(answer);}});S.confirm=value=>{answer=value;UI.closeModal();};});}
  UI.act.riskConfirm=e=>S.confirm?.(e.dataset.answer==='yes');
  UI.act.riskNew=()=>UI.modal('Nova análise de riscos',`<label class="fld"><span>Nome da análise</span><input class="inp" id="riskName" maxlength="160" value="Análise de riscos ${analyses().length+1}" data-enter="riskCreate"></label><p class="note">Será criada uma fotografia da versão salva do orçamento, com os custos diretos e o contexto SICRO atuais.</p>${S.dirty?'<label><input type="checkbox" id="riskDiscard"> Descartar as alterações não salvas do modelo atual.</label><br>':''}<button class="btn pri" data-act="riskCreate">Criar análise</button>`,{after:()=>UI.$('#riskName').focus()});
  UI.act.riskCreate=()=>{const name=UI.$('#riskName').value.trim();if(!name){UI.toast('Informe o nome da análise.','warn');return;}if(S.dirty&&!UI.$('#riskDiscard').checked){UI.toast('Salve o modelo atual ou confirme o descarte.','warn');return;}UI.closeModal();operation(async()=>{const out=await post(route(),{name});C.acceptProject(out.project);select(analyses().find(a=>a.id===out.riskId));S.tab='model';});};
  UI.act.riskSave=()=>operation(saveDraft);
  UI.act.riskRun=()=>operation(async()=>{await saveDraft();const out=await post(route(active())+'/simulate');C.acceptProject(out.project);select(active());S.tab='results';});
  UI.chg.riskAnalysis=async e=>{const id=e.value;if(S.dirty&&!await confirmRisk('Descartar alterações não salvas?')){UI.render();return;}select(analyses().find(a=>a.id===id));UI.render();};
  UI.act.riskTab=e=>{S.tab=e.dataset.tab;UI.render();};
  UI.chg.riskField=e=>{const {owner,index,key}=e.dataset;if(owner==='ui'){S[key]=e.value;S.preview=null;return;}const obj=owner?S.draft[owner][Number(index)]:S.draft;obj[key]=e.type==='checkbox'?e.checked:e.type==='number'?(e.value.trim()?Number(e.value):null):e.value;S.dirty=true;S.preview=null;const badge=document.querySelector('.risk-toolbar .tag');if(badge){badge.textContent='Modelo não salvo';badge.classList.add('warn');}for(const btn of document.querySelectorAll('[data-act="riskSave"]'))btn.disabled=false;for(const btn of document.querySelectorAll('[data-act="riskReport"],[data-act="riskCsv"],[data-act="riskBdiPreview"]'))btn.disabled=true;};
  UI.inp.riskField=UI.chg.riskField;
  UI.inp.riskSearch=e=>{S.filter=e.value;S.page=1;UI.later('risk-filter',()=>UI.render(),180);};
  UI.act.riskPage=e=>{S.page+=Number(e.dataset.d);UI.render();};
  UI.act.riskSelectScope=()=>{const a=active();for(const v of S.draft.variables){const row=a.snapshot.rows.find(r=>r.id===v.id);v.selected=S.draft.scope==='ALL'||row.abc==='A'||(S.draft.scope==='AB'&&row.abc==='B');}S.dirty=true;UI.render();};
  UI.act.riskSelectNone=()=>{S.draft.variables.forEach(v=>v.selected=false);S.dirty=true;UI.render();};
  UI.act.riskVariableDetails=e=>{const i=Number(e.dataset.index),v=S.draft.variables[i];UI.modal('Parâmetros da distribuição',`<div class="risk-grid">${field('Média (%)','mean',v.mean,'number','variables',i)}${field('Desvio padrão (%)','sd',v.sd,'number','variables',i)}${field('Justificativa da variável','justification',v.justification,'text','variables',i)}</div><p class="note">Média e desvio são usados pela normal truncada e pela lognormal. Para lognormal, mínimo/provável/máximo não são limites de truncamento.</p><button class="btn pri" data-act="riskClose">Voltar ao modelo</button>`,{wide:true});};
  UI.act.riskClose=()=>{UI.closeModal();UI.render();};
  function editEvent(i) {const e=S.draft.events[i];UI.modal('Evento de risco',`<div class="risk-grid">${field('Descrição','description',e.description,'text','events',i)}${field('Probabilidade (%)','probability',e.probability,'number','events',i)}${field('Impacto mínimo (R$)','min',e.min,'number','events',i)}${field('Impacto provável (R$)','mode',e.mode,'number','events',i)}${field('Impacto máximo (R$)','max',e.max,'number','events',i)}${choose('Distribuição','distribution',e.distribution,distributions,'events',i)}${choose('Responsável','responsibility',e.responsibility,responsibilities,'events',i)}${field('Média (R$)','mean',e.mean,'number','events',i)}${field('Desvio padrão (R$)','sd',e.sd,'number','events',i)}${field('Justificativa / mitigação','justification',e.justification,'text','events',i)}</div><button class="btn pri" data-act="riskClose">Voltar ao modelo</button>`,{wide:true});}
  UI.act.riskAddEvent=()=>{S.draft.events.push({id:U.uid('event'),description:'Novo evento',probability:20,min:0,mode:1000,max:5000,mean:1000,sd:500,distribution:'triangular',responsibility:'contratado',justification:''});S.dirty=true;editEvent(S.draft.events.length-1);};
  UI.act.riskEditEvent=e=>editEvent(Number(e.dataset.index));
  UI.act.riskRemoveEvent=async e=>{const i=Number(e.dataset.index);if(await confirmRisk('Remover este evento do modelo? As versões já salvas permanecem no histórico.')){S.draft.events.splice(i,1);S.dirty=true;UI.render();}};
  function bdiBody() {return {method:S.bdiMethod,mode:S.applyMode,confirmDoubleCounting:S.applyMode==='add'};}
  UI.act.riskBdiPreview=async()=>{if(S.applyMode==='add'&&!await confirmRisk('Somar ao risco atual pode contar riscos duas vezes. Confirma que as parcelas são distintas?'))return;operation(async()=>{S.preview=await post(route(active())+'/bdi-preview',bdiBody());const p=S.preview;UI.modal('Prévia — BDI com riscos',`<table class="tbl"><tr><td>Parcela de risco</td><td>${pct(p.oldRisk)} → ${pct(p.newRisk)}</td></tr><tr><td>BDI principal</td><td>${pct(p.oldBdi)} → <b>${pct(p.newBdi)}</b></td></tr><tr><td>Preço total</td><td>${money(p.oldPriceCents)} → <b>${money(p.newPriceCents)}</b></td></tr></table><p class="note">A contingência foi recalculada no motor local. O BDI é recalculado pela fórmula completa; a taxa de risco não é somada diretamente ao BDI final.</p><label class="fld"><span>Justificativa da aplicação</span><textarea class="inp" id="riskBdiReason" maxlength="1000"></textarea></label><button class="btn pri" data-act="riskBdiApply">Confirmar BDI personalizado</button>`,{wide:true});});};
  UI.act.riskBdiApply=()=>{const reason=UI.$('#riskBdiReason')?.value?.trim();if(!reason){UI.toast('Informe a justificativa.','warn');return;}const body={...bdiBody(),reason};UI.closeModal();operation(async()=>{const out=await post(route(active())+'/bdi-apply',body);C.acceptProject(out.project);select(active());S.tab='bdi';UI.toast('BDI personalizado aplicado; configuração anterior preservada.');});};
  function premises(a) {
    const rows=new Map(a.snapshot.rows.map(r=>[r.id,r]));
    const variables=a.config.variables.map(v=>{const r=rows.get(v.id);return [r?.code,r?.description,v.selected?'Sim':'Não',v.probability,v.min,v.mode,v.max,v.distribution,v.mean,v.sd,v.responsibility,v.type,v.justification];});
    const events=a.config.events.map(v=>[v.description,v.probability,v.min,v.mode,v.max,v.distribution,v.mean,v.sd,v.responsibility,v.justification]);
    return {variables,events};
  }
  function reportTable(head,rows) {return `<div style="overflow:auto"><table><thead><tr>${head.map(v=>`<th>${esc(v)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(v=>`<td>${esc(v??'')}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
  const variableHead=['Código','Serviço','Selecionado','Probabilidade %','Mínimo %','Provável %','Máximo %','Distribuição','Média %','Desvio %','Responsável','Tipo','Justificativa'];
  const eventHead=['Evento','Probabilidade %','Mínimo R$','Provável R$','Máximo R$','Distribuição','Média R$','Desvio R$','Responsável','Mitigação'];
  UI.act.riskCsv=()=>{
    const a=active(),r=a.result,p=premises(a),lines=[['Análise',a.name],['Versão do motor',r.engineVersion],['Versão de origem',a.snapshot.projectVersion],['Referência',a.snapshot.referenceId],['UF',a.snapshot.uf],['Regime',a.snapshot.regime],['Semente',a.config.seed],['Iterações',a.config.iterations],['Percentil',a.config.percentile],['Custo direto R$',Number(r.baseCents)/100],['Contingência R$',Number(r.contingencyCents)/100],['Taxa %',Number(r.rate)*100],[],variableHead,...p.variables,[],eventHead,...p.events,[],['Variável','Mínimo R$','Máximo R$','Maior impacto R$'],...r.tornado.map(t=>[t.nome,t.impacto_minimo,t.impacto_maximo,t.amplitude])];
    const cell=v=>{let s=String(v??'');if(typeof v==='string'&&/^\s*[=+@-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};
    O.exp.download('OrcaPro_Infraestrutura_Riscos.csv','\ufeff'+lines.map(row=>row.map(cell).join(';')).join('\r\n'),'text/csv;charset=utf-8');
  };
  UI.act.riskReport=()=>{const a=active(),p=premises(a);O.exp.download('OrcaPro_Infraestrutura_Riscos_Relatorio.html',`<!doctype html><html lang="pt-BR"><meta charset="utf-8"><title>OrçaPro Infraestrutura — riscos e contingências</title><style>body{font:14px Arial;max-width:1100px;margin:30px auto;color:#18232c}table{border-collapse:collapse;width:100%}td,th{padding:8px;border-bottom:1px solid #ddd}.risk-kpis{display:flex;gap:25px}.risk-kpis .card{display:grid;gap:8px}svg{max-height:260px}.risk-grid{display:flex;gap:20px}.risk-grid>*{flex:1}.risk-tornado-row{display:grid;grid-template-columns:280px 1fr 100px;gap:12px;margin:8px}.risk-bars{display:flex;height:16px}.risk-bars>span{width:50%;display:flex}.risk-bars>span:first-child{justify-content:flex-end}.risk-bars i{display:block;background:#2473b5}.risk-bars>span:first-child i{background:#c7744e}@media print{body{margin:0}.panel{break-inside:avoid}table{font-size:9px}}</style><h1>Riscos e contingências — ${esc(a.name)}</h1><p>Orçamento: ${esc(A.pj.name)} · versão de origem ${a.snapshot.projectVersion} · referência ${esc(a.snapshot.referenceId)} · ${esc(a.snapshot.uf)} / ${esc(a.snapshot.regime)}</p><h2>Premissas</h2><p>${esc(a.config.notes)}</p><p>Escopo ${esc(a.config.scope)} · regime ${esc(a.config.contract)} · justificativa de quantitativos: ${esc(a.config.quantityJustification)}</p>${results(a)}<h2>Serviços e distribuições</h2>${reportTable(variableHead,p.variables)}<h2>Eventos</h2>${reportTable(eventHead,p.events)}<h2>Memória das aplicações ao BDI</h2>${reportTable(['Data','Método','Modo','Risco anterior','Risco novo','BDI anterior','BDI novo','Preço anterior','Preço novo','Justificativa'],a.applications.map(x=>[x.createdAt,x.method,x.mode,pct(x.oldRisk),pct(x.newRisk),pct(x.oldBdi),pct(x.newBdi),money(x.oldPriceCents),money(x.newPriceCents),x.reason]))}<p>Relatório exportado da análise salva. Para PDF, abra este arquivo e use Imprimir → Salvar como PDF.</p></html>`,'text/html');};
};

window.installOrcaProRisks();
(function(){
 const O=window.OP,S=O.risks,UI=O.ui,A=O.app;
 const riskRender=UI.views.risks.render;
 UI.views.risks.render=function(){const body=riskRender();const a=A.pj.risks?.analyses?.find(x=>x.id===S.active);if(!a?.history?.length)return body;return body+`<details class="panel" style="margin-top:16px"><summary>Histórico do modelo e dos resultados — ${a.history.length} versões anteriores</summary><p class="note">Versões preservadas no projeto JSON. A fotografia permanece vinculada à análise.</p><div class="tblw"><table class="tbl sm"><thead><tr><th>Data</th><th>Origem</th><th>Escopo</th><th>Semente</th><th>Iterações</th><th>Contingência</th></tr></thead><tbody>${a.history.map(h=>`<tr><td>${O.util.esc(new Date(h.at).toLocaleString('pt-BR'))}</td><td>${O.util.esc(h.kind)}</td><td>${O.util.esc(h.config.scope)}</td><td>${O.util.esc(h.config.seed)}</td><td>${O.util.esc(h.config.iterations)}</td><td>${h.result?O.util.brl(Number(h.result.contingencyCents)/100):'Sem simulação'}</td></tr>`).join('')}</tbody></table></div></details>`;};
 const open=O.main.openProject;
 O.main.openProject=function(p){if(S.dirty&&!confirm('Descartar as alterações não salvas do modelo de riscos e abrir outro orçamento?'))return;S.active=null;S.draft=null;S.dirty=false;S.preview=null;S.error='';return open(p);};
 document.addEventListener('keydown',e=>{if(S.busy){e.preventDefault();e.stopImmediatePropagation();}},true);
 const manual=UI.views.manual.render;
 UI.views.manual.render=function(){return manual.call(this)+`<section class="panel" style="margin:20px 0"><h2>Riscos e contingências</h2><p>Crie uma fotografia do orçamento no menu Riscos e contingências. Ela inclui os custos diretos efetivamente adotados, inclusive transportes (DMT/FIT), FIC, mobilização, canteiro, administração local e composições próprias presentes nas linhas do orçamento.</p><ol><li>Nomeie a análise e escolha Classe A, A+B ou orçamento completo. Fora do escopo os serviços permanecem fixos; a base é sempre o custo direto completo.</li><li>Revise as hipóteses: seleção, probabilidade, mínimo, provável, máximo, distribuição, responsabilidade e tipo. Variações dos serviços são percentuais; impactos de eventos são valores em reais.</li><li>Use a justificativa de quantitativos quando o contrato for por preço unitário. Riscos da Administração são excluídos.</li><li>Salve o modelo e execute Monte Carlo. A semente permite reprodução. Confira o histograma, curva acumulada, percentis, tornado e premissas.</li><li>A contingência é máx(0, percentil − custo direto); a taxa é contingência ÷ custo direto. VME e RMS são indicadores auxiliares.</li><li>Em BDI com risco, selecione Paramétrico, Exato ou Simples Nacional, calcule a prévia, confira preço anterior/novo e informe a justificativa. Por padrão substitua a parcela R: não some a taxa diretamente ao BDI final.</li><li>Para somar R, confirme que as parcelas são distintas. O BDI diferenciado permanece separado, e os parâmetros anteriores ficam registrados na memória.</li><li>Se custos, quantidades ou referência mudarem, crie nova análise para aplicar ao BDI. A antiga pode continuar sendo simulada sobre sua fotografia.</li><li>Exporte relatório HTML imprimível/PDF, CSV e projeto JSON. As análises são salvas no IndexedDB do navegador, junto do projeto, e acompanham o JSON.</li></ol><p>Distribuições: triangular, PERT beta, uniforme, normal truncada, lognormal e fixa. Lognormal usa média/desvio aritméticos; extremos do tornado não truncam a amostragem. Variáveis independentes, sem correlação. A análise trata de custos, não de Monte Carlo das durações.</p><button class="btn pri" data-act="go" data-v="risks">Abrir Riscos e contingências</button></section>`;};
})();
