'use client';

import { Activity, BarChart3, Download, PlayCircle, Target, TrendingDown, TrendingUp } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { EmptyState } from '@/components/empty-state'; import { LoadingPanel } from '@/components/loading';
import { apiFetch, apiFileUrl, ApiError } from '@/lib/api';

type Indicator={code:string;name:string;category:string;unit:string;direction:string;targetValue?:string|null;current?:{value:string;periodStart:string;periodEnd:string}|null;previous?:{value:string}|null;delta?:string|null};
function monthRange(){const now=new Date();return{start:new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1)).toISOString(),end:new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()+1,1)).toISOString()}}
export default function IndicatorsPage(){const [items,setItems]=useState<Indicator[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const load=useCallback(()=>apiFetch<Indicator[]>('/kpis/executive').then(setItems).catch((e:Error)=>setError(e.message)).finally(()=>setLoading(false)),[]);useEffect(()=>{void load()},[load]);
 async function calculate(){setBusy(true);setError('');try{await apiFetch('/kpis/definitions/defaults',{method:'POST'});await apiFetch('/kpis/calculate',{method:'POST',body:JSON.stringify({periodStart:monthRange().start,periodEnd:monthRange().end})});setLoading(true);await load()}catch(e){setError(e instanceof ApiError?e.message:'Falha ao calcular indicadores.')}finally{setBusy(false)}}
 return <div className="page-container"><header className="page-header"><div className="page-title"><h1>KPIs, SLAs e relatórios gerenciais</h1><p>Indicadores versionados, tendências e evidência da fórmula usada em cada competência.</p></div><div className="actions"><a className="btn btn-secondary" href={apiFileUrl('/kpis/exports/executive.csv')}><Download size={16}/>CSV</a><a className="btn btn-secondary" href={apiFileUrl('/kpis/exports/executive.pdf')} target="_blank" rel="noreferrer"><Download size={16}/>PDF</a><button className="btn btn-primary" disabled={busy} onClick={()=>void calculate()}><PlayCircle size={16}/>{busy?'Calculando…':'Calcular mês atual'}</button></div></header>{error?<div className="notice error" style={{marginBottom:18}}>{error}</div>:null}
 {loading?<LoadingPanel/>:items.some(i=>i.current)?<div className="grid-kpis">{items.map(item=>{const value=item.current?Number(item.current.value):null;const delta=item.delta?Number(item.delta):null;const good=delta===null?null:item.direction==='LOWER_IS_BETTER'?delta<=0:delta>=0;return <section className={`card kpi-card ${good===false?'warning':good===true?'success':''}`} key={item.code}><div className="kpi-head"><div className="kpi-icon">{item.category==='SLA'?<Target size={20}/>:item.category==='FINANCIAL'?<BarChart3 size={20}/>:<Activity size={20}/>}</div><span className="badge info">{item.category}</span></div><div className="kpi-label">{item.name}</div><div className="kpi-value">{value===null?'—':value.toLocaleString('pt-BR',{maximumFractionDigits:2})} <small>{item.unit}</small></div><div className="kpi-note">Meta: {item.targetValue??'—'} {item.unit} · {delta===null?'sem comparação':<>{delta>=0?<TrendingUp size={13}/>:<TrendingDown size={13}/>} {delta.toLocaleString('pt-BR',{maximumFractionDigits:2})}</>}</div></section>})}</div>:<EmptyState icon={BarChart3} title="Indicadores ainda não calculados" description="Execute o cálculo do mês atual para formar a primeira linha de base."/>}
 <div className="notice" style={{marginTop:18}}><Target size={17}/> Cálculos repetidos para o mesmo escopo e período são idempotentes; a chave inclui a versão da fórmula.</div></div>}
