'use client';

import { ClipboardCheck, Pencil, PlayCircle, Save, Trash2, X } from 'lucide-react';
import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { EmptyState } from '@/components/empty-state';
import { LoadingPanel } from '@/components/loading';
import { StatusBadge } from '@/components/badge';
import { apiFetch, ApiError } from '@/lib/api';
import { BRL } from '@/lib/format';
import type { Contract, WorkOrder } from '@/lib/types';

type Commitment={id:string;number:string;fiscalYear:number;contract:{id:string}};
type Measurement={id:string;number:string;referenceMonth:string;status:string;grossAmount:string;deductions:string;performanceDeductions:string;bonuses:string;performanceIndex?:string|null;netAmount:string;version:number;contract:{id:string;code:string;object:string};commitment?:{id:string;number:string}|null;_count:{items:number}};
const NEXT:Record<string,string[]>= {DRAFT:['SUBMITTED','CANCELED'],SUBMITTED:['UNDER_REVIEW','CANCELED'],UNDER_REVIEW:['APPROVED','REJECTED'],APPROVED:['LIQUIDATED'],REJECTED:['DRAFT'],LIQUIDATED:['PAID']};
const LABEL:Record<string,string>={SUBMITTED:'Enviar',UNDER_REVIEW:'Iniciar análise',APPROVED:'Aprovar',REJECTED:'Rejeitar',LIQUIDATED:'Liquidar',PAID:'Pagar',DRAFT:'Reabrir rascunho',CANCELED:'Cancelar'};

export default function MeasurementsPage(){
 const [items,setItems]=useState<Measurement[]>([]); const [contracts,setContracts]=useState<Contract[]>([]); const [commitments,setCommitments]=useState<Commitment[]>([]); const [orders,setOrders]=useState<WorkOrder[]>([]);
 const [form,setForm]=useState({contractId:'',commitmentId:'',number:'',referenceMonth:new Date().toISOString().slice(0,7),notes:''}); const [selected,setSelected]=useState<Record<string,string>>({}); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 const [editing,setEditing]=useState<Measurement|null>(null); const [editForm,setEditForm]=useState({commitmentId:'',number:'',referenceMonth:'',notes:''});
 const load=useCallback(()=>Promise.all([apiFetch<Measurement[]>('/finance/measurements'),apiFetch<Contract[]>('/contracts'),apiFetch<Commitment[]>('/finance/commitments'),apiFetch<{items:WorkOrder[]}>('/work-orders?status=CLOSED&pageSize=100'),apiFetch<{items:WorkOrder[]}>('/work-orders?status=COMPLETED&pageSize=100')]).then(([m,c,e,closed,completed])=>{setItems(m);setContracts(c);setCommitments(e);setOrders([...closed.items,...completed.items]);setForm(v=>({...v,contractId:v.contractId||c[0]?.id||''}));}).catch((e:Error)=>setError(e.message)).finally(()=>setLoading(false)),[]);
 useEffect(()=>{void load()},[load]);
 const eligible=useMemo(()=>orders.filter(o=>o.measurementEligible&&o.contracts.some(link=>link.contract.id===form.contractId)),[orders,form.contractId]);
 function toggle(order:WorkOrder){setSelected(current=>{const copy={...current}; if(copy[order.id]!==undefined) delete copy[order.id]; else copy[order.id]=String(order.finalCost??''); return copy;});}
 async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{const lines=Object.entries(selected).map(([workOrderId,amount])=>({workOrderId,amount:Number(amount)}));await apiFetch('/finance/measurements',{method:'POST',body:JSON.stringify({...form,commitmentId:form.commitmentId||undefined,notes:form.notes||undefined,items:lines})});setSelected({});setForm({...form,number:'',notes:''});setLoading(true);await load();}catch(e){setError(e instanceof ApiError?e.message:'Falha ao criar medição.')}finally{setBusy(false)}}
 async function consolidate(){setBusy(true);setError('');try{await apiFetch('/finance/measurements/consolidate-final-budgets',{method:'POST',body:JSON.stringify({...form,commitmentId:form.commitmentId||undefined,notes:form.notes||undefined})});setSelected({});setForm({...form,number:'',notes:''});setLoading(true);await load();}catch(e){setError(e instanceof ApiError?e.message:'Falha ao consolidar orçamentos finais.')}finally{setBusy(false)}}
 async function transition(item:Measurement,status:string){let note:string|undefined;if(['REJECTED','CANCELED'].includes(status)){note=window.prompt('Justificativa obrigatória:')?.trim();if(!note)return;}setBusy(true);setError('');try{await apiFetch(`/finance/measurements/${item.id}/transitions`,{method:'POST',body:JSON.stringify({status,version:item.version,note})});setLoading(true);await load();}catch(e){setError(e instanceof ApiError?e.message:'Falha na transição.')}finally{setBusy(false)}}
 function beginEdit(item:Measurement){setEditing(item);setEditForm({commitmentId:item.commitment?.id??'',number:item.number,referenceMonth:item.referenceMonth,notes:''});window.scrollTo({top:0,behavior:'smooth'})}
 async function saveEdit(event:FormEvent){event.preventDefault();if(!editing)return;setBusy(true);setError('');try{await apiFetch(`/finance/measurements/${editing.id}`,{method:'PATCH',body:JSON.stringify({...editForm,commitmentId:editForm.commitmentId||undefined,notes:editForm.notes||undefined})});setEditing(null);setLoading(true);await load()}catch(e){setError(e instanceof ApiError?e.message:'Falha ao editar medição.')}finally{setBusy(false)}}
 async function archive(item:Measurement){if(!window.confirm(`Excluir a medição ${item.number}? Somente boletins ainda não aprovados podem ser arquivados.`))return;setBusy(true);setError('');try{await apiFetch(`/finance/measurements/${item.id}`,{method:'DELETE'});await load()}catch(e){setError(e instanceof ApiError?e.message:'Falha ao excluir medição.')}finally{setBusy(false)}}
 return <div className="page-container"><header className="page-header"><div className="page-title"><h1>Medições</h1><p>Boletins por contrato, com OS concluídas, IGD e reflexos financeiros dos KPIs.</p></div></header>{error?<div className="notice error" style={{marginBottom:18}}>{error}</div>:null}
 {editing?<form className="card form-card" onSubmit={saveEdit} style={{marginBottom:18}}><div className="card-header"><div><h2>Editar medição {editing.number}</h2><p>Disponível para rascunhos e medições rejeitadas.</p></div><button className="btn btn-ghost" type="button" onClick={()=>setEditing(null)}><X size={15}/>Fechar</button></div><div className="card-body"><div className="form-grid"><F c="col-3" l="Número"><input className="input" required value={editForm.number} onChange={e=>setEditForm({...editForm,number:e.target.value})}/></F><F c="col-3" l="Competência"><input className="input" type="month" required value={editForm.referenceMonth} onChange={e=>setEditForm({...editForm,referenceMonth:e.target.value})}/></F><F c="col-3" l="Empenho"><select className="select" value={editForm.commitmentId} onChange={e=>setEditForm({...editForm,commitmentId:e.target.value})}><option value="">Sem vínculo</option>{commitments.filter(c=>c.contract.id===editing.contract.id).map(c=><option key={c.id} value={c.id}>{c.number}/{c.fiscalYear}</option>)}</select></F><F c="col-3" l="Observações"><input className="input" value={editForm.notes} onChange={e=>setEditForm({...editForm,notes:e.target.value})}/></F></div><div className="actions" style={{marginTop:16}}><button className="btn btn-primary" disabled={busy}><Save size={15}/>Salvar alterações</button></div></div></form>:null}
 <form className="card form-card" onSubmit={submit} style={{marginBottom:18}}><div className="card-header"><div><h2>Novo boletim de medição</h2><p>Após a consolidação, a API calcula automaticamente os KPIs configurados, glosas, bônus e valor líquido.</p></div><ClipboardCheck size={19}/></div><div className="card-body"><div className="form-grid"><F c="col-5" l="Contrato"><select className="select" required value={form.contractId} onChange={e=>{setForm({...form,contractId:e.target.value,commitmentId:''});setSelected({})}}>{contracts.map(c=><option key={c.id} value={c.id}>{c.code} — {c.object}</option>)}</select></F><F c="col-3" l="Empenho"><select className="select" value={form.commitmentId} onChange={e=>setForm({...form,commitmentId:e.target.value})}><option value="">Sem vínculo</option>{commitments.filter(c=>c.contract.id===form.contractId).map(c=><option key={c.id} value={c.id}>{c.number}/{c.fiscalYear}</option>)}</select></F><F c="col-2" l="Número"><input className="input" required value={form.number} onChange={e=>setForm({...form,number:e.target.value})}/></F><F c="col-2" l="Competência"><input className="input" type="month" required value={form.referenceMonth} onChange={e=>setForm({...form,referenceMonth:e.target.value})}/></F><div className="field col-12"><label>OS elegíveis</label><div className="table-wrapper"><table className="data-table"><thead><tr><th></th><th>OS</th><th>Serviço</th><th>Valor medido</th></tr></thead><tbody>{eligible.map(o=><tr key={o.id}><td><input type="checkbox" checked={selected[o.id]!==undefined} onChange={()=>toggle(o)}/></td><td>{o.number}</td><td>{o.title}</td><td><input className="input" style={{maxWidth:160}} type="number" min="0.01" step="0.01" disabled={selected[o.id]===undefined} value={selected[o.id]??''} onChange={e=>setSelected({...selected,[o.id]:e.target.value})}/></td></tr>)}</tbody></table></div></div></div><div className="actions" style={{marginTop:16}}><button className="btn btn-secondary" type="button" disabled={busy||!form.contractId||!form.number} onClick={()=>void consolidate()}><ClipboardCheck size={15}/>Consolidar finais do mês</button><button className="btn btn-primary" disabled={busy||!Object.keys(selected).length}>Criar medição manual</button></div></div></form>
 {loading?<LoadingPanel/>:<section className="card table-card">{items.length?<div className="table-wrapper"><table className="data-table"><thead><tr><th>Boletim</th><th>Contrato</th><th>Status</th><th>Itens</th><th>Bruto</th><th>IGD</th><th>Glosa KPI</th><th>Bônus</th><th>Líquido</th><th>Ações</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td><span className="table-primary">{i.number}</span><span className="table-secondary">{i.referenceMonth}{i.commitment?` · ${i.commitment.number}`:''}</span></td><td>{i.contract.code}</td><td><StatusBadge value={i.status}/></td><td>{i._count.items}</td><td>{BRL.format(Number(i.grossAmount))}</td><td><span className={`badge ${Number(i.performanceIndex??0)>=85?'success':Number(i.performanceIndex??0)>=70?'warning':'danger'}`}>{i.performanceIndex?Number(i.performanceIndex).toLocaleString('pt-BR',{maximumFractionDigits:2}):'—'}</span></td><td>{BRL.format(Number(i.performanceDeductions??0))}</td><td>{BRL.format(Number(i.bonuses??0))}</td><td><strong>{BRL.format(Number(i.netAmount))}</strong><span className="table-secondary">Deduções totais {BRL.format(Number(i.deductions))}</span></td><td><div className="actions">{['DRAFT','REJECTED'].includes(i.status)?<button className="btn btn-secondary" type="button" onClick={()=>beginEdit(i)}><Pencil size={14}/>Editar</button>:null}{['DRAFT','SUBMITTED','UNDER_REVIEW','REJECTED'].includes(i.status)?<button className="btn btn-secondary danger-text" type="button" onClick={()=>void archive(i)}><Trash2 size={14}/>Excluir</button>:null}{(NEXT[i.status]??[]).map(status=><button className={status==='APPROVED'||status==='PAID'?'btn btn-primary':'btn btn-secondary'} type="button" disabled={busy} key={status} onClick={()=>void transition(i,status)}><PlayCircle size={14}/>{LABEL[status]}</button>)}</div></td></tr>)}</tbody></table></div>:<EmptyState icon={ClipboardCheck} title="Nenhuma medição" description="Crie o primeiro boletim a partir de OS concluídas."/>}</section>}</div>
}
function F({c,l,children}:{c:string;l:string;children:React.ReactNode}){return <div className={`field ${c}`}><label>{l}</label>{children}</div>}
