'use client';

import { Calculator, Database, Plus, Send } from 'lucide-react';
import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { EmptyState } from '@/components/empty-state'; import { LoadingPanel } from '@/components/loading'; import { StatusBadge } from '@/components/badge';
import { apiFetch, ApiError } from '@/lib/api'; import { BRL } from '@/lib/format'; import type { WorkOrder } from '@/lib/types';

type Catalog={id:string;referenceMonth:string;state:string;version:string;itemCount:number;source:string;priceRegime:'NON_EXEMPT'|'EXEMPT'|'NOT_APPLICABLE';catalogKind:'INPUTS'|'COMPOSITIONS'|'MIXED'}; type CatalogItem={id:string;type:string;code:string;description:string;unit:string;unitCost:string};
type Budget={id:string;status:string;version:number;subtotal:string;bdiPercentage:string;total:string;workOrder:{id:string;number:string;title:string};catalog?:Catalog|null;_count:{items:number;revisions:number}};
const NEXT:Record<string,string[]>={DRAFT:['SUBMITTED','CANCELED'],SUBMITTED:['APPROVED','REJECTED','CANCELED'],REJECTED:['DRAFT','CANCELED']};

export default function BudgetsPage(){const [budgets,setBudgets]=useState<Budget[]>([]);const [catalogs,setCatalogs]=useState<Catalog[]>([]);const [catalogItems,setCatalogItems]=useState<CatalogItem[]>([]);const [orders,setOrders]=useState<WorkOrder[]>([]);const [form,setForm]=useState({workOrderId:'',catalogId:'',bdiPercentage:'0',items:[] as Array<{catalogItemId:string;quantity:string}>});const [importForm,setImport]=useState({sourceType:'SINAPI',referenceMonth:new Date().toISOString().slice(0,7),state:'MG',version:'2026.04'});const [importFile,setImportFile]=useState<File|null>(null);const [importResult,setImportResult]=useState('');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const load=useCallback(()=>Promise.all([apiFetch<Budget[]>('/budgets'),apiFetch<Catalog[]>('/budgets/sinapi/catalogs'),apiFetch<{items:WorkOrder[]}>('/work-orders?pageSize=100')]).then(([b,c,o])=>{setBudgets(b);setCatalogs(c);setOrders(o.items);setForm(v=>({...v,workOrderId:v.workOrderId||o.items[0]?.id||'',catalogId:v.catalogId||c[0]?.id||''}))}).catch((e:Error)=>setError(e.message)).finally(()=>setLoading(false)),[]);useEffect(()=>{void load()},[load]);
 useEffect(()=>{if(!form.catalogId)return;apiFetch<CatalogItem[]>(`/budgets/sinapi/catalogs/${form.catalogId}/items`).then(setCatalogItems).catch((e:Error)=>setError(e.message))},[form.catalogId]);
 const total=useMemo(()=>form.items.reduce((sum,line)=>{const i=catalogItems.find(c=>c.id===line.catalogItemId);return sum+Number(line.quantity||0)*Number(i?.unitCost||0)},0)*(1+Number(form.bdiPercentage||0)/100),[form,catalogItems]);
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await apiFetch(`/budgets/work-orders/${form.workOrderId}`,{method:'PUT',body:JSON.stringify({catalogId:form.catalogId||undefined,referenceMonth:catalogs.find(c=>c.id===form.catalogId)?.referenceMonth,state:catalogs.find(c=>c.id===form.catalogId)?.state,bdiPercentage:Number(form.bdiPercentage),items:form.items.map(i=>({catalogItemId:i.catalogItemId,quantity:Number(i.quantity)}))})});setForm({...form,items:[]});setLoading(true);await load()}catch(c){setError(c instanceof ApiError?c.message:'Falha ao salvar orçamento.')}finally{setBusy(false)}}
 async function importCatalog(e:FormEvent){e.preventDefault();if(!importFile){setError('Selecione o arquivo XLSX.');return}setBusy(true);setError('');setImportResult('');try{const body=new FormData();body.set('file',importFile);body.set('sourceType',importForm.sourceType);body.set('state',importForm.state.toUpperCase());body.set('version',importForm.version);if(importForm.sourceType==='CUSTOM')body.set('referenceMonth',importForm.referenceMonth);const result=await apiFetch<{totalItems:number;totalSkipped:number;catalogs:Array<{sheet:string;itemCount:number;priceRegime:string;catalogKind:string}>}>('/budgets/catalogs/import-file',{method:'POST',body});setImportResult(`${result.totalItems.toLocaleString('pt-BR')} itens importados em ${result.catalogs.length} catálogo(s); ${result.totalSkipped.toLocaleString('pt-BR')} linhas sem preço foram ignoradas.`);setLoading(true);await load()}catch(c){setError(c instanceof Error?c.message:'Falha na importação.')}finally{setBusy(false)}}
 async function transition(b:Budget,status:string){let note;if(['REJECTED','CANCELED'].includes(status)){note=window.prompt('Justificativa:')?.trim();if(!note)return}setBusy(true);try{await apiFetch(`/budgets/${b.id}/transitions`,{method:'POST',body:JSON.stringify({status,version:b.version,note})});setLoading(true);await load()}catch(c){setError(c instanceof ApiError?c.message:'Falha na transição.')}finally{setBusy(false)}}
 return <div className="page-container"><header className="page-header"><div className="page-title"><h1>Orçamentos e SINAPI</h1><p>Composições por competência e UF, BDI calculado e revisões imutáveis.</p></div></header>{error?<div className="notice error" style={{marginBottom:18}}>{error}</div>:null}<div className="grid grid-2" style={{marginBottom:18}}>
 <form className="card form-card" onSubmit={save}><div className="card-header"><div><h2>Compor orçamento</h2><p>Custos unitários são obtidos do catálogo selecionado.</p></div><Calculator size={19}/></div><div className="card-body"><div className="form-grid"><F c="col-7" l="Ordem de serviço"><select className="select" required value={form.workOrderId} onChange={e=>setForm({...form,workOrderId:e.target.value})}>{orders.map(o=><option key={o.id} value={o.id}>{o.number} — {o.title}</option>)}</select></F><F c="col-3" l="Catálogo"><select className="select" required value={form.catalogId} onChange={e=>setForm({...form,catalogId:e.target.value,items:[]})}><option value="">Selecione</option>{catalogs.map(c=><option key={c.id} value={c.id}>{c.referenceMonth}/{c.state} v{c.version}</option>)}</select></F><F c="col-2" l="BDI (%)"><input className="input" type="number" min="0" step="0.01" value={form.bdiPercentage} onChange={e=>setForm({...form,bdiPercentage:e.target.value})}/></F><div className="field col-12"><label>Itens</label>{form.items.map((line,index)=><div className="actions" key={index} style={{marginBottom:8}}><select className="select" style={{flex:1}} required value={line.catalogItemId} onChange={e=>setForm({...form,items:form.items.map((x,i)=>i===index?{...x,catalogItemId:e.target.value}:x)})}><option value="">Selecione</option>{catalogItems.map(i=><option key={i.id} value={i.id}>{i.code} — {i.description} ({BRL.format(Number(i.unitCost))}/{i.unit})</option>)}</select><input className="input" style={{width:120}} type="number" min="0.000001" step="0.000001" placeholder="Qtd." required value={line.quantity} onChange={e=>setForm({...form,items:form.items.map((x,i)=>i===index?{...x,quantity:e.target.value}:x)})}/><button className="btn btn-ghost" type="button" onClick={()=>setForm({...form,items:form.items.filter((_,i)=>i!==index)})}>Remover</button></div>)}</div></div><div className="actions" style={{marginTop:16}}><button className="btn btn-secondary" type="button" disabled={!form.catalogId} onClick={()=>setForm({...form,items:[...form.items,{catalogItemId:'',quantity:'1'}]})}><Plus size={15}/>Adicionar item</button><button className="btn btn-primary" disabled={busy||!form.items.length}>Salvar {BRL.format(total)}</button></div></div></form>
 <form className="card form-card" onSubmit={importCatalog}><div className="card-header"><div><h2>Importar tabelas de custos</h2><p>Envie o XLSX oficial do SINAPI ou uma tabela própria de manutenção.</p></div><Database size={19}/></div><div className="card-body"><div className="form-grid"><F c="col-4" l="Origem"><select className="select" value={importForm.sourceType} onChange={e=>setImport({...importForm,sourceType:e.target.value})}><option value="SINAPI">SINAPI oficial</option><option value="CUSTOM">Tabela própria</option></select></F><F c="col-2" l="UF"><input className="input" maxLength={2} required value={importForm.state} onChange={e=>setImport({...importForm,state:e.target.value.toUpperCase()})}/></F><F c="col-3" l="Versão"><input className="input" required value={importForm.version} onChange={e=>setImport({...importForm,version:e.target.value})}/></F>{importForm.sourceType==='CUSTOM'?<F c="col-3" l="Competência"><input className="input" type="month" required value={importForm.referenceMonth} onChange={e=>setImport({...importForm,referenceMonth:e.target.value})}/></F>:null}<F c="col-12" l="Arquivo XLSX *"><input className="input" type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" required onChange={e=>setImportFile(e.target.files?.[0]??null)}/></F></div><div className="notice">No SINAPI, o sistema importa automaticamente insumos e composições sintéticas, com e sem desoneração, apenas para a UF escolhida. As abas analíticas não são importadas.</div>{importForm.sourceType==='CUSTOM'?<div className="notice" style={{marginTop:10}}>Tabela própria: use as colunas Código, Descrição, Unidade, Custo Unitário e, opcionalmente, Tipo.</div>:null}{importResult?<div className="notice success" style={{marginTop:10}}>{importResult}</div>:null}<div className="actions" style={{marginTop:16}}><button className="btn btn-primary" disabled={busy||!importFile}>{busy?'Importando…':'Importar XLSX'}</button></div></div></form></div>
 {loading?<LoadingPanel/>:<section className="card table-card">{budgets.length?<div className="table-wrapper"><table className="data-table"><thead><tr><th>OS</th><th>Status</th><th>Versão</th><th>Itens</th><th>Subtotal</th><th>BDI</th><th>Total</th><th>Ações</th></tr></thead><tbody>{budgets.map(b=><tr key={b.id}><td><span className="table-primary">{b.workOrder.number}</span><span className="table-secondary">{b.workOrder.title}</span></td><td><StatusBadge value={b.status}/></td><td>v{b.version}</td><td>{b._count.items}</td><td>{BRL.format(Number(b.subtotal))}</td><td>{(Number(b.bdiPercentage)*100).toFixed(2)}%</td><td>{BRL.format(Number(b.total))}</td><td><div className="actions">{(NEXT[b.status]??[]).map(s=><button key={s} type="button" className={s==='APPROVED'?'btn btn-primary':'btn btn-secondary'} disabled={busy} onClick={()=>void transition(b,s)}><Send size={14}/>{s}</button>)}</div></td></tr>)}</tbody></table></div>:<EmptyState icon={Calculator} title="Nenhum orçamento" description="Importe uma base SINAPI e componha o custo de uma OS."/>}</section>}</div>}
function F({c,l,children}:{c:string;l:string;children:React.ReactNode}){return <div className={`field ${c}`}><label>{l}</label>{children}</div>}
