-- v0.16.0: gestão e fiscalização do ciclo contratual.
ALTER TABLE `Contract`
  ADD COLUMN `executionRegime` ENUM('UNIT_PRICE', 'GLOBAL_PRICE', 'TASK', 'INTEGRAL', 'INTEGRATED', 'SEMI_INTEGRATED', 'SUPPLY_AND_ASSOCIATED_SERVICE') NULL DEFAULT 'GLOBAL_PRICE',
  ADD COLUMN `nature` ENUM('CONTINUOUS', 'SCOPE') NULL DEFAULT 'CONTINUOUS';

CREATE TABLE `InspectorProfile` (
  `id` CHAR(36) NOT NULL,
  `tenantId` CHAR(36) NOT NULL,
  `userId` CHAR(36) NULL,
  `createdByUserId` CHAR(36) NOT NULL,
  `name` VARCHAR(160) NOT NULL,
  `registrationNumber` VARCHAR(80) NOT NULL,
  `cpf` VARCHAR(14) NULL,
  `jobTitle` VARCHAR(120) NOT NULL,
  `professionalEducation` VARCHAR(120) NULL,
  `professionalCouncil` VARCHAR(80) NULL,
  `department` VARCHAR(160) NULL,
  `phone` VARCHAR(30) NULL,
  `email` VARCHAR(190) NULL,
  `specialty` VARCHAR(160) NOT NULL,
  `status` ENUM('ACTIVE', 'LEAVE', 'SUSPENDED', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  `availableHours` INTEGER NOT NULL DEFAULT 40,
  `maxProcesses` INTEGER NOT NULL DEFAULT 8,
  `baseLatitude` DECIMAL(10, 7) NULL,
  `baseLongitude` DECIMAL(10, 7) NULL,
  `restrictedCompanies` TEXT NULL,
  `designationOrdinance` VARCHAR(220) NULL,
  `notes` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `deletedAt` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `InspectorProfile_tenantId_registrationNumber_key` (`tenantId`, `registrationNumber`),
  INDEX `InspectorProfile_tenant_status_deleted_idx` (`tenantId`, `status`, `deletedAt`),
  INDEX `InspectorProfile_tenant_specialty_status_idx` (`tenantId`, `specialty`, `status`),
  INDEX `InspectorProfile_userId_idx` (`userId`),
  CONSTRAINT `InspectorProfile_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `Tenant`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `InspectorProfile_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `InspectorProfile_createdByUserId_fkey` FOREIGN KEY (`createdByUserId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `ContractInspectionTeamMember` (
  `id` CHAR(36) NOT NULL,
  `tenantId` CHAR(36) NOT NULL,
  `contractId` CHAR(36) NOT NULL,
  `inspectorProfileId` CHAR(36) NOT NULL,
  `assignedByUserId` CHAR(36) NOT NULL,
  `role` ENUM('CONTRACT_MANAGER', 'SUBSTITUTE_MANAGER', 'TECHNICAL_INSPECTOR', 'ADMINISTRATIVE_INSPECTOR', 'SECTORAL_INSPECTOR', 'SUBSTITUTE_INSPECTOR') NOT NULL,
  `designationAct` VARCHAR(220) NOT NULL,
  `startsAt` DATETIME(3) NOT NULL,
  `endsAt` DATETIME(3) NULL,
  `isPrimary` BOOLEAN NOT NULL DEFAULT false,
  `notes` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `deletedAt` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  INDEX `ContractInspectionTeam_tenant_contract_deleted_idx` (`tenantId`, `contractId`, `deletedAt`),
  INDEX `ContractInspectionTeam_inspector_period_idx` (`tenantId`, `inspectorProfileId`, `startsAt`, `endsAt`),
  CONSTRAINT `ContractInspectionTeam_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `Tenant`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `ContractInspectionTeam_contractId_fkey` FOREIGN KEY (`contractId`) REFERENCES `Contract`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `ContractInspectionTeam_inspectorProfileId_fkey` FOREIGN KEY (`inspectorProfileId`) REFERENCES `InspectorProfile`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `ContractInspectionTeam_assignedByUserId_fkey` FOREIGN KEY (`assignedByUserId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `ContractGuarantee` (
  `id` CHAR(36) NOT NULL,
  `tenantId` CHAR(36) NOT NULL,
  `contractId` CHAR(36) NOT NULL,
  `createdByUserId` CHAR(36) NOT NULL,
  `analystUserId` CHAR(36) NULL,
  `analystInspectorId` CHAR(36) NULL,
  `number` VARCHAR(120) NOT NULL,
  `modality` ENUM('CASH_DEPOSIT', 'PUBLIC_DEBT_BONDS', 'SURETY_BOND', 'BANK_GUARANTEE', 'OTHER') NOT NULL,
  `guarantorName` VARCHAR(200) NULL,
  `guarantorTaxId` VARCHAR(24) NULL,
  `contractPercentage` DECIMAL(9, 6) NOT NULL DEFAULT 5,
  `guaranteedValue` DECIMAL(16, 2) NOT NULL,
  `minimumPercentage` DECIMAL(9, 6) NOT NULL DEFAULT 5,
  `issuedAt` DATETIME(3) NULL,
  `startsAt` DATETIME(3) NOT NULL,
  `endsAt` DATETIME(3) NOT NULL,
  `status` ENUM('REQUIRED', 'PRESENTED', 'UNDER_REVIEW', 'APPROVED', 'COMPLEMENT_REQUESTED', 'RENEWAL_REQUESTED', 'REPLACED', 'UNDER_EXECUTION', 'EXECUTED', 'RELEASED', 'EXPIRED') NOT NULL DEFAULT 'PRESENTED',
  `workflow` VARCHAR(120) NOT NULL DEFAULT 'Análise inicial',
  `executionValue` DECIMAL(16, 2) NOT NULL DEFAULT 0,
  `recoveredValue` DECIMAL(16, 2) NOT NULL DEFAULT 0,
  `releasedAt` DATETIME(3) NULL,
  `coverages` TEXT NULL,
  `history` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `deletedAt` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ContractGuarantee_contractId_number_key` (`contractId`, `number`),
  INDEX `ContractGuarantee_tenant_contract_status_idx` (`tenantId`, `contractId`, `status`, `deletedAt`),
  INDEX `ContractGuarantee_tenant_end_status_idx` (`tenantId`, `endsAt`, `status`),
  CONSTRAINT `ContractGuarantee_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `Tenant`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `ContractGuarantee_contractId_fkey` FOREIGN KEY (`contractId`) REFERENCES `Contract`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `ContractGuarantee_createdByUserId_fkey` FOREIGN KEY (`createdByUserId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `ContractGuarantee_analystUserId_fkey` FOREIGN KEY (`analystUserId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `ContractGuarantee_analystInspectorId_fkey` FOREIGN KEY (`analystInspectorId`) REFERENCES `InspectorProfile`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `ContractApostille` (
  `id` CHAR(36) NOT NULL,
  `tenantId` CHAR(36) NOT NULL,
  `contractId` CHAR(36) NOT NULL,
  `createdByUserId` CHAR(36) NOT NULL,
  `number` VARCHAR(80) NOT NULL,
  `type` ENUM('PRICE_ADJUSTMENT', 'REPACTUATION', 'MONETARY_UPDATE', 'BUDGET_ALLOCATION_CHANGE', 'FUNDING_SOURCE_CHANGE', 'REGISTRATION_CORRECTION', 'OTHER_LEGAL_BASIS') NOT NULL,
  `date` DATETIME(3) NOT NULL,
  `indexName` VARCHAR(100) NULL,
  `percentage` DECIMAL(9, 6) NULL,
  `valueBefore` DECIMAL(16, 2) NOT NULL,
  `valueChange` DECIMAL(16, 2) NOT NULL DEFAULT 0,
  `valueAfter` DECIMAL(16, 2) NOT NULL,
  `calculationMemo` TEXT NULL,
  `justification` TEXT NOT NULL,
  `status` VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `deletedAt` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ContractApostille_contractId_number_key` (`contractId`, `number`),
  INDEX `ContractApostille_tenant_contract_date_idx` (`tenantId`, `contractId`, `date`, `deletedAt`),
  CONSTRAINT `ContractApostille_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `Tenant`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `ContractApostille_contractId_fkey` FOREIGN KEY (`contractId`) REFERENCES `Contract`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `ContractApostille_createdByUserId_fkey` FOREIGN KEY (`createdByUserId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `ContractReceipt` (
  `id` CHAR(36) NOT NULL,
  `tenantId` CHAR(36) NOT NULL,
  `contractId` CHAR(36) NOT NULL,
  `createdByUserId` CHAR(36) NOT NULL,
  `responsibleInspectorId` CHAR(36) NULL,
  `number` VARCHAR(100) NOT NULL,
  `type` ENUM('PROVISIONAL', 'DEFINITIVE', 'PARTIAL', 'BY_STAGE', 'REJECTION') NOT NULL,
  `objectCategory` VARCHAR(120) NOT NULL,
  `requestProtocol` VARCHAR(120) NULL,
  `protocolAt` DATETIME(3) NULL,
  `inspectionDate` DATETIME(3) NULL,
  `status` ENUM('REQUESTED', 'UNDER_REVIEW', 'INSPECTION_SCHEDULED', 'WITH_PENDING_ITEMS', 'AWAITING_CORRECTIONS', 'APPROVED_PROVISIONAL', 'OBSERVATION_PERIOD', 'APPROVED_DEFINITIVE', 'TERM_ISSUED', 'REJECTED', 'CLOSED') NOT NULL DEFAULT 'REQUESTED',
  `provisionalRequired` BOOLEAN NOT NULL DEFAULT true,
  `decision` ENUM('APPROVE', 'APPROVE_WITH_PENDING_ITEMS', 'REJECT', 'SUSPEND_FOR_DILIGENCE') NOT NULL,
  `commissionOrdinance` VARCHAR(500) NULL,
  `quorum` VARCHAR(80) NULL,
  `contractorDocuments` TEXT NULL,
  `inspectionsAndTests` TEXT NULL,
  `observationStartsAt` DATETIME(3) NULL,
  `observationEndsAt` DATETIME(3) NULL,
  `technicalWarrantyEndsAt` DATETIME(3) NULL,
  `occurrences` TEXT NULL,
  `consolidatedOpinion` TEXT NOT NULL,
  `competentAuthority` VARCHAR(180) NULL,
  `pendingItems` JSON NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `deletedAt` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ContractReceipt_contractId_number_key` (`contractId`, `number`),
  INDEX `ContractReceipt_tenant_contract_status_idx` (`tenantId`, `contractId`, `status`, `deletedAt`),
  CONSTRAINT `ContractReceipt_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `Tenant`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `ContractReceipt_contractId_fkey` FOREIGN KEY (`contractId`) REFERENCES `Contract`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `ContractReceipt_createdByUserId_fkey` FOREIGN KEY (`createdByUserId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `ContractReceipt_responsibleInspectorId_fkey` FOREIGN KEY (`responsibleInspectorId`) REFERENCES `InspectorProfile`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `ConstructionDiary` (
  `id` CHAR(36) NOT NULL,
  `tenantId` CHAR(36) NOT NULL,
  `contractId` CHAR(36) NOT NULL,
  `workOrderId` CHAR(36) NULL,
  `createdByUserId` CHAR(36) NOT NULL,
  `responsibleInspectorId` CHAR(36) NULL,
  `number` VARCHAR(100) NOT NULL,
  `date` DATETIME(3) NOT NULL,
  `openedAt` DATETIME(3) NULL,
  `closedAt` DATETIME(3) NULL,
  `operationalSituation` VARCHAR(160) NOT NULL,
  `weather` VARCHAR(80) NULL,
  `temperatureCelsius` DECIMAL(5, 2) NULL,
  `precipitationMm` DECIMAL(8, 2) NULL,
  `status` ENUM('OPEN', 'CLOSED', 'VALIDATED', 'CONTESTED') NOT NULL DEFAULT 'OPEN',
  `workFront` VARCHAR(180) NULL,
  `ownWorkforce` INTEGER NOT NULL DEFAULT 0,
  `outsourcedWorkforce` INTEGER NOT NULL DEFAULT 0,
  `servicesPerformed` TEXT NULL,
  `servicesInProgress` TEXT NULL,
  `servicesCompleted` TEXT NULL,
  `equipmentMobilized` TEXT NULL,
  `equipmentDemobilized` TEXT NULL,
  `materialsReceived` TEXT NULL,
  `testsAndQualityControl` TEXT NULL,
  `occurrencesAndRisks` TEXT NULL,
  `contractualImpact` VARCHAR(160) NULL,
  `formalCommunications` TEXT NULL,
  `inspectionDirections` TEXT NULL,
  `notes` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `deletedAt` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ConstructionDiary_contractId_number_key` (`contractId`, `number`),
  INDEX `ConstructionDiary_tenant_contract_date_idx` (`tenantId`, `contractId`, `date`, `deletedAt`),
  INDEX `ConstructionDiary_workOrderId_idx` (`workOrderId`),
  CONSTRAINT `ConstructionDiary_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `Tenant`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `ConstructionDiary_contractId_fkey` FOREIGN KEY (`contractId`) REFERENCES `Contract`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `ConstructionDiary_workOrderId_fkey` FOREIGN KEY (`workOrderId`) REFERENCES `WorkOrder`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `ConstructionDiary_createdByUserId_fkey` FOREIGN KEY (`createdByUserId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `ConstructionDiary_responsibleInspectorId_fkey` FOREIGN KEY (`responsibleInspectorId`) REFERENCES `InspectorProfile`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `ContractCommunicationClaim` (
  `id` CHAR(36) NOT NULL,
  `tenantId` CHAR(36) NOT NULL,
  `contractId` CHAR(36) NOT NULL,
  `createdByUserId` CHAR(36) NOT NULL,
  `responsibleInspectorId` CHAR(36) NULL,
  `number` VARCHAR(100) NOT NULL,
  `type` VARCHAR(160) NOT NULL,
  `protocolDate` DATETIME(3) NOT NULL,
  `sender` VARCHAR(100) NOT NULL,
  `recipient` VARCHAR(100) NOT NULL,
  `priority` ENUM('LOW', 'NORMAL', 'HIGH', 'URGENT') NOT NULL DEFAULT 'NORMAL',
  `currentStatus` VARCHAR(120) NOT NULL,
  `claimNature` VARCHAR(100) NULL,
  `workflowStage` VARCHAR(120) NOT NULL,
  `instructionStartsAt` DATETIME(3) NULL,
  `instructionEndsAt` DATETIME(3) NULL,
  `standardDecisionDays` INTEGER NOT NULL DEFAULT 30,
  `decisionDeadline` DATETIME(3) NULL,
  `extensionApproved` BOOLEAN NOT NULL DEFAULT false,
  `extensionJustification` TEXT NULL,
  `technicalDeadline` DATETIME(3) NULL,
  `inspectionDeadline` DATETIME(3) NULL,
  `legalDeadline` DATETIME(3) NULL,
  `appealDeadline` DATETIME(3) NULL,
  `subject` VARCHAR(240) NOT NULL,
  `detailedDescription` TEXT NOT NULL,
  `technicalOpinion` TEXT NULL,
  `inspectionOpinion` TEXT NULL,
  `legalOpinion` TEXT NULL,
  `decision` TEXT NULL,
  `forwardedModule` VARCHAR(120) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `deletedAt` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ContractCommunication_contractId_number_key` (`contractId`, `number`),
  INDEX `ContractCommunication_tenant_contract_date_idx` (`tenantId`, `contractId`, `protocolDate`, `deletedAt`),
  INDEX `ContractCommunication_tenant_status_deadline_idx` (`tenantId`, `currentStatus`, `decisionDeadline`),
  CONSTRAINT `ContractCommunication_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `Tenant`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `ContractCommunication_contractId_fkey` FOREIGN KEY (`contractId`) REFERENCES `Contract`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `ContractCommunication_createdByUserId_fkey` FOREIGN KEY (`createdByUserId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `ContractCommunication_responsibleInspectorId_fkey` FOREIGN KEY (`responsibleInspectorId`) REFERENCES `InspectorProfile`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `ContractDossierAttachment` (
  `id` CHAR(36) NOT NULL,
  `tenantId` CHAR(36) NOT NULL,
  `contractId` CHAR(36) NOT NULL,
  `uploadedByUserId` CHAR(36) NOT NULL,
  `entityType` ENUM('CONTRACT', 'GUARANTEE', 'APOSTILLE', 'RECEIPT', 'CONSTRUCTION_DIARY', 'COMMUNICATION_CLAIM') NOT NULL,
  `entityId` CHAR(36) NULL,
  `kind` VARCHAR(80) NOT NULL,
  `storageKey` VARCHAR(500) NOT NULL,
  `fileName` VARCHAR(255) NOT NULL,
  `originalName` VARCHAR(255) NOT NULL,
  `mimeType` VARCHAR(120) NOT NULL,
  `sizeBytes` BIGINT NOT NULL,
  `sha256` CHAR(64) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `deletedAt` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ContractDossierAttachment_storageKey_key` (`storageKey`),
  INDEX `ContractDossierAttachment_entity_idx` (`tenantId`, `contractId`, `entityType`, `entityId`, `deletedAt`),
  CONSTRAINT `ContractDossierAttachment_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `Tenant`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `ContractDossierAttachment_contractId_fkey` FOREIGN KEY (`contractId`) REFERENCES `Contract`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `ContractDossierAttachment_uploadedByUserId_fkey` FOREIGN KEY (`uploadedByUserId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
