-- v0.18.0: orçamento contratual, planilhas de mão de obra e integração com OS.
ALTER TABLE `Contract`
  ADD COLUMN `exclusiveLaborDedication` BOOLEAN NOT NULL DEFAULT false;

CREATE TABLE `ContractBudget` (
  `id` CHAR(36) NOT NULL,
  `tenantId` CHAR(36) NOT NULL,
  `contractId` CHAR(36) NOT NULL,
  `createdByUserId` CHAR(36) NULL,
  `status` ENUM('DRAFT', 'ACTIVE', 'ARCHIVED') NOT NULL DEFAULT 'DRAFT',
  `version` INTEGER NOT NULL DEFAULT 1,
  `title` VARCHAR(180) NULL,
  `referenceMonth` VARCHAR(7) NULL,
  `subtotal` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `bdiAmount` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `total` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `sourceTotal` DECIMAL(18,2) NULL,
  `notes` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `deletedAt` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ContractBudget_contractId_key` (`contractId`),
  INDEX `ContractBudget_tenant_status_deleted_idx` (`tenantId`, `status`, `deletedAt`),
  CONSTRAINT `ContractBudget_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `Tenant`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `ContractBudget_contractId_fkey` FOREIGN KEY (`contractId`) REFERENCES `Contract`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `ContractBudget_createdByUserId_fkey` FOREIGN KEY (`createdByUserId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `ContractBudgetImport` (
  `id` CHAR(36) NOT NULL,
  `tenantId` CHAR(36) NOT NULL,
  `budgetId` CHAR(36) NOT NULL,
  `importedByUserId` CHAR(36) NULL,
  `format` ENUM('XLSX', 'XLSB', 'PDF', 'MANUAL') NOT NULL,
  `originalName` VARCHAR(255) NOT NULL,
  `storageKey` VARCHAR(500) NOT NULL,
  `fileName` VARCHAR(255) NOT NULL,
  `mimeType` VARCHAR(120) NOT NULL,
  `sizeBytes` BIGINT NOT NULL,
  `sha256` CHAR(64) NOT NULL,
  `sheetCount` INTEGER NOT NULL DEFAULT 0,
  `importedItemCount` INTEGER NOT NULL DEFAULT 0,
  `laborPostCount` INTEGER NOT NULL DEFAULT 0,
  `ignoredSheetCount` INTEGER NOT NULL DEFAULT 0,
  `report` JSON NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ContractBudgetImport_storageKey_key` (`storageKey`),
  INDEX `ContractBudgetImport_tenant_budget_created_idx` (`tenantId`, `budgetId`, `createdAt`),
  INDEX `ContractBudgetImport_tenant_sha256_idx` (`tenantId`, `sha256`),
  CONSTRAINT `ContractBudgetImport_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `Tenant`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `ContractBudgetImport_budgetId_fkey` FOREIGN KEY (`budgetId`) REFERENCES `ContractBudget`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `ContractBudgetImport_importedByUserId_fkey` FOREIGN KEY (`importedByUserId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `ContractBudgetSheet` (
  `id` CHAR(36) NOT NULL,
  `tenantId` CHAR(36) NOT NULL,
  `importId` CHAR(36) NOT NULL,
  `name` VARCHAR(160) NOT NULL,
  `orderIndex` INTEGER NOT NULL,
  `rowCount` INTEGER NOT NULL DEFAULT 0,
  `columnCount` INTEGER NOT NULL DEFAULT 0,
  `role` VARCHAR(40) NOT NULL DEFAULT 'AUXILIARY',
  `importedRows` INTEGER NOT NULL DEFAULT 0,
  `ignoredRows` INTEGER NOT NULL DEFAULT 0,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ContractBudgetSheet_importId_name_key` (`importId`, `name`),
  INDEX `ContractBudgetSheet_tenant_role_idx` (`tenantId`, `role`),
  CONSTRAINT `ContractBudgetSheet_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `Tenant`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `ContractBudgetSheet_importId_fkey` FOREIGN KEY (`importId`) REFERENCES `ContractBudgetImport`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `ContractBudgetItem` (
  `id` CHAR(36) NOT NULL,
  `tenantId` CHAR(36) NOT NULL,
  `budgetId` CHAR(36) NOT NULL,
  `importId` CHAR(36) NULL,
  `catalogItemId` CHAR(36) NULL,
  `kind` ENUM('SUPPORT_SERVICE', 'LABOR_POST', 'MATERIAL', 'ON_DEMAND_SERVICE', 'SINAPI_INPUT', 'SINAPI_COMPOSITION', 'OTHER') NOT NULL DEFAULT 'OTHER',
  `source` VARCHAR(40) NOT NULL DEFAULT 'USER',
  `sectionCode` VARCHAR(40) NULL,
  `sectionName` VARCHAR(180) NULL,
  `code` VARCHAR(80) NOT NULL,
  `description` TEXT NOT NULL,
  `technicalReference` VARCHAR(255) NULL,
  `unit` VARCHAR(30) NOT NULL,
  `quantity` DECIMAL(18,6) NOT NULL DEFAULT 1,
  `laborUnitCost` DECIMAL(18,6) NOT NULL DEFAULT 0,
  `materialUnitCost` DECIMAL(18,6) NOT NULL DEFAULT 0,
  `unitCost` DECIMAL(18,6) NOT NULL DEFAULT 0,
  `bdiPercentage` DECIMAL(9,6) NOT NULL DEFAULT 0,
  `totalCost` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `includedInTotal` BOOLEAN NOT NULL DEFAULT true,
  `sourceSheet` VARCHAR(160) NULL,
  `sourceRow` INTEGER NULL,
  `sourceData` JSON NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `deletedAt` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  INDEX `ContractBudgetItem_tenant_budget_kind_deleted_idx` (`tenantId`, `budgetId`, `kind`, `deletedAt`),
  INDEX `ContractBudgetItem_tenant_code_idx` (`tenantId`, `code`),
  INDEX `ContractBudgetItem_tenant_catalog_idx` (`tenantId`, `catalogItemId`),
  INDEX `ContractBudgetItem_import_sheet_row_idx` (`importId`, `sourceSheet`, `sourceRow`),
  CONSTRAINT `ContractBudgetItem_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `Tenant`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `ContractBudgetItem_budgetId_fkey` FOREIGN KEY (`budgetId`) REFERENCES `ContractBudget`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `ContractBudgetItem_importId_fkey` FOREIGN KEY (`importId`) REFERENCES `ContractBudgetImport`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `ContractBudgetItem_catalogItemId_fkey` FOREIGN KEY (`catalogItemId`) REFERENCES `SinapiCatalogItem`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `ContractLaborPost` (
  `id` CHAR(36) NOT NULL,
  `tenantId` CHAR(36) NOT NULL,
  `budgetId` CHAR(36) NOT NULL,
  `importId` CHAR(36) NULL,
  `code` VARCHAR(80) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `unit` VARCHAR(30) NOT NULL DEFAULT 'POSTO',
  `postQuantity` DECIMAL(12,4) NOT NULL DEFAULT 1,
  `employeesPerPost` DECIMAL(12,4) NOT NULL DEFAULT 1,
  `professionalQuantity` DECIMAL(12,4) NOT NULL DEFAULT 1,
  `months` DECIMAL(12,4) NOT NULL DEFAULT 12,
  `cbo` VARCHAR(40) NULL,
  `collectiveAgreement` VARCHAR(180) NULL,
  `mteRegistration` VARCHAR(80) NULL,
  `categoryBaseDate` VARCHAR(60) NULL,
  `shift` VARCHAR(80) NULL,
  `baseSalary` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `monthlyCostBeforeBdi` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `bdiAmount` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `monthlyCost` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `annualCost` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `includedInTotal` BOOLEAN NOT NULL DEFAULT true,
  `sourceSheet` VARCHAR(160) NULL,
  `sourceData` JSON NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `deletedAt` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  INDEX `ContractLaborPost_tenant_budget_deleted_idx` (`tenantId`, `budgetId`, `deletedAt`),
  INDEX `ContractLaborPost_import_sheet_idx` (`importId`, `sourceSheet`),
  CONSTRAINT `ContractLaborPost_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `Tenant`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `ContractLaborPost_budgetId_fkey` FOREIGN KEY (`budgetId`) REFERENCES `ContractBudget`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `ContractLaborPost_importId_fkey` FOREIGN KEY (`importId`) REFERENCES `ContractBudgetImport`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `ContractLaborCostComponent` (
  `id` CHAR(36) NOT NULL,
  `tenantId` CHAR(36) NOT NULL,
  `laborPostId` CHAR(36) NOT NULL,
  `module` VARCHAR(120) NULL,
  `submodule` VARCHAR(120) NULL,
  `code` VARCHAR(40) NULL,
  `description` TEXT NOT NULL,
  `percentage` DECIMAL(12,8) NULL,
  `amount` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `basis` VARCHAR(255) NULL,
  `sourceRow` INTEGER NULL,
  `sortOrder` INTEGER NOT NULL DEFAULT 0,
  `sourceData` JSON NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `ContractLaborComponent_tenant_post_order_idx` (`tenantId`, `laborPostId`, `sortOrder`),
  CONSTRAINT `ContractLaborCostComponent_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `Tenant`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `ContractLaborCostComponent_laborPostId_fkey` FOREIGN KEY (`laborPostId`) REFERENCES `ContractLaborPost`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `ContractBudgetRevision` (
  `id` CHAR(36) NOT NULL,
  `tenantId` CHAR(36) NOT NULL,
  `budgetId` CHAR(36) NOT NULL,
  `createdByUserId` CHAR(36) NULL,
  `version` INTEGER NOT NULL,
  `subtotal` DECIMAL(18,2) NOT NULL,
  `bdiAmount` DECIMAL(18,2) NOT NULL,
  `total` DECIMAL(18,2) NOT NULL,
  `reason` TEXT NULL,
  `snapshot` JSON NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ContractBudgetRevision_budgetId_version_key` (`budgetId`, `version`),
  INDEX `ContractBudgetRevision_tenant_created_idx` (`tenantId`, `createdAt`),
  CONSTRAINT `ContractBudgetRevision_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `Tenant`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `ContractBudgetRevision_budgetId_fkey` FOREIGN KEY (`budgetId`) REFERENCES `ContractBudget`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `ContractBudgetRevision_createdByUserId_fkey` FOREIGN KEY (`createdByUserId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE `BudgetItem`
  ADD COLUMN `contractBudgetItemId` CHAR(36) NULL,
  ADD INDEX `BudgetItem_tenant_contractBudgetItem_idx` (`tenantId`, `contractBudgetItemId`),
  ADD CONSTRAINT `BudgetItem_contractBudgetItemId_fkey` FOREIGN KEY (`contractBudgetItemId`) REFERENCES `ContractBudgetItem`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
