'use client';
import Link from 'next/link';
import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { ApiError } from '@/lib/api';
import { infraAccess, infraApi, infraDownload, infraItems, type InfraCycle, type InfraProject } from '@/lib/infra-api';
import { ORCAPRO_ONLY } from '@/lib/product-config';
import InfraShell from '../infra-shell';
import styles from '../../orcapro/workspace.module.css';

type Version = { version: number; createdAt?: string };
type Migration = { confirmationToken: string; report: { before: { workDays: number }; after: { workDays: number }; items: { id: string; code: string; description: string; quantity: number; oldUnitCostCents: number | null; newUnitCostCents: number | null; deltaDirectCents: number | null }[] } };
const reais = (cents: number | null) => cents == null ? 'Preço ausente' : (cents / 100).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
export default function InfraProjects() {
  const [projects, setProjects] = useState<InfraProject[]>([]), [cycles, setCycles] = useState<InfraCycle[]>([]), [admin, setAdmin] = useState(false);
  const [error, setError] = useState(''), [busy, setBusy] = useState(false), [trash, setTrash] = useState(false), [newProject, setNew] = useState(false), [example, setExample] = useState(false);
  const [name, setName] = useState('Novo orçamento'), [cycleId, setCycleId] = useState(''), [uf, setUf] = useState('SP'), [regime, setRegime] = useState('SD');
  const [selected, setSelected] = useState<InfraProject | null>(null), [versions, setVersions] = useState<Version[]>([]), [migration, setMigration] = useState<Migration | null>(null), [targetCycle, setTarget] = useState('');
  const [policies, setPolicies] = useState<{ name: string; data: { text: string }; version: number }[]>([]);
  const load = useCallback(async (archived = trash) => {
    const [access, documents, references] = await Promise.all([infraAccess(), infraApi<{ items: InfraProject[] }>('/projects?trash=' + archived), infraApi<{ items: InfraCycle[] }>('/cycles')]);
    if (!access.enabled) throw new Error('Seu acesso ao Infraestrutura ainda não está ativo.');
    setAdmin(access.role === 'ADMIN'); setProjects(infraItems(documents)); setCycles(infraItems(references));
    const first = infraItems(references).find(c => c.status === 'PUBLISHED');
    setCycleId(previous => previous || first?.id || '');
    const query = new URLSearchParams(window.location.search);
    setNew(query.has('novo') || query.has('exemplo')); setExample(query.has('exemplo'));
    const requested = infraItems(documents).find(p => p.id === query.get('versoes'));
    if (requested) { setSelected(requested); setVersions(infraItems(await infraApi<{ items: Version[] }>('/projects/' + requested.id + '/versions'))); }
  }, [trash]);
  useEffect(() => { let active = true; if (ORCAPRO_ONLY) return; void Promise.resolve().then(() => load(trash)).catch(cause => { if (!active) return; if (cause instanceof ApiError && cause.status === 401) window.location.assign('/login/?next=/orcapro-infraestrutura'); else setError(cause instanceof Error ? cause.message : 'Falha ao listar projetos.'); }); return () => { active = false; }; }, [load, trash]);
  async function action(fn: () => Promise<void>) { setBusy(true); setError(''); try { await fn(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Falha na operação.'); } finally { setBusy(false); } }
  async function create(event: FormEvent) { event.preventDefault(); await action(async () => { const project = await infraApi<InfraProject>('/projects', { method: 'POST', body: JSON.stringify({ cycleId, name, uf: projectUf, regime, example }) }); window.location.assign('/orcapro-infraestrutura/editor/?id=' + project.id); }); }
  async function history(project: InfraProject) { await action(async () => { setSelected(project); setMigration(null); setVersions(infraItems(await infraApi<{ items: Version[] }>('/projects/' + project.id + '/versions'))); }); }
  async function compare() { if (!selected || !targetCycle) return; await action(async () => { setMigration(await infraApi<Migration>('/projects/' + selected.id + '/migrate-cycle', { method: 'POST', body: JSON.stringify({ cycleId: targetCycle, version: selected.version, dryRun: true }) })); }); }
  if (ORCAPRO_ONLY) return <InfraShell title="OrçaPro Infraestrutura"><p>Este programa está disponível no ambiente de desenvolvimento.</p></InfraShell>;
  const selectedCycle = cycles.find(c => c.id === cycleId);
  const availableUfs = selectedCycle?.validation?.ufs || (selectedCycle ? [selectedCycle.uf] : ['SP']);
  const projectUf = availableUfs.includes(uf) ? uf : availableUfs[0];
  return <InfraShell title="Meus orçamentos SICRO" admin={admin}>
    {error ? <p className={styles.error} role="alert">{error}</p> : null}
    <section className={styles.panel}><div className={styles.sectionHeader}><h2>Orçamentos e cronogramas</h2><div className={styles.actions}><button className={styles.primary} onClick={() => { setNew(true); setExample(false); }}>Novo orçamento</button><button onClick={() => { setNew(true); setExample(true); setName('Exemplo — construção de rodovia'); }}>Criar projeto de exemplo</button><label><input type="checkbox" checked={trash} onChange={e => setTrash(e.target.checked)} /> Lixeira</label></div></div>
      <p className={styles.muted}>Cada orçamento mantém sua referência SICRO e seu histórico. Uma nova publicação não altera projetos existentes.</p>
      <div className={styles.tablewrap}><table><thead><tr><th>Nome</th><th>Referência</th><th>UF / regime</th><th>Versão</th><th>Ações</th></tr></thead><tbody>{projects.map(p => <tr key={p.id}><td><strong>{p.name}</strong></td><td>{cycles.find(c => c.id === p.cycleId)?.ref || 'Referência histórica'}</td><td>{p.uf} / {p.regime}</td><td>{p.version}</td><td><div className={styles.actions}>{!trash ? <><Link className={styles.linkbutton} href={'/orcapro-infraestrutura/editor/?id=' + p.id}>Abrir</Link><button disabled={busy} onClick={() => void history(p)}>Versões e migração</button><button disabled={busy} onClick={() => void action(async () => { await infraApi('/projects/' + p.id + '/duplicate', { method: 'POST', body: JSON.stringify({ name: p.name + ' — cópia' }) }); await load(); })}>Duplicar</button></> : null}<button disabled={busy} onClick={() => void action(async () => { if (!trash && !confirm('Mover este projeto para a lixeira? Ele poderá ser restaurado.')) return; await infraApi('/projects/' + p.id + (trash ? '/unarchive' : ''), { method: trash ? 'POST' : 'DELETE', body: JSON.stringify({ version: p.version }) }); await load(); })}>{trash ? 'Restaurar' : 'Mover para lixeira'}</button></div></td></tr>)}</tbody></table></div>{!projects.length ? <p className={styles.muted}>Nenhum orçamento nesta consulta.</p> : null}
    </section>
    {newProject ? <section className={styles.panel}><h2>{example ? 'Criar exemplo da rodovia' : 'Novo orçamento privado'}</h2><form className={styles.form} onSubmit={create}><label>Nome<input required maxLength={200} value={name} onChange={e => setName(e.target.value)} /></label><label>Referência SICRO<select required value={cycleId} onChange={e => setCycleId(e.target.value)}>{cycles.filter(c => c.status === 'PUBLISHED').map(c => <option key={c.id} value={c.id}>{c.uf} · {c.ref}</option>)}</select></label><label>UF<select value={projectUf} onChange={e => setUf(e.target.value)}>{availableUfs.map(u => <option key={u}>{u}</option>)}</select></label><label>Regime<select value={regime} onChange={e => setRegime(e.target.value)}><option value="SD">Não desonerado</option><option value="CD">Desonerado</option><option value="SE">Sem encargos</option></select></label><button className={styles.primary} disabled={busy || !cycleId}>Criar e abrir</button><button type="button" onClick={() => setNew(false)}>Cancelar</button></form></section> : null}
    {selected ? <section className={styles.panel}><div className={styles.sectionHeader}><h2>{selected.name} — versões e referência</h2><button onClick={() => { setSelected(null); setMigration(null); }}>Fechar</button></div><p className={styles.muted}>Restaurar uma versão cria uma nova versão do orçamento. A migração SICRO exige comparação e confirmação.</p><div className={styles.actions}>{versions.map(v => <button key={v.version} disabled={busy} onClick={() => void action(async () => { if (!confirm('Restaurar a versão ' + v.version + '? O estado atual será preservado no histórico.')) return; await infraApi(`/projects/${selected.id}/restore/${v.version}`, { method: 'POST', body: JSON.stringify({ version: selected.version }) }); await load(); setSelected(null); })}>Restaurar versão {v.version}</button>)}</div><div className={styles.form}><label>Migrar para<select value={targetCycle} onChange={e => { setTarget(e.target.value); setMigration(null); }}><option value="">Selecione…</option>{cycles.filter(c => c.status === 'PUBLISHED' && c.id !== selected.cycleId).map(c => <option key={c.id} value={c.id}>{c.uf} · {c.ref}</option>)}</select></label><button disabled={busy || !targetCycle} onClick={() => void compare()}>Comparar custos</button></div>{migration ? <div className={styles.report}><h3>Comparação antes / depois</h3><p>Prazo: {migration.report.before.workDays} → {migration.report.after.workDays} dias úteis.</p><div className={styles.tablewrap}><table><thead><tr><th>Código</th><th>Serviço</th><th>Quantidade</th><th>Custo unitário anterior</th><th>Custo unitário novo</th><th>Variação do custo direto</th></tr></thead><tbody>{migration.report.items.map(item => <tr key={item.id}><td>{item.code}</td><td>{item.description}</td><td>{item.quantity.toLocaleString('pt-BR')}</td><td>{reais(item.oldUnitCostCents)}</td><td>{reais(item.newUnitCostCents)}</td><td>{reais(item.deltaDirectCents)}</td></tr>)}</tbody></table></div><button className={styles.primary} disabled={busy} onClick={() => void action(async () => { if (!confirm('Confirmar a migração após revisar os custos e as pendências?')) return; await infraApi(`/projects/${selected.id}/migrate-cycle`, { method: 'POST', body: JSON.stringify({ cycleId: targetCycle, version: selected.version, dryRun: false, confirmationToken: migration.confirmationToken }) }); await load(); setSelected(null); setMigration(null); })}>Confirmar migração</button></div> : null}</section> : null}
    <section className={styles.panel}><h2>Privacidade e seus dados</h2><div className={styles.actions}><button disabled={busy} onClick={() => void action(async () => infraDownload('/me/export/archive', 'OrcaPro_Infraestrutura_meus_dados.json.gz'))}>Exportar meus dados</button><button onClick={() => void action(async () => setPolicies(infraItems(await infraApi<{ items: typeof policies }>('/policies'))))}>Política de privacidade e termos</button><button disabled={busy} onClick={() => void action(async () => { const confirmation = prompt('Esta ação encerra o acesso ao Infraestrutura e coloca seus dados na lixeira, sujeitos à política de retenção. Os outros programas são preservados. Para confirmar, digite EXCLUIR MEUS DADOS.'); if (confirmation !== 'EXCLUIR MEUS DADOS') return; await infraApi('/me/data', { method: 'DELETE', body: JSON.stringify({ confirm: confirmation }) }); window.location.assign('/programas'); })}>Solicitar exclusão dos meus dados</button></div>{policies.map(p => <details key={p.name}><summary>{p.name === 'privacy' ? 'Política de privacidade' : 'Termos de uso'}</summary><p style={{ whiteSpace: 'pre-wrap' }}>{p.data.text}</p></details>)}</section>
  </InfraShell>;
}
